### ISSUE TITLE
flipped = true will never be set on a door

### ISSUE THREAD

**Issue by marchello2000** [Autodesk/revit-ifc#10]
This line of code will never result in `flipped == true`:
```
flipped = MathUtil.IsAlmostEqual(Math.Abs(zVec.Z), -1.0);
```
Because it's comparing a positive number to `-1`

https://github.com/Autodesk/revit-ifc/blob/2b32380548054bfe4063ab17806124e921e36534/Source/Revit.IFC.Export/Utility/DoorWindowInfo.cs#L193

**Comment by AngelVelezSosa** [comment]
Thanks for the catch - I've alerted the team to fix this.

**Comment by WawanSolihin** [comment]
There is an ongoing work to improve this code for IFC4RV certification. As part of the improvement, this line of code will no longer be used. The code is not yet in the Master branch, but will likely be integrated for the next released version.

**Comment by AngelVelezSosa** [comment]
I am closing this issue for now; we can re-open if the problem persists after the next integration.
