### ISSUE TITLE
Where is IFC guid stored?

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#100]
Is the IFC-GUID stored in Revit unless you check the following checkbox?
![image](https://user-images.githubusercontent.com/5968613/55585875-f2c74f00-5727-11e9-8e30-c73f12d30399.png)
Is the GUID expected to be stable in the future exports of the same element if it's not strored as a parameter in Revit?

**Comment by AngelVelezSosa** [comment]
The GUID is expected to be stable, but this checkbox future-proofs against any necessary (or unexpected) changes based on a newer version of the IFC.  It isn't necessary, which is why it is in the Advanced tab.

**Comment by eibre** [comment]
Thanks! Is it possible to figure out the Revit element that correspond to a certain guid if the option was not checked during export? Is there a mapping saved somewhere else or is the IFC guid based on revits unique id somwhow? We want to parse a bcf file and get the elements in Revit based the IFC guids stored in the file.

**Comment by AngelVelezSosa** [comment]
The general way to generate the GUID is to use a base GUID and XOR with the element id.  But not sure you have access to that GUID in BCF.  The element id isn't in the tag in BCF?

**Comment by eibre** [comment]
I guess we can look up the element id in the IFC file by the GUID from BCF. Thanks for the info Angel!

**Comment by klacol** [comment]
Please be aware of changing GUID's when changing the phase, see #65.
