### ISSUE TITLE
Random IFC GUID for walls at each export

### ISSUE THREAD

**Issue by felixcharvin** [Autodesk/revit-ifc#109]
I'm using Revit 2019.2.1, IFC export 19.2 and I encountered an issue with IFC export and more particularly generation of IFC GUID.
In my project I have 23 walls which their IFC GUID change at each IFC export and it's a problem for managing database.
I did some tests, isolate only walls and export them multiple times to IFC. I also tried to predict IFC GUID before export on Dynamo and I found that IFC GUID are generated with the method CreateAlternateGUID (revit API, Class ExporterIFCUtils) and if the IFC GUID already exists for another object the GUID will be random.
My question is why we don't use CreateSubElementGUID method from revit API to handle duplicate GUID so they will be no more random on GUID?

Link for method CreateSubElementGUID : http://www.revitapidocs.com/2018.2/f982827b-fa34-be50-fe11-abc4f884f574.htm

On this capture, blue walls always have constant IFC GUID for each IFC export but orange walls always have random IFC GUID.
![Capture d’écran (58)](https://user-images.githubusercontent.com/19908633/57920351-1e973200-789b-11e9-97b5-4a2c58694994.png)

On this excel file we have revit unique ID, Tag Id, and generated IFC GUID for each wall.
[Explication_random_IFC_GUID.xlsx](https://github.com/Autodesk/revit-ifc/files/3190932/Explication_random_IFC_GUID.xlsx)

I also have generated 2 IFC to compare GUID, tell me if you need them.
Thanks

**Comment by AngelVelezSosa** [comment]
Could you send me some watered down version of that file that shows the problem for one wall?  You can send it to angel.velez@autodesk.com.  It will be confidential.  It's unclear why those walls would have random GUIDs.
