### ISSUE TITLE
Some IFC types are no longer set on export

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#11]
The following export mappings no longer work completely:

| Revit object | Previously possible | Result with 18.4 |
| --- | --- | --- |
| Wall | IfcFooting.STRIP_FOOTING | IfcFooting.NOTDEFINED |
| Loadable Family (Structural Foundations) | IfcFooting.PAD_FOOTING | IfcFooting.NOTDEFINED |
| Loadable Family (Structural Foundations) | IfcPile.SUPPORT | IfcPile.NOTDEFINED |

This is a regression that must have slipped in at some point between (probably) 18.2 and 18.4

## Steps to reproduce
* Open the following model
https://github.com/andydandy74/MyIssues/raw/master/RevitIFC11/MissingTypeAssignments.rvt
* Export with older exporter version
* Export with newer exporter version
* Compare the two IFC files in a text editor and notice that in the newer file all element types are assigned the NOTDEFINED value

**Comment by WawanSolihin** [comment]
Is this for IFC2x3 or IFC4?

**Comment by andydandy74** [comment]
Sorry, ifc2x3 :-)

**Comment by WawanSolihin** [comment]
There is a bug that is a side effect when a work to improve consistency of Object and TypeObject during export that cause some of the PredefinedType not exported correctly. This is fixed and should be in the next release when the work in the certification branch is merged into the master.

**Comment by dvrvb** [comment]
I assume that this is the same issue as the last message (on bottom of the page) in the topic https://sourceforge.net/p/ifcexporter/discussion/general/thread/b6a9156b/
That was tested for IFC4RV.

**Comment by AngelVelezSosa** [comment]
Closing for now but this should be checked when v19.2 comes out.
