### ISSUE TITLE
Link IFC: Is it possible to not import category?

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#111]
I tried to set IfcSpaces to "Not Imported" in the ifc mapping file found in File > Open > IFC Options, but the spaces are still linked as generic models.
![image](https://user-images.githubusercontent.com/5968613/58231127-7ff55000-7d36-11e9-97a3-7dc43035c555.png)

**Comment by andydandy74** [comment]
Try ```Don't import``` instead.

**Comment by eibre** [comment]
Thanks @andydandy74. I did a new test with `Don't import`, but the generic model spaces are still there.

**Comment by eibre** [comment]
I tried again with https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v21.1.0.0 and `DontImport`worked
