### ISSUE TITLE
Release of 2020 version

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#114]
When is it planned to release the 2020 plugin version? I normally wait to do our rollout, until the plugin have been updated. Might be overkill..
So also wondering how much difference there is currently between the open source / App Store version and the base product, at point of Revit X.0.0 product release?

**Comment by AngelVelezSosa** [comment]
See #115 for the roadmap.  Open source and app store versions should be the same, +/- a week or two to synchronize them.
