### ISSUE TITLE
IFC4 Export Certification

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#115]
Any ETA on the IFC4 Export Certification?

**Comment by AngelVelezSosa** [comment]
This is tied to #114 .  Roadmap: Get v19.2 changes synchronized with the development version (in progress), make sure they pass automated and manual test.  Get these changes back into v19.3 and v20.1.  Finish upgrade from RV1.1 to RV1.2 to wrap up architectural export certification.  Move on to structural and MEP certifications.
