### ISSUE TITLE
Revit AddIN migration from 2019 to 2020 

### ISSUE THREAD

**Issue by theextremeandy** [Autodesk/revit-ifc#119]
The UserInterfaceUtility.dll assembly in Revit 2020 does not contain type ChildWindow!
When we call a xaml window we receive the following error: 

Error	XDG0008	The name "ChildWindow" does not exist in the namespace "clr-namespace:Autodesk.Revit.WPFFramework;assembly=UserInterfaceUtility".

Nobody has an idea or solution for this problem?
Thanks
Andy

**Comment by AngelVelezSosa** [comment]
We haven't yet put in the source code for Revit 2020.  We are finalizing the last integration issues now.
