### ISSUE TITLE
IfcBuildingElementProxy CompositionType IFC2x3

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#121]
Just a minor issue.

Revit 2019.2.1 | IFC exporter 19.2.0.0
When exporting an IfcBuildingElementProxy, the 9th position in the definition now gets the attribute PredefinedType (with default value USERDEFINED). That's OK for IFC4.
But for IFC2x3 this 9th position should be the attribute CompositionType (default ELEMENT).

Regards,
Dirk

[2019-07-12 IfcBuildingElementProxy CompositionType.zip](https://github.com/Autodesk/revit-ifc/files/3385928/2019-07-12.IfcBuildingElementProxy.CompositionType.zip)

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/41319048/61119387-fe4eb280-a49a-11e9-9988-e3a19d2a9817.png">

**Comment by AngelVelezSosa** [comment]
Thanks, we are wrapping up 19.3 issues but we'll include this.

**Comment by dvrvb** [comment]
Not yet fixed. Probably for one of the next rounds.
Issue checked for R2020 with 20.1.0.1, export to IFC2x3CV2.0 :
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/41319048/63654546-f5c8e780-c77b-11e9-8458-75a97bfb0796.png">
