### ISSUE TITLE
Ceiling Grid visibility in IFC

### ISSUE THREAD

**Issue by EvaEriksson** [Autodesk/revit-ifc#126]
The ceiling grid in Revit is part of the material and since material patterns don't export to IFC every ceiling surface exports as a flat surface, without grid. This makes it impossible to do cross-disciplinary coordination for ceilings outside Revit and the IFC file cannot be used on site for determining the ceiling grid placement, forcing us to make drawings when we want to only deliver the IFC model.

Is it possible to add the grid pattern to the ceiling object on export?

**Comment by AngelVelezSosa** [comment]
Material patterns don't show up in IFC because they are not part of any MVD.  We could add them as an add-on to an MVD, but that would technically be an incorrect IFC file, and no other application would be required to read them, or even if they did read them, read them correctly.  I remember many years ago an attempt to exchange patterns that failed because of a disagreement of model vs. annotation patterns. This probably should be brought up in https://forums.buildingsmart.org as a request to either extend an MVD, or have an add-on that would support this information.

**Comment by torgeirfadnes** [comment]
@AngelVelezSosa; I understand that there is a solution already in place for it in ArchiCAD, so i bet something similar can be done in Revit. To make a definition change to the IFC Schema is probably a long term solution, but what we need at this point is a quick fix with a workaround of some sort. 

Maybe the short term solution would be to change the way Revit handles the ceiling grid to something more similar to Sloped Glazing model based grid.

Model based construction and coordination is being held back by the lack of ceiling grids.

*I hope this can get a high priority*

**Comment by AngelVelezSosa** [comment]
I totally agree that there can be a short term solution, but unless it is actually agreed to by everyone, then you don't know that anyone else can read it.  Maybe the really short-term solution is to model the ceiling grid using some other way?  Curtain systems are already abused anyway, would they work?

**Comment by EvaEriksson** [comment]
We have thought of using curtain systems but those are part of roofs and the roof category can not be overridden through IfcExportAs. Neither can walls. So using that would result in a faulty IFC file.

**Comment by tsolsen** [comment]
We would often use curtain systems for ceilings in detailed design, if they could export to ceilings. Have the exact features that ceilings are missing with unique panels and member profiling.

**Comment by AngelVelezSosa** [comment]
That may be an easier short-term solution, to get IfcExportAs Ceiling to work for curtain systems and roofs.  Let me look into that.

**Comment by evapeva** [comment]
@AngelVelezSosa 
Have you looked at the possibility to allow IFCExportAs to work on all object categories?

**Comment by AngelVelezSosa** [comment]
Yes; the current implementation makes it hard to do it generically.  But that's something we'd like to do.

**Comment by torgeirfadnes** [comment]
@AngelVelezSosa Any ETA on when it will be possible to IFCExportAs to work for Roofs and Curtain Systems to Ceilings? I these are the ones we need first, if this is faster than making a generic solution for everything to everything.

**Comment by AngelVelezSosa** [comment]
We are working on a few things for our next update, but we hope to have roofs-as-anything be part of it.

**Comment by AngelVelezSosa** [comment]
Note as an update: ceiling grids are exported to IFC now.
