### ISSUE TITLE
The state of the checkbox "Export only schedules containing IFC, Pset, or Common in the tile" is not saved.

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#13]
Version:
Revit 2019.0.1 
IFC for Revit 2019 v19.1

Issue:
The state of the checkbox "Export only schedules containing IFC, Pset, or Common in the tile" is not saved when creating custom export setup.

Steps to reproduce:
1) Create new export setup
2) Under the tab "Propery Sets" check "Export schedules as propery sets" and "Export only schedules containing IFC, Pset, or Common in the tile"
3) Export a file
4) Start a new IFC export and go to the "Property Sets" tab. The checkbox "Export only schedules containing IFC, Pset, or Common in the tile" is now unticked.

First when a new export setup is created:
![image](https://user-images.githubusercontent.com/5968613/43834028-01b96c6e-9b0d-11e8-9a35-ff45508a595a.png)
Second on nect export and the same setups is chosen:
![image](https://user-images.githubusercontent.com/5968613/43834069-1e9349d6-9b0d-11e8-9752-933090d809e0.png)

**Comment by andydandy74** [comment]
I also reported this in June. Apparently it's a known issue, tracked as REVIT-129461.
