### ISSUE TITLE
Exporter version 19.3 - Originating System

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#132]
Looks to me as the exports from IFC-2019.3.0.0 version, in Originating System signs as `Exporter 19.1.0.0`.
Can anyone confirm?

**Comment by dvrvb** [comment]
For IFC4 RV1.2 as well as for IFC2x3 CV2.0 it seems the output in IFC is correctly reporting 19.3.0.0
![2019-09-23](https://user-images.githubusercontent.com/41319048/65431985-ab8a6300-de1a-11e9-9545-8485f74b4082.jpg)
Regards,
Dirk

**Comment by tsolsen** [comment]
Thank you @dvrvb Then it must be something with my install.

**Comment by dvrvb** [comment]
I hope you'll get your install fixed, so you can enjoy all the improvements that are made in 19.3
