### ISSUE TITLE
Bounded Value

### ISSUE THREAD

**Issue by MichCarr** [Autodesk/revit-ifc#139]
Hi everybody,

I am trying to export a parameter (e.g. _NominalPartLoadRatio for IfcBoiler_) that should be filled with a _Bounded Value_ (https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/link/ifcpropertyboundedvalue.htm) following the IFC standard.

**Is there any way to specify such a type of Property in Revit?**
I saw that the relevant parameter in Autodesk IFC shared parameters file is a "Multiline Text" Parameter; maybe there is a method to fill in the parameter to obtain the desired result.

Thank you in advance!

**Comment by AngelVelezSosa** [comment]
Revit itself doesn't have a concept of a bounded parameter.  I will mention this internally to the team that is looking to improve parameters in Revit.
