### ISSUE TITLE
IFC GUID changes Revit 2019

### ISSUE THREAD

**Issue by HenkMolhoek** [Autodesk/revit-ifc#143]
When using the tab Steel in Revit 2019 for connections and parametric cuts, the Guid changes for those elements. This happens with the 19.3 and 19.2 IFC exporter.

[Documents.zip](https://github.com/Autodesk/revit-ifc/files/3901438/Documents.zip)

**Comment by JOuellette-Autodesk** [comment]
Cannot duplicate. The attached file has too many dependencies not included.
