### ISSUE TITLE
Question about IFCSYSTEM exported from REVIT

### ISSUE THREAD

**Issue by Hirak2019** [Autodesk/revit-ifc#151]
hello
I have a question about exporting electrical systems from revit
in my example I have an electrical IFCSYSTEM exported as follows 
#2256= IFCSYSTEM('12mLpqpwz11gYqQ8OPIoBM',#42,'4',$,'');
#2257= IFCRELSERVICESBUILDINGS('2GDrMo8a18bfI6dSu7tezM',#42,$,$,#2256,(#122));
#2260= IFCRELASSIGNSTOGROUP('2BQPoH$p11R9tPZHs99GHP',#42,$,$,(#987,#1336,#1512,#1580),.PRODUCT.,#2256);

the elements constituting the IfcSystem are obtained from IFCRELASSIGNSTOGROUP and they are 
(#987,#1336,#1512,#1580)

my question is:
are the elements ordered so that the panel supplying the circuit would be the first in the list? in my example it would be #987

Thank you

**Comment by AngelVelezSosa** [comment]
I don't think there's any particular sorting here.
