### ISSUE TITLE
Reference to Autodesk.UI.Windows is missing

### ISSUE THREAD

**Issue by Jaterroso** [Autodesk/revit-ifc#163]
Hello,

I am studying the Revit-ifc solution, as I intend to create a custom exporter. I have updated succesfully al references though Nuget, except for the Autodesk.UI.Windows in IFCExporterUIOverride project. 
Where do I find the library? I have searched though the the Revit and the SDK folders and googled a bit, but found nothing related to it.

**Comment by Jaterroso** [comment]
Anyone? it is a really simple question...

**Comment by dvrvb** [comment]
C:\Program Files\Autodesk\Revit 2020\Autodesk.UI.Windows.dll

![image](https://user-images.githubusercontent.com/41319048/78016025-87b85480-734a-11ea-9b27-a5e349c190c6.png)

**Comment by Jaterroso** [comment]
Thanks, but it does not solve my issue:
 According to the description "IFC for Revit 2019 and beyond", it should be possible to run the project on Revit 2019. That is the issue:  I am using Revit 2019 and the library is not included in the corresponding path.... However, I can successfully run the custom exporter (compiled and downloaded from Autodesk app store) from Revit¿¿¿???

**Comment by dvrvb** [comment]
for 2019 you have to use the solution @ https://github.com/Autodesk/revit-ifc/tree/Release_19.x.x
The 2019 version seems not have that reference. So it isn't missing.
![image](https://user-images.githubusercontent.com/41319048/78018721-b20c1100-734e-11ea-9372-41e5dbc136c5.png)

**Comment by Jaterroso** [comment]
Thanks a lot, Dirk
It would not hurt to have a visible link or a fork to to the 2019 version...

I had previously tried to download the specific 2019 project, but I downloaded it from the sourceforge site instead https://sourceforge.net/projects/ifcexporter/ I found out that that version was broken  
![image](https://user-images.githubusercontent.com/62424097/78019505-1c718100-7350-11ea-82f9-63a174f2a3c0.png)

The project you referenced seems to be correct. Again, thanks a lot
