### ISSUE TITLE
Max IFC Export Size Restriction, 1GB?

### ISSUE THREAD

**Issue by Pengeace** [Autodesk/revit-ifc#197]
In exporting a 125M RVT file to IFC, a dialog box with the message "Fatal error" appears.
In the log file, I find a message of `Error: Max model data size is reached.`

Then, I delete about 1/6 products in this RVT file and export it to IFC again. This time the IFC export process ends successfully with a 740M IFC file.

I find that a post in the Revit offical website points out this below message [here](https://knowledge.autodesk.com/support/revit-products/troubleshooting/caas/sfdcarticles/sfdcarticles/Revit-shows-no-response-when-exporting-model-to-IFC-File.html).
> Revit has the capability to export to an IFC file format, however, the file cannot be larger than 1 GB.

I want to know if there is a workaround to avoid this restriction or modify the 1GB  threshold value?

Thanks!

**Comment by AngelVelezSosa** [comment]
Hi, this is a restriction of the toolkit we use to read and write IFC files, not a Revit restriction.  It is actually based an when a cached file reaches 4GB on disk, which is impossible to know exactly when it happens.  Changing tessellation co told can help, and we are working in an option that automatically reduces the tessellation for extra large objects.  But unfortunately the limitaction is a hard limit for now.

**Comment by Pengeace** [comment]
Many thanks for your valuable explanation and advice! 

As you have pointed out, the above problem is mainly caused by the underlying EDM toolkit having the 4GB size limitation for cache files. (wondering that if it is possible to replace the EDM tool with other implementations). 
Hope that there will be a better solution for this restriction in the future. Thank you again!
