### ISSUE TITLE
Rebar exports with wrong height

### ISSUE THREAD

**Issue by josols** [Autodesk/revit-ifc#2]
Hi, first github issue! :)

We have been continiously exporting a rebar model to IFC over some time and suddenly the rebars gets exported with some strange heights. This has apparantly occurred without doing anything in the Revit model. We are completely lost as to what the error can be, any clues?
![image](https://user-images.githubusercontent.com/7080648/42025263-6b613ade-7ac4-11e8-9c8f-72c863545225.png)

**Comment by josols** [comment]
we've found the issue, we had defined IfcExportAs og IfcExportType as IfcRebar. This should probably not cause rebars to move?

**Comment by AngelVelezSosa** [comment]
No, that probably shouldn't.  What version of Revit/IFC are you on?  We did fix some positioning issues with v18.4/v19.1.

**Comment by WawanSolihin** [comment]
I am trying to clear reported issues here. Looking at this report, it looks old and we have done quite some works for IFC4 certification that has requirements for Rebar. We passed that certification, so I expect this issue to be fixed already in the latest 2019/2020/2021 IfcExporter releases.

**Comment by JOuellette-Autodesk** [comment]
Closed as Revit (2023) has passed IFC4 RV1.2 certification. See @WawanSolihin comment above
