### ISSUE TITLE
Support for IfcSystem for building elements

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#204]
I'm missing the ability, to collect my building elements, into IfcSystem. This would allow us, to use the schema method, when wanting to relate elements to each other.

I'm assuming shared parameters as IfcSystem and IfcSystem[Type] would be the straightforward implementation.
Preferred would be, to on export point to a RVT parameter, and appoint that as a system parameter.

**Comment by AngelVelezSosa** [comment]
If you create an assembly, you can use the IfcExportAs shared parameter to export it as an IfcSystem.  You can also export a Revit group using the same parameter as an IfcBuildingSystem (in IFC4) of IfcFurniture.  Should expand groups to also support systems.

**Comment by tsolsen** [comment]
I was not aware of that posibility. Thank you.

It's just that I was perhaps looking for a less involved setup :)
If we have to collect elements into assemblies and groups, they are locked and needs to be managed also - and the system is the assembly/group.
My initial thought was to reference an instance to a IfcBuildingSystem, as we can reference a room to a IfcZone (Name, Description, Type).
Users would use those parameters, equally to any other parameters.
IfcInventory would also be nice, so we could collect rooms and their furniture, to measure against a FFE program.

Is it allowed in IFC, for an object, to reference more than one system?

**Comment by jmirtsch** [comment]
Hi Troels,

It is also possible to manage aspects such as systems outside of revit, and then merging this information (with say system assignment) into an IFC generated from Revit.  I've done some development of a excel tools to do this for Transport for New South Wales.  There is a demonstration and explanation of this in the video here.  https://drive.google.com/file/d/1TZUVKYUxcBAfH3e5j63L3vmZcifdw8SV/view?usp=sharing  Get in touch if you'd like to learn more about this approach.

Cheers,

Jon

**Comment by Emanuel-EP** [comment]
Is it possible to add a custom Pset to IfcSystem?

This doesn't work:
PropertySet:	Cust_System	I	IfcElement, IfcSystem
	Supplier	Text	Supplier
