### ISSUE TITLE
StairRiserTreadsCalculator

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#21]
Is the StairRiserThreadsCalculator.cs missing in Exporter\PropertySet\Calculators\,
or can the line 131 `<Compile` Include="Exporter\PropertySet\Calculators\StairRiserTreadsCalculator.cs" /> `be eliminated in  
revit-ifc-IFC4RV-Certification\Source\Revit.IFC.Export\Revit.IFC.Export.csproj ?

**Comment by WawanSolihin** [comment]
The project setting has been updated that removes the obsolete "Exporter\PropertySet\Calculators\StairRiserTreadsCalculator.cs" and add several other missing calculators (commit: bd70fc6)
