### ISSUE TITLE
IFC Shared Parameters-RevitIFCBuiltIn-Type_ALL.txt does not seem to apply

### ISSUE THREAD

**Issue by Moult** [Autodesk/revit-ifc#217]
The presence of https://github.com/Autodesk/revit-ifc/blob/master/Install/Program%20Files%20to%20Install/IFC%20Shared%20Parameters-RevitIFCBuiltIn-Type_ALL.txt suggests that these parameters can be used to override attributes.

A quick test of using this file to create an `IfcName[Type]` type-based parameter in a project, and giving it a value, shows that it is not taken into account during export.

Am I using it wrong, or what is the purpose of this shared parameters file?

**Comment by AngelVelezSosa** [comment]
That is indeed the purpose of the file; checking with team to see why that wouldn't work.

**Comment by WawanSolihin** [comment]
I did some tests and it appears that it works as intended. Attached is a very simple example model that has IfcName[Type] assigned to both objects (Wall and Model in Place).
[Tests.zip](https://github.com/Autodesk/revit-ifc/files/5045714/Tests.zip)

**Comment by Moult** [comment]
@WawanSolihin I see. It seems as though it is broken in the bundled version of 2019.2 (tested with your files) but works in the latest release of the plug-in (confirmed with your files).

Cheers and thanks!
