### ISSUE TITLE
Regression on Grid export

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#225]
Hi,

I can't find grids exported from the latest exporter versions, testet in RVT 2020.2.2 and 2021.
Can anyone confirm, they are experiencing the same regression?

**Comment by AngelVelezSosa** [comment]
There is a bug where the export layers table set grids to Not Exported instead of IfcGrid by default.  This bug is old and has been corrected for a future release, but just check the default settings and change them.

**Comment by tsolsen** [comment]
That was it. Thank you! I never go into that table any longer, so would have hard time, figuring out where to look.
