### ISSUE TITLE
ColumnBaseQuantities - CrossSectionArea

### ISSUE THREAD

**Issue by yarph** [Autodesk/revit-ifc#226]
The CrossSectionArea of the ColumnBaseQuantities set is reported in square feet. GrossVolume and OuterSurfaceArea seem to mix feet and meters.
![image](https://user-images.githubusercontent.com/70579680/91844525-ed8d6d00-ec57-11ea-97a6-18443e3e1eb4.png)
In this example it should be 0.25 square meters.
![image](https://user-images.githubusercontent.com/70579680/91844650-24638300-ec58-11ea-820a-97f6a9ae01f1.png)

I'm using Revit 2020.

Thanks,
Thomas

**Comment by AngelVelezSosa** [comment]
We've done a number of corrections on quantities that will be in a future version of the open source - we will verify this one.

**Comment by yarph** [comment]
Forgot about this issue. Looks good in 2024.
