### ISSUE TITLE
Dynamo IFC Export 

### ISSUE THREAD

**Issue by RAJKUMAR-STRUCTURES** [Autodesk/revit-ifc#233]
Hi,
I am using one of IFC export code. The code is exporting 3d views to IFC. I have problem after exporting views all views have has one view only.. check below
![12](https://user-images.githubusercontent.com/71932104/94342057-00fbe000-002c-11eb-93d7-4cacdc6c5070.jpg)
 image for your reference.
![IFC1](https://user-images.githubusercontent.com/71932104/94342162-c181c380-002c-11eb-870b-c7b1c27a1440.jpg)

**Comment by eibre** [comment]
The exporter does not split the objects that are cropped with a section box. You need to do this manually.

**Comment by AngelVelezSosa** [comment]
Correct.  That is by design.   We use the section box only to determine which elements are visible.  In general, we did not want to export half-walls and half-floors (e.g.) to IFC.

**Comment by RAJKUMAR-STRUCTURES** [comment]
Thats ah correct @eibre but my task is i have to export individual 3Dviews. which already enclosed in section box.
Is there any possibility?
