### ISSUE TITLE
Exporting Toposurface

### ISSUE THREAD

**Issue by KKvistgaard** [Autodesk/revit-ifc#236]
Hi

When exporting Revit to IFC, we usually hide elements, that we wont include in the export, either by Filter or by Worksets. This works perfectly for everything but Toposurface. 

When hiding a Toposurface, it does still appear in the IFC export (Revit versions prior to 2021). 
Only work-around is to manually temporary delete the objects, which is time consuming and leaves a big risk for errors.

**Comment by AngelVelezSosa** [comment]
Please try the latest version.  This was a regression that has been fixed in the latest point release.
