### ISSUE TITLE
IFC4 and MVD-restrictions

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#24]
Some questions about IFC4 and MVD-restrictions.

I assume that an IFC-model exported according a particular MVD only can/may contain entities that are defined within the scope of the MVD.
So, if IfcAnnotation isn't part of the scope of IFC4RV1.1, it should not be present in the IFC-model, right?

According to:
http://www.buildingsmart-tech.org/specifications/ifc-view-definition/ifc4-reference-view/comparison-rv-dtv
these entities are not making part of IFC4RV, but are currently exportable with the exporter as IFC4RV:
IfcAnnotation
IfcBeamStandardCase *
IfcColumnStandardCase *
IfcDoorStandardCase *
IfcMemberStandardCase *
IfcPlateStandardCase *
IfcSlabElementedCase *
IfcSlabStandardCase *
IfcWallElementedCase *
IfcWallStandardCase *
IfcWindowStandardCase *
IfcOpeningStandardCase *
IfcVoidingFeature 
IfcSurfaceFeature
IfcVirtualElement
IfcProxy *
IfcExternalSpatialElement []

( * = status changed to Deprecated in IFC4_ADD2_TC1: "this definition may be imported, but shall not be exported by applications." )
( [] = I've mentioned IfcExternalSpatialElement in my issue "IfcSpatialElement", but I suppose that after all for IFC4RV it should not be present in the model )  

**What would be a solution to prevent that these entities are not present in a IFC4RV-model?**

Sidenote:
At the moment it is also possible to export IfcSite/IfcBuilding/IfcBuildingStorey as separate geometry on buildingstoreys (example of cubes with the use of IFCExportAs).
I suppose it is OK that these entities can have independent geometry, but the geometry should than be related directly to the entities in the "spatialstructuralelement"-tree, according to rule WR41, isn't ?
(in the way now the IfcSite geometry is produced by the use of a Topography)

**Comment by AngelVelezSosa** [comment]
Sorry for the slow response - going through some of the issues here.  
Strictly speaking, an IFC model that satisfies an MVD should only contain the allowed items for that MVD.  In the past, there were "add-on" MVDs that you could have that could "extend" what was in the MVD, and many vendors allowed for options that would indeed add extra information that wasn't part of the MVD.  Obviously, this can lead to confusion (e.g. "Revit gives me text froma plan view, why doesn't your application?"

As far as the deprecated ones, we shouldn't be exporting them any more, and before we are certified, we will need to go through everything mentioned above and make sure that we aren't exporting obsolete information.  @WawanSolihin , FYI.
