### ISSUE TITLE
Access to newly certified IFC4 version?

### ISSUE THREAD

**Issue by Moult** [Autodesk/revit-ifc#241]
I hear through the social grapevine that Revit is now certified for IFC4 architectural export!

First of all - congratulations!

So, uh, where do I get this new certified version? https://apps.autodesk.com/RVT/en/Detail/Index?id=8986482933300179260 still shows last updated 8/5/2020.

The 2021 version shows 7/10/2020, is that it? Can the fixes be backported to 2020?

**Comment by AngelVelezSosa** [comment]
We intend to backsubmit the changes to the opem source.  We are waiting to finish up one little thing (don't want to spoil any surprises) that is hopefully wrapping up very soon, and then will update 2019-2021 here and in the App Store.  We intend to include other fixes also.

**Comment by Moult** [comment]
Bump? :) 

https://blogs.autodesk.com/revit/2020/11/10/revit-first-bim-platform-with-dual-ifc4-certification/

**Comment by eibre** [comment]
@Moult Take a look at this commit: https://github.com/Autodesk/revit-ifc/commit/64786c58fd6a34254cbf0e292966459334599fa8

**Comment by AngelVelezSosa** [comment]
This is definitely in progress (as you can see).  We need to do some cleanup and create the install so that the DLLs are signed.  But it a task that is in-progress now (and has been for a number of days).

**Comment by Moult** [comment]
Thanks for the update, and thanks for the commit reference @eibre - but I was referring to a distribution, so that users can access it.

I'll keep watch on this page :) https://apps.autodesk.com/RVT/en/Detail/Index?id=7265544480016320144&appLang=en&os=Win64

**Comment by AngelVelezSosa** [comment]
@Moult : it will be here first.  We've made an initial commit, which will be followed by the final commit and the signed DLLs soon.  It will be here before the App Store, so if you are particularly keen, watch this space first :)

**Comment by Moult** [comment]
Bump?

**Comment by AngelVelezSosa** [comment]
Still chugging along.  No serious delays, just being careful to avoid regressions as much as possible.

**Comment by eibre** [comment]
@Moult https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v21.2.0.0

**Comment by Moult** [comment]
@AngelVelezSosa congratulations! Just a few questions:

 1. When will this be distributed on the store?
 2. When will it be backported for Revit 2020, Revit 2019? etc?

**Comment by AngelVelezSosa** [comment]
I've uploaded it to the store, so has to go through the approval process.  Working on 2020 update now- that's harder because there was some significant API changes around units in 2021.  2019 update will be easier.
