### ISSUE TITLE
If i can convert rvt to ifc without revit or forge?

### ISSUE THREAD

**Issue by Febfire** [Autodesk/revit-ifc#26]
I want to convert rvt to ifc through C#,without revit installed and don't use online forge.
If it's possible?

**Comment by AngelVelezSosa** [comment]
No, because you need some way to open the Revit file, unfortunately.

**Comment by castronelson** [comment]
can please anyone suggests why the RevitAPI.dll not working? if added in a empty project using asp.net

**Comment by castronelson** [comment]
This below error i am getting.
Could not load file or assembly 'RevitAPI' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by castronelson** [comment]
I included the dll in Bin.I got the dll from Nuget Packages and add it in references.
Any solution , Revit file to Ifc conversion and possibilities?
