### ISSUE TITLE
Walls from BlenderBIM not importing

### ISSUE THREAD

**Issue by theoryshaw** [Autodesk/revit-ifc#261]
I wasn't able to import [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/93d2fb7c652fd03e2adc07284bb338171d40c7a9/Random%20Tests/Wall_Zigzag/from_Blender/Wall_Zigzag_02.ifc) file into Revit.

It opens in other IFC viewers. 

Pinging @moult as well, if BlenderBIM issue.

**Comment by AngelVelezSosa** [comment]
I'll check it as soon as my Revit is done importing the current file I've been testing :)

**Comment by Moult** [comment]
Subscribing to issue in case it happens to be a BlenderBIM Add-on bug.

**Comment by AngelVelezSosa** [comment]
It seems OK to me in my Dev version - have you tried in the latest open source version?

Only issue I see:
#106: WARNING: Ignoring unhandled representation item of type IfcMappedItem in Box representation. (This message will only appear once.)

I _think_ this is accurate.  Thoughts?

**Comment by theoryshaw** [comment]
It was tested on both
- Exporter 20.2.30.42 - Alternate UI 20.2.30.42
- Exporter 20.2.1.0 - Alternate UI 20.2.1.0

with Autodesk Revit 2020.

[This](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/93d2fb7c652fd03e2adc07284bb338171d40c7a9/Random%20Tests/Wall_Zigzag/from_Blender/Wall_Zigzag_03.rvt) is the resultant Revit file.

I did not get any warnings, that i saw anyway, when imported.  But as you can see, the Revit file is empty.

**Comment by Moult** [comment]
@AngelVelezSosa I think that warning is incorrect. The representation type is set to `MappedRepresentation. See here: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/mapped-geometry.htm

The docs say "any" is allowed. In this case, the representation identifier is Box.

> IfcShapeRepresentation.RepresentationIdentifier = (any, see above)

**Comment by AngelVelezSosa** [comment]
Autodesk Revit 2020 doesn't have support for IFCPOLYGONALFACESET yet, I don't think.  I think it will come with the IFC4 RV update.  Revit 2021 should read that in just fine.  The "Box" thing can be fixed, although that's a red herring - the issue is IFCPOLYGONALFACESET.  Try it with the Revit 2021 code.

**Comment by JOuellette-Autodesk** [comment]
@AngelVelezSosa 
Testing:
Revit 2023.0.1.318   IFC for Revit 2023.3.5.0

I can "Link IFC" and "Open IFC" with success
[Wall_Zigzag_02.ifc..zip](https://github.com/Autodesk/revit-ifc/files/10934741/Wall_Zigzag_02.ifc.zip)
