### ISSUE TITLE
How to add IfcPostalAddress to site object.

### ISSUE THREAD

**Issue by jokopperud** [Autodesk/revit-ifc#264]
Does revit allow correct export of IFCPostal Adress to IFCSite object?

When checking "assign address to site" in the Project address dialog box in the IFC export interface, the IFCPostalAdress object seems to be linked to the IFCBuilding object and not the Site object and doesen't store the checkmark when opening the Project address dialog box again.

Is there somthing wrong on my side or is there somthing in your code that needs to be altered?

Can you give some advice?

http://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcactorresource/lexical/ifcpostaladdress.htm
![image](https://user-images.githubusercontent.com/41875873/102895056-55183400-4464-11eb-859e-9836e9f334c1.png)

**Comment by eibre** [comment]
This issue seems connected to https://github.com/Autodesk/revit-ifc/pull/235

**Comment by jokopperud** [comment]
do you have an idea @WawanSolihin ?

**Comment by WawanSolihin** [comment]
Yes, currently the selection for Assign address to ... is not remembered. It is a known issue and there a PR, but we have not managed to put that into the code.
The options actually allows the same IfcPostalAddress to IfcSIte and/or IfcBuilding depending which one(s) is being ticked.

**Comment by jokopperud** [comment]
I hear my colleague does not have this issue in Revit versjon 2021.1.2.

So appears to be solved in that version.
