### ISSUE TITLE
IfcGUID option terminated the export

### ISSUE THREAD

**Issue by Teun1** [Autodesk/revit-ifc#266]
We have a model which could not be exported to IFC. But we could export this model  before.
After some testing we could narrow the problem down to the IfcGUID option in the exporter.
While unchecking this option we were able to export. But this should work.
The IFC exporter was 19.4.1.0. We also tried upgrading to 2021 but the problem remains.
Has anybody else had similar problems in the last 6 months? Any tips?

**Comment by ArjanPeeters** [comment]
I’ve had the same problem. But the elements need to be editable because of the store ifc huid option. Is the work set checked out?

**Comment by Teun1** [comment]
All the worksets were checked out, as you call it. The people working on the project could not do it. I used detach from central. And I also upgraded to 2021. In all cases it did not work. 
The IfcGUID parameter is read / write for a while now. So I do not know what could be the problem.

**Comment by Teun1** [comment]
The BuiltinParameter IFC_GUID value for VariesBetweenGroups is false. For my part change this BuiltinParameter please to true.
However if a user add this Text parameter manualy as a project parameter BEFORE the first IFC export. With VariesBetweenGroups as true it does work. Otherwise you will be asked to explode the Groups after export. (I will add this to our project template files.)

For our project this is not the problem. Even without all groups it is still not possible to export.

**Comment by Teun1** [comment]
The Text BuiltinParameter IFC_GUID value for VariesBetweenGroups is natively set to false. For my part change this to true please.

But for this project, even without all Groups it is not possible to export.

**Comment by WawanSolihin** [comment]
Can you please test with the latest release (19.5.0.0, or 20.3.2.0, or 21.2.1.0)? There is a similar issue reported regarding export failure when the IfcGUID option is selected.

**Comment by Teun1** [comment]
We will. Thanks WawanSolihin

**Comment by Teun1** [comment]
I did test the original project (Revit 2019) with model groups at the moment. And I was able to export to project with ifcGUID option enabled. After purge all and synchronize I tried to export again again as an IFCZIP. It did seemed more slow than the last time but it did not break. 

So far so good. Thanks. 
And I will close this issue.
