### ISSUE TITLE
Export aborted with ZoneClassificationCode

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#271]
In both 2020, and 2021, I'm getting export aborted exports, when ZoneClassificationCode is filled out on rooms. The files export with zones, when ZoneClassificationCode is not present.
Exporter versions 20.3.1.0 and 21.2.0.

I have it working with 20.2.1.0, before upgrading.

Can anyone confirm this error?

**Comment by AngelVelezSosa** [comment]
We have confirmed this error - it is a regression and are working towards a fix.

**Comment by WawanSolihin** [comment]
Please install the latest release 20.3.2.0 or 21.2.1.0. The issue has been fixed in these releases.
