### ISSUE TITLE
There has been an unrecoverable error during export. Export will now be aborted.

### ISSUE THREAD

**Issue by gvanolst** [Autodesk/revit-ifc#274]
I'm having issues exporting to IFC. Using the latest Revit 2020 and exporter.

https://we.tl/t-aVsLhhnxc0

**Comment by WawanSolihin** [comment]
I tested it with both IFC2x3 and IFC4 RV exports and they are exported fine. I am using the latest **20.3.1.0** exporter.
![image](https://user-images.githubusercontent.com/31854582/108008604-b2cb9580-703b-11eb-83f6-e703461d7aea.png)

**Comment by gvanolst** [comment]
Thank you for testing. I've been testing some more, when I uncheck "Store the IFC GUID in an element parameter after export" the export works fine. But I need this option to be checked.

**Comment by WawanSolihin** [comment]
Thanks, that is the crucial information. I can reproduce it and will look into the issue

**Comment by WawanSolihin** [comment]
Please install the latest release 20.3.2.0. The issue should be fixed in this version.
