### ISSUE TITLE
Issues exporting structural framing under a different ifc name

### ISSUE THREAD

**Issue by Natiolivera** [Autodesk/revit-ifc#279]
Hello everybody,

I am trying to export Structural Framing as IfcMember but when I export the files it changes to IfcEelementAssembly. I have nothing set under this name.

I mapped the category to be exported as IfcMember and also used the IFCExportedAs parameter, neither of them worked.
I attached some pictures for you to see If I am doing something wrong. 

Does anyone know what could be happening?
Thank you all for your time and patience in advance,

![01](https://user-images.githubusercontent.com/79795046/109420436-362ca580-79b1-11eb-8c6c-5252f4083f53.jpg)
![02](https://user-images.githubusercontent.com/79795046/109420437-3d53b380-79b1-11eb-8abe-42cdbc05e0e8.jpg)
![03](https://user-images.githubusercontent.com/79795046/109420438-40e73a80-79b1-11eb-82f3-c561e621125c.jpg)

**Comment by AngelVelezSosa** [comment]
An IfcElementAssembly is a grouping; it shouldn't contain geometry, but instead other IFC entities (in this case, hopefully IfcMembers).  Do the 38 IfcElementAssembly contain the 47 IfcMembers?

**Comment by Natiolivera** [comment]
Angel,

Thank you for your prompt response.

I understand now, It doesn't matter how those Trusses are set up, they will be exported automatically as a group of entities as IfcElementAssembly despite the configuration of each entity because they are all part of a complex geometry. I didn't know about this.

The 47 IfcMembers are not contain in the 38 IfcElementAssembly and that is the reason why they are exported differently, now that you point that out I can see, I should fix that in my model.

The other 38 elements contain IfcMembers indeed. (attached is a picture)

I am just starting with all the IFC world,

Thank you Angel for your help, I really appreciate it

![04](https://user-images.githubusercontent.com/79795046/109422322-db4b7c00-79b9-11eb-9295-7458ebb787cc.jpg)
