### ISSUE TITLE
Volumetric flow rate units

### ISSUE THREAD

**Issue by jmirtsch** [Autodesk/revit-ifc#280]
Hi,  

I posted a pull request last year in response to an apparent issue with the scaling of volumetric flow units.
Has it been considered yet?  https://github.com/Autodesk/revit-ifc/pull/257

Thanks,

Jon

**Comment by BIMLUND** [comment]
Is this the same problem as this: ?
We have set everything to "L/sec" in Revit. When export to IFC. We get the correct VALUES. But the UNIT in the IFC-file is incorrect (it says m3/sec)... So we have 35 L/sec in Revit. But in IFC it is 35 m3/sec.... That is an error by 1000 🚨 

Revit 2023 (latest IFC-exporter):
![image](https://github.com/Autodesk/revit-ifc/assets/81314195/0985aa7b-7b7a-4cd4-8e0b-8d03c5fd00cf)

IFC-file:
![image](https://github.com/Autodesk/revit-ifc/assets/81314195/74b89add-790c-45f2-9357-de7c5c3a13a1)

Uploaded a Revit 2023 and IFC-file here:
[Wrong litre second.zip](https://github.com/Autodesk/revit-ifc/files/13741477/Wrong.litre.second.zip)

**Comment by AngelVelezSosa** [comment]
Let me check on that - I thought that was fixed a while ago.

**Comment by t-vasyi** [comment]
Hi @BIMLUND 
The attached _wrong litre.ifc_ is technically correct.
Revit exported **L/sec** as **dm3/sec**, but the viewer displayed it as **m3/sec**

![image](https://github.com/Autodesk/revit-ifc/assets/115650049/aa3412da-4a2e-4911-880f-7eafdd681da8)

**Comment by AngelVelezSosa** [comment]
OK, so that seems like a viewer issue, then.  We currently promise one of three states:
1. Ideally, correct value with correct units.
2. If not, correct scaled value with standardized units.
3. Last resort, a number if we can't figure it out at all.

The bug is if we have correct value/wrong units, wrong value/correct units or wrong value/wrong units.

**Comment by AngelVelezSosa** [comment]
I think that the viewer is using the data incorrectly.  The .VOLUMEUNIT. doesn't have to have the same base as the .VOLUMETRICFLOWRATEUNIT.  If they are displaying volume by looking at .VOLUMEUNIT. and .TIMEUNIT. they are doing it incorrectly.
