### ISSUE TITLE
Exporter is refusing to export PredefinedType for Revit walls and column

### ISSUE THREAD

**Issue by dr-snglr** [Autodesk/revit-ifc#283]
Hello,

Pretty sure this is some weird bug, or maybe someone has an idea.

- This is version 20.2.1.0, quite a simple thing:

I want export a wall with a IFC PredefinedType using the IfcExportType Attribute:
![image](https://user-images.githubusercontent.com/71882073/110168989-4bae2f00-7df8-11eb-9e02-5f21ea8f4a7d.png)

- No matter what I try, it's refusing to do it.

Why I suspect it's some weird bug: **it works fine for slabs.** But columns and walls, nope.

Simple example model:
[PredefinedType.zip](https://github.com/Autodesk/revit-ifc/files/6093172/PredefinedType.zip)

- It's also not possible to export walls as IfcWalls, it's always a IfcWallStandardCase, even when just one layer. This also looks like a weird bug.

Would appreciate some hints, thanks in advance.

**Comment by dr-snglr** [comment]
So, turns out, it's writing the PredefinedType to the IFC type container, not the instance. I would really need it as an instance property.

**Comment by AngelVelezSosa** [comment]
This is an IFC issue, not a Revit issue.  In IFC4, all instances have PredefinedTypes, but in IFC2x3, they don't.  In particular for your example, IfcWall doesn't and ifcSlab does.
