### ISSUE TITLE
ifc export - multiple building levels at the same elevation - ifc-file has all elements on same level 

### ISSUE THREAD

**Issue by easyetta** [Autodesk/revit-ifc#285]
Hello,
I have multiple building levels at the same elevation(, due to changes that may come I need it as flexible as possible). I have one element on level Ebene_0, some elements in the south are eg. on the level +00_1AL_BH_S1 and some elements in the north are on +00_1AL_BH_N1. When I export the ifcfile all elements are on Ebene_0. I double checked and my elements have the right base level as seen in the pdf.

I can't meet the requirements of our ifc-structure like this and when we import the file to Allplan the elements are located on the wrong drawing file, which causes a lot of problems.

I've tried all different kind of settings in Revit. I've tried the viewers (Desite, Solibri, Navisworks) all show the same phenomenon. Anybody an idea how to solve it? How does Revit choose the export level?
I only can solve it, when I change the elevation of the level to +0,0001 or -0,0001.
I've tried to overwrite the IFCParameter, but it doesn't work for levels at the same elevation.

I am a bit desperate :-/

I export to ifc2x3 (Allplan cant import ifc4)

Appreciate any idea! Thank you very much!

Cheers,
An

**Comment by eibre** [comment]
If  you untick "building storey" in properties, the level will not be exported:
![image](https://user-images.githubusercontent.com/5968613/111776706-9dec5700-88b2-11eb-9f2e-aeafadb36edc.png)

You can also override level by adding i shared parameter `IfcSpatialContainer`

The valid values are:
	• IfcSite - for assigning objects to IfcSite, useful for objects outside the building
	• IfcBuilding – for assigning objects to IfcBuilding
name of the level - for assignment to a specific IfcBuildingStorey (= Level in Revit). Please not that the Level must be checked for export as Building Story

**Comment by easyetta** [comment]
Thank you very much for your answer!

IfcSpatialContainer worked 

Amazing!

**Comment by easyetta** [comment]
Thank you very much for your answer!

Oh I am sorry, I did some more tests and to overwrite with IfcSpatialContainer does not work if you have two or more levels at the same height :-(

**Comment by andydandy74** [comment]
This looks fixed in 23.2.3 :-)

**Comment by AngelVelezSosa** [comment]
Thanks for checking!  I will close.
