### ISSUE TITLE
StructualConnections (Steel) dosent export

### ISSUE THREAD

**Issue by BIMLUND** [Autodesk/revit-ifc#292]
Hi!
Structual Connections dosent export to IFC 2x3.

Revit 2020. 
I have tried uninstall the IFC-exporter and also Installed different versions. No result. 

I have found a workaround that is nuts. But it works so we can continue our production. So any one that is stuck can use this:

![image](https://user-images.githubusercontent.com/81314195/114050237-627af200-988c-11eb-8a5a-b6f2e2d899bb.png)

**Comment by MichaelVictoriano** [comment]
@BIMLUND, did you tried specifying it to be exported first from the IFC options window?
![image](https://user-images.githubusercontent.com/81650759/114056240-5c374680-9889-11eb-9667-3d3d64a95b23.png)

**Comment by BIMLUND** [comment]
Hi @MichaelVictoriano, Holy cow. 
I was 100% sure I had done that but accidentally loaded the wrong mapping files over and over.
Thanks. That solved it. I was sure I've seen them exported before.

Please delete this embarrassing post.

**Comment by AngelVelezSosa** [comment]
Note that we do intend to default to proxy in the future to avoid this sort of simple mistake.
