### ISSUE TITLE
Missing Color in IFC 4 Reference View

### ISSUE THREAD

**Issue by CaptKrunch001** [Autodesk/revit-ifc#294]
Hello together,

I have problems with the colors of walls when exporting an IFC 4 file with the MVD Reference View (Architecture). I use Revit 2021 and the exporter with version 21.2.1.0.

As soon as a door or window is placed in the wall, no color is assigned to the element. Tested with FZK viewer and bimCollab Zoom.

Does anyone have an idea what I am [doing](url) wrong or is there an error in the [exporter?]([url](url))

Attached are a few screenshots , the corresponding (German) Revit file and the IFC,

![Revit](https://user-images.githubusercontent.com/82499876/114672427-6d5ada00-9d05-11eb-81e7-535e04102bdb.jpg)
![Wall with Color](https://user-images.githubusercontent.com/82499876/114672431-6df37080-9d05-11eb-816a-15bb4f01cfaa.jpg)
![Wall without Color](https://user-images.githubusercontent.com/82499876/114672433-6e8c0700-9d05-11eb-8495-23a2c32710ce.jpg)

[IFC4 Export Test.zip](https://github.com/Autodesk/revit-ifc/files/6309042/IFC4.Export.Test.zip)

**Comment by CaptKrunch001** [comment]
Can anyone confirm the problem?

**Comment by AngelVelezSosa** [comment]
@WawanSolihin can you take a look?

**Comment by WawanSolihin** [comment]
It seems that when the geometry (in this case the walls that has window openings) is exported as a tessellation, the color is not obtained correctly. I will register a defect for this issue.

**Comment by CaptKrunch001** [comment]
Thank you :)
