### ISSUE TITLE
export IFC for Revit

### ISSUE THREAD

**Issue by GuillaumeAutret38** [Autodesk/revit-ifc#300]
Hello,
I am writing to you because I can no longer export in ifc format with Revit 2021. I am attaching the error messages to you.
Please let me know in advance if there is a fix to fix the problem.
cordially
Guillaume Autret
guillaume.autret@aktis.archi
![Capture erreur01](https://user-images.githubusercontent.com/67965502/117769562-25f83880-b234-11eb-8cb1-f610dbfb1d30.JPG)
![Capture erreur02](https://user-images.githubusercontent.com/67965502/117769564-2690cf00-b234-11eb-8a4f-804177b8416d.JPG)

**Comment by GuillaumeAutret38** [comment]
it does it to me on all models

**Comment by GuillaumeAutret38** [comment]
I have the same message with a new empty project without template

**Comment by AngelVelezSosa** [comment]
OK, there's something clearly wrong with your Revit or IFC.  I would suggest uninstalling and reinstalling IFC, or contacting your support person.  The fact that nothing exports at all seems like some sort of problem with the installation.

**Comment by GuillaumeAutret38** [comment]
Alright!
