### ISSUE TITLE
PropertySet GUID storage

### ISSUE THREAD

**Issue by TZwielehner** [Autodesk/revit-ifc#302]
Every time a property set is exported it gets the same GlobalID (as intended). Can anyone point me to where this is stored in the database?

**Comment by AngelVelezSosa** [comment]
By "database", do you mean Revit?  Answer - it isn't.  For certain common property sets, we generate a custom GUID in the IFC code.  Although just responding to this message makes me think we could do a bit better :)

**Comment by dedicos** [comment]
So the GUID is generated at every export, and using the values from IFCSubElementEnums.cs the result is always the same? That means the consistency for custom psets is not necessarily guaranteed? Many questions, I know.

**Comment by AngelVelezSosa** [comment]
All correct.  I am currently thinking about other ways to generate a stable GUID using the element GUID + the property set name (which needs to be unique pre element).  Any advice for how to do this easily in C# is appreciated.  That would then potentially replace the IFCSubElementEnums.cs approach, which is limited.

**Comment by dedicos** [comment]
Well, I'm afraid I won't be of great help as I cannot code in C#, I try to use these classes in python. Persisting the GUIDs in some kind of schema would be a workaround for the moment I guess.

**Comment by jmirtsch** [comment]
We've been using this algorithm to generate a deterministic hash globalid from a string, https://github.com/GeometryGym/GeometryGymIFC/blob/9c0694aa3c81649b44475fa8d29b0676dcfa4108/Core/IFC/ParserIFC.cs#L784  
Would be interested in feedback if there is a better way to do it.  How to determine the probability of an id clash is beyond me but I suspect it's pretty low.

Hashing the object definition globalid with the pset name works if the pset is only assigned to a single instance.
But psets can be common to multiple instances/types so how to handle this scenario is more difficult.

**Comment by AngelVelezSosa** [comment]
That is pretty much what I intended to write.
In Revit, a property set is specific to an instance or a type - the individual properties may be shared across property sets, but not the IfcPropertySet itself.  So that should be sufficient to hash the element guid and the property set name as a string.

**Comment by dedicos** [comment]
The psets could be generated per instance first, and then checked for equality in a second step where multiple instances could reference the same one. However, knowing which one stays consistent and its guid might not be easy. Saving file size like that is also not the main pain point, geometry eats properties for breakfast.

**Comment by JOuellette-Autodesk** [comment]
Fixed
