### ISSUE TITLE
IfcGUID and Groups

### ISSUE THREAD

**Issue by PeterTranberg** [Autodesk/revit-ifc#313]
Hi
There are still issues with writing IfcGUID values back to elements in Revit when elements are grouped and copied between exports. I have found 2 issue reports addressing this problem.
https://github.com/Autodesk/revit-ifc/issues/166
https://github.com/Autodesk/revit-ifc/issues/164

What I expect from the option: (Requires the option "Store the  IFC GUID in an element parameter after export")
1. The guid that is assigned to all elements at IFC Export is written back to the Built-in instance parameter IfcGUID in Revit
2. the guid for the Revit type is written to the Built-in Type parameter Type IfcGUID
3. I do not expect to be able to edit the value of IfcGUID in any circumstances, the software HAS to deliver valid data without the user editing any machine generated code.

What happens in Revit 2021
1. At the initial IFC Export of a model with groups, the GUID assignment in the IFC file and the result in the Revit file is correct
2. Copying a group and making a new export result in a warning where the user can choose to Ungroup the copied groups or cancel. The Ungroup option ungroups the copied groups and leaves the IfcGUID empty, the Cancel Command leaves the group grouped and the IfcGUID empty

 What happens in Revit 2022 with the latest release of IFC Exporter 22.1.0 
1.  Att he initial IFC Export of a model with groups, the GUID assignment in the IFC file ais correct but the result in the Revit file is NO IfcGUID Parameter assigned to the Grouped elements 
2.  Copying a group and making a new export result in no errors but still no IfcGUID parameter assigned to grouped elements

@AngelVelezSosa this needs to be more stabil, do you agree with my initial expectation of the option or am I wrong about the option.

**Comment by AngelVelezSosa** [comment]
For 3 above:

I do not expect to be able to edit the value of IfcGUID in any circumstances, the software HAS to deliver valid data without the user editing any machine generated code.

That was the original state.  But customers asked for the ability to make the parameter read-write.  There were a couple of issues for that:
1. Customers wanted the ability to override the value.
2. In cases where the IfcGUID parameter was read-only and empty, there were no solutions for them.  So this gave them flexibility.

We do have an open JIRA item to improve behavior of GUID generation in groups.

**Comment by JOuellette-Autodesk** [comment]
https://jira.autodesk.com/browse/REVIT-160422
https://jira.autodesk.com/browse/REVIT-185360
https://jira.autodesk.com/browse/REVIT-177107

Closed as fixed for Revit 2023
