### ISSUE TITLE
Exporting nested families

### ISSUE THREAD

**Issue by lejla-adsk** [Autodesk/revit-ifc#318]
When exporting nested families, following is possible: 

1. declaring the nested families as shared -> this exports the nested families as separate entities 
2. declaring the nested families as NOT shared -> this exports them as a part of the main entity

Is there anyway to leave the families shared (as this is often needed in Revit schedules) and still export a nested family as one entity only (or at least keep the properties of the enclosing family in some way)?

Thanks, Lejla

**Comment by AngelVelezSosa** [comment]
Hi @lejla-adsk , not currently but that sounds like a possible improvement.
