### ISSUE TITLE
Time in exported IFC files

### ISSUE THREAD

**Issue by SergejMuhic** [Autodesk/revit-ifc#331]
We have an issue with comparing time to system time in Revit generated IFC files. The header features the time but the format is not complete:
`FILE_NAME('2018_01','2021-07-28T09:53:37',...)`
What is missing is the timezone information after seconds. According to https://www.w3.org/TR/NOTE-datetime all components must be present:
```
   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
   Complete date plus hours, minutes, seconds and a decimal fraction of a
second
      YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)
```
Other tools do generate a complete time:
```
FILE_NAME(
/* name */ 'bspline surface',
/* time_stamp */ '2020-03-05T12:31:09+03:00',
```

**Comment by AngelVelezSosa** [comment]
That's a limitation of both the current toolkit we use for IFC file generation, and the toolkit we are switching to.  I'll alert the toolkit creators of that.

**Comment by AngelVelezSosa** [comment]
They have indicated an interest in improving the outcome, but we won't be able to do anything until that happens (with hacking the file afterwards, which seems like the wrong thing to do.)

**Comment by SergejMuhic** [comment]
Thanks for the update. We will circumvent the issue for now.

**Comment by Moult** [comment]
This bug really shouldn't be closed, as the issue is not resolved.
