### ISSUE TITLE
Errors exporting properties using UserDefined Paramater Sets

### ISSUE THREAD

**Issue by tcosse** [Autodesk/revit-ifc#339]
I have tested out exporting four Electrical parameters using the UserDefined Parameter Set mapping file.
These are the four parameters to export : 
![image](https://user-images.githubusercontent.com/52131424/130421214-4900de7c-c380-4e38-afaf-b06c6587cbba.png)
The files used for this test can be found [here ](https://arep-my.sharepoint.com/:f:/g/personal/thomas_cosse_parvis_fr/Esr7hji0DkhApvJdZV3HiDEBRmfvzkv58-Aco8bsVxtKCg?e=jcGlER)

UserDefinedPset Mapping file used : 
![image](https://user-images.githubusercontent.com/52131424/130423091-4db3cff3-de4e-46ef-b421-9c36db7ed93e.png)

The results of the test are presented in this table :
![image](https://user-images.githubusercontent.com/52131424/130425513-0cdb8a4c-a0ab-4c9f-8530-2390a8aa38a0.png)

Conclusions : 
- The Data Types "ElectricalCurrent" and "ElectricalVoltage" do not export correctly
- When using "Integer" or "Real" Data Types instead, the values are not correctly exported most of the time
- When using "Text" Data Type the value is not exported

I am using ifc exporter v20.3.2.0 on Revit 2020

**Comment by AngelVelezSosa** [comment]
Can you check this in Revit 2022?  I believe we added support for these for MEP certification work.

**Comment by tcosse** [comment]
The issue seems to be resolved in Revit 2022, I tested with version v22.2.1.0.
