### ISSUE TITLE
IFCEntity not set as expected in IFC2x3

### ISSUE THREAD

**Issue by HL-code** [Autodesk/revit-ifc#346]
In this example the "IfcExportAs" parameter on a FamilyInstance is set to "IfcOutletType".
Then exported to both IFC2x3 and IFC4.

![IfcEntity issue](https://user-images.githubusercontent.com/68648654/133232804-d74ea2b1-2bc4-4d0b-bf45-46a7476bf02b.png)

IfcEntity is not the specific exported entity when using IFC2x3.
It diverts to a more general IfcFlow entity in the IFC hierachy.

When using IFC4 the IfcEntity is set as expected according to the given parameters for export.
What is the reason for this  ?

Due to this our IFC2x3 files does not validate using the new XML-files from Statsbygg Norway.

**Comment by AngelVelezSosa** [comment]
IfcOutlet is a new entity in IFC4.  In IFC2x3, there were many MEP entity types, but only a few instance types (like IfcFlowTerminal).  IFC4 added a 1-1 mapping between the types (like ifcOutletType) and the instance (in this case, IfcOutlet).  So the above is correct - there is no IfcOutlet entity to use in IFC2x3.

Source:
https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/schema/ifcelectricaldomain/lexical/ifcoutlet.htm
