### ISSUE TITLE
Latest open source version may have issues with Revit 2022.1

### ISSUE THREAD

**Issue by AngelVelezSosa** [Autodesk/revit-ifc#349]
If you get the Revit 2022.1 update, it may have compatibility issues with the open source.  We are looking into this.  Please note, though, that Revit 2022.1 comes with the latest IFC updates, so uninstalling the open source actually has exactly the same results as Revit 2022.1.  We will update this issue when we have more information.

**Comment by A-drt** [comment]
Hi, i tried this morning and i confirm the export is terrible. we need to get an fix as soon as possible.
thanks you to inform us.

**Comment by AngelVelezSosa** [comment]
Yes, we are actively working on this.  But upgrading to Revit 2022.1and uninstalling the open source will have the same result as pre-2022.1.

**Comment by danielaase1337** [comment]
Any update on this issue ? we have multiple customers strugeling to export IFC at the moment

**Comment by AngelVelezSosa** [comment]
Still working on it, but remember that with Revit 2022.1, you can just uninstall the open source - it contains the latest codes.
