### ISSUE TITLE
W-section beam not importing

### ISSUE THREAD

**Issue by theoryshaw** [Autodesk/revit-ifc#350]
Any thoughts on why [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/273b1adf32a781a6b6429d91c2dbbef6cb425c13/Random_Tests/Beam_W_section/from_Blender/Beam_W_section_02.ifc) file, doesn't import into Revit?

**Comment by AngelVelezSosa** [comment]
Import = Open or Link (or both?)

**Comment by theoryshaw** [comment]
Sorry, open.

**Comment by AngelVelezSosa** [comment]
So this file got lost in the backlog, long ago, but it's actually a pretty simple reason why it doesn't open in Revit.  Revit only imports whatever is contained inside the one IFCPROJECT in the file.  This file doesn't have any IFCRELCONTAINEDINSPATIALSTRUCTURE, so the beams are ignored.
