### ISSUE TITLE
Revit does not export sloped floor to IFC

### ISSUE THREAD

**Issue by eestrado** [Autodesk/revit-ifc#366]
I'm trying to export a Revit model to IFC. This model has a floor slab with a slope. However, when exported to IFC the floor slab is flat. The height is just the average of the max and min heights. Is this a bug that can be fixed or perhaps I didn't select the right option?

![image](https://user-images.githubusercontent.com/92844367/138425378-87300ac7-fe18-41ec-bcf4-649450a21c08.png)
Section in Revit showing slope

![image](https://user-images.githubusercontent.com/92844367/138425801-5afdb235-830e-48a3-b6f1-727cbc3252d0.png)
Floor in IFC file

**Comment by JOuellette-Autodesk** [comment]
Fixed for 2023 (23.01.318)
