### ISSUE TITLE
Release 22.3.0.0 for Revit 2022: Beams no exporting in IFC 4

### ISSUE THREAD

**Issue by LuPaMi** [Autodesk/revit-ifc#367]
Hello to all,
Some beams (exported as IfcBeamType.BEAM) are not exporting in Ifc 4. I've tried so far to export in Reference (both strucutral and architectural) and design transfer. Is there some workaround?
They're represented in red and orange in Revit view.
Thanks in advance for any help!

in Revit:

![ModelRVT](https://user-images.githubusercontent.com/92087442/138675933-5b760295-fd33-44b5-9a45-763e2e07fd8c.PNG)

In Ifc Viewer (Bim Vision , Solibri and FKZ ):
![ModelIFC](https://user-images.githubusercontent.com/92087442/138676120-db0dd712-8d40-4407-bb78-3b2f9edfb15b.PNG)

My Export set up:
![IFCSettings](https://user-images.githubusercontent.com/92087442/138676178-bb76c9ef-9d30-4fed-918b-0e15a11c9a2e.png)

**Comment by JOuellette-Autodesk** [comment]
Fixed for IFC for Revit 22.4
