### ISSUE TITLE
IFC Scalability Improvements available in Open Source version? (ODA SDK)

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#387]
Is the improvements mentioned [here ](https://knowledge.autodesk.com/support/revit/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/Revit-WhatsNew/files/GUID-19C4F8E4-7F92-402A-9133-04A252D09020-htm.html) included in the open source version of IFC export? It mentions ODA SDK

**Comment by AngelVelezSosa** [comment]
The latest version of the open source is compatible with Revit 2022.1.X, which use the ODA toolkit.  The ODA toolkit did have some obscure regressions that we will try to incorporate into the open source to work around until newer versions of the toolkit (and Revit) are available.
