### ISSUE TITLE
Error if Export base quantities is checked

### ISSUE THREAD

**Issue by silverglow** [Autodesk/revit-ifc#389]
Whenever I try to export a model with the **Export base quantities** option checked (in Property Sets tab), I get an error and the export stops: model is too big, suggesting to use filters or the export current view only. I tried with a basic model with only one wall, so it's definetely not the case.
Is there any other aspect to set to export base quantities?
I'm using Revit 2022 - Exporter v. 22.3.0.0

**Comment by AngelVelezSosa** [comment]
Please try again with the latest version - v22.4 - and see if that fixes the issue.  There were definitely some API incompatibilities between the old and new toolkits.

**Comment by silverglow** [comment]
ok: v. 22.4 solved the error.
