### ISSUE TITLE
IFC 4.1 4.2 available classes fot the IFC mapping options

### ISSUE THREAD

**Issue by duffra** [Autodesk/revit-ifc#390]
Hi, in the Improvement section I see: "Added additional generic support for IFC4.x files for 2022.1. (Added entities represented in schemas:IFC2x, IFC4x, IFC4x2, IFC4x3)."
Is there any list of the available entities supported during the export? Using some new Entities from the IFC 4.2 Buildingsmart Documentation (for example the infrastructural entities) in the Revit mapping option, it results in having IfcBuildingElementProxy occurences in the IFC. 
It seems to me a default behaviour if a non-considered class is set in the mapping option, but I would like to check what is supported and what is not.
Checked using Revit 2022 - Exporter v. 22.4.0.0

Thanks

**Comment by JOuellette-Autodesk** [comment]
Being IFC4.2 is not officially supported by buildingSMART International (withdrawn - see https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/), the logical support would be IFC2.3.0.1, IFC4.0.2.1, and IFC4.3.x.

And yes, we are aware of the documentation need.

**Comment by JOuellette-Autodesk** [comment]
Future documentation planned to include IFC4.3, alongside the current IFC2x2, 2x3, and 4 versions.
