### ISSUE TITLE
IFC4RV: issues with last commit

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#40]
@WawanSolihin 
Sorry, there seems to be some regression. With the last commit something is not going well with the tessellation of irregular shaped objects, probably something to do with the fix of the large meshes.
Also some stairs and railings and some walls seems to kind of explode now: when I select them, the bounding box is huge. Before, with version of 08-sept-2018, these objects and the tessellation was OK.
(I do notice that a big sitemesh of the sample at https://sourceforge.net/p/ifcexporter/discussion/general/thread/75a87f43/ , which was not exporting before, is now exportable.)

The offset issue of some walls is fixed, but now some plates of a curtain wall are getting an offset.

It will take some time to prepare samples to isolate these issues.

**Comment by dvrvb** [comment]
@WawanSolihin
Actually it's not the last commit, but the one before the current last one: https://github.com/Autodesk/revit-ifc/commit/2641d6be54e448f66ce879c953d5d50fe1aaa42c

Since my last exports of complete models dated from sep-8-2018, I now did a re-export including the commit at sep-21-2018: until that one the export is still OK concerning the above mentioned regression issues.

**Comment by WawanSolihin** [comment]
Thanks for the information Dirk.

I reversed some of the changes that causes the regression in commit# 974b277
Please let us know if there is any other issue.

Thanks,
Wawan

________________________________

**Comment by dvrvb** [comment]
Impressive! Talking about performance improvement: the site (that I borrowed from the model of https://sourceforge.net/p/ifcexporter/discussion/general/thread/75a87f43/
 ) only takes less than a minute to export (with version 29), while before (version 21) it took 55 minutes. 

I attached the sample because it can be handy for testing purposes.
[site.zip](https://github.com/Autodesk/revit-ifc/files/2430685/site.zip)
version 29: current exporter version (including your last commit)
version 21: exporter version till (and including) your commit at 21-sep

I will add the issues that still arise in the next comments.

**Comment by dvrvb** [comment]
issue: wall "explosion", with a part of the wall located elsewhere

[wall.zip](https://github.com/Autodesk/revit-ifc/files/2430914/wall.zip)

version 21: wall (6715) is exporting OK
version 29: part of wall is located far far away 

good news: the strange thing with the tesselation is only a viewer-thingy, caused by that far-far-away-located-part-of-the-wall.
If I export the sample model without this wall: it's looking fine again.


![2018-09-29_wall](https://user-images.githubusercontent.com/41319048/46248954-4aa39700-c421-11e8-957d-3fdcf8df7f2f.png)

**Comment by dvrvb** [comment]
probably same issue as in previous comment: here the plate (27409) is not exploded but located elsewhere.

[plate.zip](https://github.com/Autodesk/revit-ifc/files/2430946/plate.zip)


![2018-09-29_plate](https://user-images.githubusercontent.com/41319048/46249456-d8838000-c429-11e8-8b6e-a33b5c173ea9.png)

**Comment by WawanSolihin** [comment]
Thanks Dirk,
Let me take a look at this. It is quite strange that only part of the geometry is misplaced.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by WawanSolihin** [comment]
Hi Dirk,

I think the commit e803c59 should fix the issue.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: wawan solihin <wsolihin@outlook.com>
Sent: Sunday, September 30, 2018 1:46:33 PM
To: Autodesk/revit-ifc; Autodesk/revit-ifc
Cc: Mention
Subject: RE: [Autodesk/revit-ifc] IFC4RV: issues with last commit (#40)

Thanks Dirk,
Let me take a look at this. It is quite strange that only part of the geometry is misplaced.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dvrvb** [comment]
Hi Wawan,
Thx!
I will re-export (probably this evening) the complete models with this issue, and give you feedback afterwards.
Regards,
Dirk

**Comment by dvrvb** [comment]
Marvellous!
I just exported one small (but complete) model, and the export is now again OK!
I will do the other re-exports later today (and probably this issue can be closed then).

**Comment by dvrvb** [comment]
Hi Wawan,
Indeed, the issues are fixed in the 6 models I re-exported! 
So I'll close this issue.

I'm wondering when your commits will be merged in the master branch.
Hopefully the 4 commits this branch is behind the master are not interfering anything.

If I now only inspect visually a batch of models (mainly architectural models, and just checking if the geometry is exported and positioned at the correct location), the only main issue that is left open, is the one with the windows: https://github.com/Autodesk/revit-ifc/issues/29
It would be nice if that one is also fixed soon.

If this branch is merged with the master branch then there is next to the window issue also the issue with the voids related to doors (that issue of the doors does not exist in the IFC4RV-certification branch): so this could be an issue for merging the branches.

Thx for the nice fix.
Regards,
Dirk

**Comment by WawanSolihin** [comment]
Hi Dirk,

I think the issue with the Windows should have been fixed too. I exported the model and it looks fine in the viewer.
The changes will be first merged to Dev branch, which will be ready to into master when the next release will be prepared.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dvrvb** [comment]
HI Wawan,

I've got the same result as before with BIM Vision.
![2018-10-03_door_window_void](https://user-images.githubusercontent.com/41319048/46393442-9a19e980-c6e5-11e8-9f0a-409bd15d5b5a.png)

But in the FZKViewer it looks OK.
Sorry, it seems to be a BIM Vision issue.
Is there any other Viewer that is reading & displaying IFC4RV properly?

Regards,
Dirk

**Comment by WawanSolihin** [comment]
Let me take a look more closely. It seems that the door geometry is not recognized/missing? But the FZK viewer picks up something.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dvrvb** [comment]
In the FZK Viewer it look OK, but when I look to the amount of Entities in FZK Viewer:
![image](https://user-images.githubusercontent.com/41319048/46394543-bf105b80-c6e9-11e8-9277-f20eb1a67217.png)
I would only expect 1 window, 1 door, 5 openingelements.

**Comment by WawanSolihin** [comment]
Hi Dirk,

I see the problem now. The door in question is made of nested families. And if you go down the families, the basic pieces that make up the door has IfcExportAs value. Some of them (the glass) has IfcExportAs=IfcWindow or IfcPlate, while the frames have IfcExportAs=IfcMember. The result is that the Door does not have the geometry because all the parts are exported as multiple IfcMembers, IfcPlates and IfcWindows, instead of IfcDoor.
This is a strange setting in the data. Data error?

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dvrvb** [comment]
Hi Wawan,
the sample with the shared and nested families, is indeed intended to fall apart in pieces.

But probably it is better to look at the other sample, with the simple door and window.
In IFC2x3CV2 it was going OK, but in IFC4RV it seems that the void is also exported as IfcWindow/IfcDoor, at least if I look at the amounts of entities.

![image](https://user-images.githubusercontent.com/41319048/46396424-af941100-c6ef-11e8-8499-eaec9d83d897.png)

in case of the sample with the shared and nested families: because the "door" is falling apart in pieces, and none of the pieces are IfcDoor, it is correct that there is no door anymore in IFC.


In the regular exporter 19.1 (screenshot at the right) the output in IFC4RV was similar with the current output in IFC2x3CV2. But with the current output in IFC4RV the amounts are different (and there are 3 doors which shouldn't be there, I think)
![image](https://user-images.githubusercontent.com/41319048/46396774-a48db080-c6f0-11e8-8a4b-4ddf0b7c917c.png)

Regards,
Dirk

**Comment by WawanSolihin** [comment]
Hi Dirk,

I am looking at it and the opening are defined as Door category. In this case the opening is exported as a Door, which is correct.
I need to look at the difference between IFC2x3 and IFC4RV export in this case.

[cid:image002.png@01D45B30.C8526D70]

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by WawanSolihin** [comment]
Just to add, in IFC2x3 the Door (Opening) is not exported, while in IFC4 is exported. That is the difference. I need to investigate why the difference.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: wawan solihin <wsolihin@outlook.com>
Sent: Wednesday, October 3, 2018 3:49:24 PM
To: Autodesk/revit-ifc; Autodesk/revit-ifc
Cc: Mention
Subject: RE: [Autodesk/revit-ifc] IFC4RV: issues with last commit (#40)

Hi Dirk,

I am looking at it and the opening are defined as Door category. In this case the opening is exported as a Door, which is correct.
I need to look at the difference between IFC2x3 and IFC4RV export in this case.

[cid:image002.png@01D45B30.C8526D70]

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dvrvb** [comment]
Even if I set in the Export Options mapping table the doors opening and windows opening = IfcOpeningElement, I still get the same result in IFC4RV.

**Comment by WawanSolihin** [comment]
Hi Dirk,

The issue has been fixed now for IFC4RV. However, BIM Vision may show extra footprint geometry for IfcPlates, which is not turned on by default in FZK viewer. I need to clarify in what circumstances and which entity the footprint geometry should be created.

Regards,
Wawan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dvrvb** [comment]
Hi Wawan,

Excellent! Thx a lot for fixing it so quickly.

I indeed do notice the footprints of the plates, which are shown in BIM Vision, but not by default in FZKViewer (unless the option of 'all representations' is chosen).

Spoken of footprints: also the footprints of the slabs of ramps/stairs are shown by default in BIM Vision. In one model the footprints of one particular stairway were all located outside the building. But with the 'runaway' fix, also these footprints fell in place again.
The only runaway objects that I'm aware of are still the ones with the parts, but that's another issue https://github.com/Autodesk/revit-ifc/issues/20

Regards,
Dirk
