### ISSUE TITLE
Revit 2022 and separate IFC addon

### ISSUE THREAD

**Issue by mathib** [Autodesk/revit-ifc#400]
Hi,

I used the [IFC addon for Revit](https://apps.autodesk.com/RVT/EN/LIST/SEARCH?PRODUCTLINE=RVT&QUERY=IFC) in the past for older versions of Revit such as 2016-2017, but I wondered if it is still necessary to install such an addon for the newest Revit 2022.1.1 version?

I noticed that an IFC addon for Revit 2022 is missing from the app store, so I started wondering if it's now included in Revit 2022 OOTB?

**Comment by JOuellette-Autodesk** [comment]
Hi @mathib,
Rather than the Autodesk App Store, the IFC addon can be found here in the GitHub repository... https://github.com/Autodesk/revit-ifc/releases.
