### ISSUE TITLE
Windows parameters exported if wall not joined / not exported if wall is joined

### ISSUE THREAD

**Issue by MisunMartin** [Autodesk/revit-ifc#402]
Hello everybody,

we have found out a strange issue with exporting.
When we do export IFC from Revit there is an IfcWindow element with custom pSet and parameters.

The elements affected are following:
1 - hosting wall
2 - window in host wall
3 - faccade wall (joined or unjoined with the host wall)

The following happens:
**- if only 1 and 2 are exported all parameters in Window Pset_Architektur are exported**
**- if everything is exported, but the walls remain unjoined (so the window opening is missing in facade all parameters in Window Pset_Architektur are exported**
**- if walls are joined (as they should be) and all elements are exported some parameters in Window Pset_Architektur are missing**

First encountered in Revit 2020
We have tried will multiple exporter versions.
Also tried multiple Revit versions.
Tried to replicate with completelly different Window family (same)
Tried to replicate with doors (doors works perfectly fine...)
Exporting using from Revit schedule seems to work..... Not idea why.

Any ideas about what might be the issue or how to solve this strange Wall erasing parameters in "non-related" elements??

Thank you all for your inputs and hopefully some solution :-D

Enclosed 3 IFC exports to see and give it a look.....

[IFC_Examples.zip](https://github.com/Autodesk/revit-ifc/files/7949607/IFC_Examples.zip)

**Comment by rdfeij** [comment]
Hello, I have the same Issue.

Is there a solution for this?

**Comment by rdfeij** [comment]
@AngelVelezSosa ,  can you have a look into this?

**Comment by AngelVelezSosa** [comment]
I believe that is on our list of short-term issues to address; I'll verify.

**Comment by parrela** [comment]
[REVIT-171615] is submitted to Revit 2022. @MisunMartin have you tried it in that version of Revit?

**Comment by rdfeij** [comment]
@parrela Revit 2022 is not an option for me because the model we deliver to our client is Revit 2020. I have te deliver the Native File and the corresponding IFC file. Will this issue be solved for Revit 2020?

**Comment by AngelVelezSosa** [comment]
We are not currently back-submitting fixes to Revit 2020.  But there is a workaround.  You can deliver the Revit 2020 model.  You can also temporarily upgrade the model to Revit 2022 or Revit 2023, and export the IFC file from there, and deliver that.  I would hope that your contract would allow that.
