### ISSUE TITLE
Hexagon becomes a circle on Export 2x3 2020

### ISSUE THREAD

**Issue by gschleusner** [Autodesk/revit-ifc#406]
The gray item is a Revit floor modeled to have straight edges and is exporting as a circle.  The green items are modeled as sweeps as in place.   It appears Revit is trying to "fix" the geometry.   Is there anyway to avoid this happening. 

![image](https://user-images.githubusercontent.com/6507154/151816961-854a4e31-d540-4dae-8ed0-180d0800e549.png)

**Comment by AngelVelezSosa** [comment]
Revit shouldn't even be trying to do that.  Can you get us a Revit file with just the "fixed" geometry?

**Comment by gschleusner** [comment]
@AngelVelezSosa forthcoming...

**Comment by AngelVelezSosa** [comment]
Checked the file offline with @gschleusner , and comparing the contents of the IFC file and another viewer, looks like this is a viewer problem, not a Revit problem.
