### ISSUE TITLE
Export of BaseQuantities

### ISSUE THREAD

**Issue by IO10101** [Autodesk/revit-ifc#407]
BaseQuantities for IfcDistributionElements like Pipes, Ducts and Cabletrays won't be exported in Revit 2021. F.e. I would expect Qto_PipeSegmentBaseQuantities.Length in the IFC File. Export of Quantities only works for IfcBuildingElements like IfcWall.

**Comment by AngelVelezSosa** [comment]
We are working on proper quantity support as part of our IFC4 MEP certification.

**Comment by JOuellette-Autodesk** [comment]
Revit 2023 was certified in April 2022.
