### ISSUE TITLE
Ifc export via api: There has been an unrecoverable error during export

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#410]
We have created an add-in to export ifc. Even if the file is an empty file, some users get this error message when exporting:

There has been an unrecoverable error during export.  This may be because the file is too large to export.  Try using filters and "Current View Only" mode, or look at the documentation for more suggestions.  Export will now be aborted.

Is this a known issue? Revit 2022.

**Comment by AngelVelezSosa** [comment]
The only known issue is the Enscape one where Enscape 3.2 can crash IFC export.  If you have created your own add-in, unfortunately you'd have to debug it to see what the issue is - there are no other generic "IFC just doesn't work" issues other than the Enscape one.

**Comment by eibre** [comment]
THank you for the reply!

We have tracked down the bug: in our code: The "ActivePhaseId" option was set wrong.

This fixed the issue:  `options.AddOption("ActivePhaseId", "0");`
