### ISSUE TITLE
Types not importing in Revit 2020

### ISSUE THREAD

**Issue by theoryshaw** [Autodesk/revit-ifc#415]
[this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/4926e662c0bddd8533b6799a4a51d98be19748de/Random_Tests/Types_Generic/from_Blender/Types_Generic_02.ifc) file doesn't link or open in Revit 2020. 

Any clues why?

IFC.for.Revit.2020.version.20.3.3.0

**Comment by AngelVelezSosa** [comment]
Does it work in newer versions?

**Comment by theoryshaw** [comment]
i think this was a user error, on my part.  Closing, sorry.
