### ISSUE TITLE
Exporting Pipe and Duct insulation IFC4 Revit 2021-2022

### ISSUE THREAD

**Issue by AhmadZnait** [Autodesk/revit-ifc#416]
Both pipe/duct and their insulation get exported as one element (IfcPipeSegment/IfcDuctSegment
<img width="1488" alt="IFC4 Duct" src="https://user-images.githubusercontent.com/99953142/154643151-15256f2c-4c7d-4650-8af8-bd63cdec3b84.png">
)

**Comment by JOuellette-Autodesk** [comment]
@AhmadZnait Could you please tell me which versions of Revit and the IFC Open Source tools you are using?

**Comment by AhmadZnait** [comment]
@JOuellette-Autodesk using both Revit 2021.1.5 and 2022.1.1 and IFC exporters v 21.4.2.0,  and 22.4.0.0

**Comment by JOuellette-Autodesk** [comment]
This will definitely impact certification.
Problem Report filed https://jira.autodesk.com/browse/REVIT-188934

**Comment by JOuellette-Autodesk** [comment]
@AhmadZnait is this true of both IFC4 and 2x3?

**Comment by AhmadZnait** [comment]
@JOuellette-Autodesk with IF2x3 is working normally the problem is with IFC4 Reference View

**Comment by molodca** [comment]
Verified on Revit v. 21.1.70.21 (20220517_1515(x64)) with IFC 2021 v.21.2.1, and Revit 2022.1.3 (22.1.30.34 20220520_1515(x64)) with Revit IFC 22.5.2. OS Windows 10 x 64 (v. 19044.2364). 
The issue was not reproduced. Insulation can be selected, hidden or deleted separately from pipes and ducts.
