### ISSUE TITLE
HTML log file created only for IFC2x3 models?

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#417]
I haven't tested this extensively, but it seems that when linking IFC models, Revit only creates a log file for IFC2x3 models. Would it be possible to enable this for IFC4 models as well?

(Tested in 22.4)

![grafik](https://user-images.githubusercontent.com/3014437/154699924-5e3d8e06-6aeb-4c37-ad5c-2cc0fddde58a.png)

**Comment by AngelVelezSosa** [comment]
That's definitely not generically true.  In fact, there are messages we write out if we process an IFC4.X file to state that we only have a partial implementation. Is there something special in this particular case?

**Comment by andydandy74** [comment]
[GitHub417.zip](https://github.com/Autodesk/revit-ifc/files/8098941/GitHub417.zip)

**Comment by JOuellette-Autodesk** [comment]
Problem Report filed: https://jira.autodesk.com/browse/REVIT-188903

**Comment by andydandy74** [comment]
This looks fixed in 24.2
