### ISSUE TITLE
Why are Slope and Rotation Angle parameters exported unitless?

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#419]
Parameters that use the ```Slope``` or ```Rotation Angle``` parameter type are exported as ```IfcReal``` as opposed to parameters that use the ```Angle``` parameter type (which are exported as ```IfcPlaneAngleMeasure```).

Would it be possible to export these parameter types the same way as ```Angle``` parameters?

![grafik](https://user-images.githubusercontent.com/3014437/154724388-69b9934d-4016-4e32-9936-52ccc24db37a.png)

**Comment by AngelVelezSosa** [comment]
Can you provide a trivial sample file?

**Comment by andydandy74** [comment]
[100_IFC_SlopeAndRotationAngleUnitless.zip](https://github.com/Autodesk/revit-ifc/files/8098887/100_IFC_SlopeAndRotationAngleUnitless.zip)

**Comment by andydandy74** [comment]
Fixed in 23.3.0 - ```RotationAngle``` parameters are now exported as ```IfcPlaneAngleMeasure``` while ```Slope``` parameters are exported as ```IfcPositiveRatioMeasure```. Thanks!
