### ISSUE TITLE
Appending "(Type)" in Pset

### ISSUE THREAD

**Issue by abalazy** [Autodesk/revit-ifc#42]
Feature from previous versions:
Append "(Type)" to all internal Revit type property sets, to avoid having multiple property sets with the same name assigned to the same IFC entity.
is not available in current.
Best would be having an opportunity to merge Type and Instance parameters into one Property Set.

**Comment by AngelVelezSosa** [comment]
A lot of people complained about that, so we minimize its use.  Merging would be the best, but it is a non-trivial amount of code.

**Comment by abalazy** [comment]
We noticed an issue with combining type and instance parameters in common property set in Revit 2019. 
Here is an example showing result of such export in current and older Revit version.
![2018_10_03_16_28_56_autodesk_revit_2019_rac_basic_sample_project rvt_3d_view_3d_](https://user-images.githubusercontent.com/43812564/46417755-9eb4c100-c72a-11e8-96d2-7526691e5b15.png)
![16 19 ifc pset](https://user-images.githubusercontent.com/43812564/46418024-30243300-c72b-11e8-8f76-11d93e6c6c32.png)

**Comment by jmirtsch** [comment]
Where do you want the the properties to be assigned?  I'd suggest not using "I, T" in the parameter mapping file but simply "I"  The IFC export code will seek parameters on the instance and the type, and you should get a a single set (if you don't, can you post a simple model that demonstrates this?)  I've not personally used the "I, T" nomination before.  If you want to two sets, one on instance and one on type, I'd suggest splitting your mapping up and modifying the name of one of them.

**Comment by abalazy** [comment]
"I" assigned in property set file is giving the same result. Actually after several tests any random text in that spot is giving identic Psets.
File I'm using for that test is RAC_basic_sample_project provided as sample file in Revit.
Used pset mapping table:

> PropertySet:	AGP	I	IfcElement
> 	Dlugosc	Length	Length
> 	Powierzchnia	Area	Area
> 	Opis	Text	Description
> 	Type Mark	Text

**Comment by WawanSolihin** [comment]
Feature from previous versions:
Append "(Type)" to all internal Revit type property sets, to avoid having multiple property sets with the same name assigned to the same IFC entity.

==> It somehow uses [Type] instead, i.e. if you append [Type] to the Pset name to be assigned to the Type, it may work. But I am not sure whether it will work in all scenarios.

**Comment by WawanSolihin** [comment]
The current behavior is that the properties from the Type is also exported to the Instance. Like John, I do not agree with this implementation, but it is part of the legacy implementation where many objects do not support IfcTypeObject and therefore the type properties are also exported to the instance. Removing this may cause problems to applications which are already using this. Differentiating properties to be exported as part of Type (using [Type]) suffix will help for now. 
In the near future, we may consider having an advanced option to strictly limit instance parameters exported to the instance, and type parameters to the IfcTypeObject.
I will close this issue "As designed".
