### ISSUE TITLE
Stringers show wrong value in Pset_MemberCommon.Slope

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#421]
When exporting assembled stairs to IFC2x3, the ```Slope``` attribute of ```Pset_MemberCommon``` seems to always export as 90°, regardless of the actual slope of the stringer.

![grafik](https://user-images.githubusercontent.com/3014437/154920819-2835bc1b-cf76-4534-9492-77b34bb53628.png)

**Comment by JOuellette-Autodesk** [comment]
@andydandy74 can you tell me which version of Revit and IFC tools you are using?

**Comment by andydandy74** [comment]
I believe this was tested with v22.4.0. The viewer I used is BIM Collab Zoom 5.2

**Comment by JOuellette-Autodesk** [comment]
Problem report filed: https://jira.autodesk.com/browse/REVIT-188901

**Comment by andydandy74** [comment]
Fixed in 23.3.0 - thanks!
