### ISSUE TITLE
Slab edges do not inherit level of host object

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#422]
When exporting to IFC2x3, it seems like slab edges do not inherit their building storey attribute (as defined in ```IfcRelContainedInSpatialStructure```) from their host's level. Instead, the building storey seems to be determined geometrically which usually ends up being the building storey below the host's level.

![grafik](https://user-images.githubusercontent.com/3014437/154944646-6ec5e39a-f8c0-4d8c-a638-87f07f70d000.png)

![grafik](https://user-images.githubusercontent.com/3014437/154944667-b853fa72-e6a8-41ec-81fd-6530ae091963.png)

**Comment by JOuellette-Autodesk** [comment]
Which version of Revit and the IFC tools are you using?

**Comment by andydandy74** [comment]
I believe this was tested with v22.4.0 in Revit 22.1.2. The viewer I used is BIM Collab Zoom 5.2

**Comment by JOuellette-Autodesk** [comment]
Problem Report filed: https://jira.autodesk.com/browse/REVIT-188900

**Comment by andydandy74** [comment]
This looks fixed in 24.2.0
