### ISSUE TITLE
Revit 2021: IFC Add-in 21.4.0.0 to 21.4.2.0 is buggy and leads to wrong coordinated models

### ISSUE THREAD

**Issue by Thomas84** [Autodesk/revit-ifc#424]
Since exporter version 21.4.0.0 and the actual 21.4.2.0 version as well, the "Link IFC" function leads to wrong placed models (Revit German language settings). The model is placed far away from the internal origin. Both teams have PBP and origin on the same location.
I installed 21.2.1.0 and everything works as expected. 
One week of error searching and the add-in is buggy 

(-__-)

USE 21.2.1.0 if don't want to work additionally at the weekend!

**Comment by JOuellette-Autodesk** [comment]
@Thomas84 Is this IFC4 or IFC2x3 export?

**Comment by emilianocapasso** [comment]
@JOuellette-Autodesk IFC 2x3 from my side, I'll do more tests also in IFC4 and I'll give you feedback

**Comment by Thomas84** [comment]
> @Thomas84 Is this IFC4 or IFC2x3 export?

 IFC2X3

**Comment by JOuellette-Autodesk** [comment]
Problem Report filed: https://jira.autodesk.com/browse/REVIT-188931

**Comment by emilianocapasso** [comment]
@JOuellette-Autodesk I've run additional test with my team (all latest versions downloaded from here):

- Exporter 2019: Export by PBP and Internal Origin leads to wrong import back (both with Open or Link) like @Thomas84 said, the model will be imported far away
- Exporter 2020: Same as 2019
- Exporter 2021: Same as 2020 and 2021
- Exporter 2022: Internal Origin works as expected. Project Base Point same as 2019, 2020 and 2021

On all the exporter the option to export By Shared Coordinates, has the correct behaviour (both import and export)

**Comment by emilianocapasso** [comment]
- Exporter 2021: By Shared Coordinates, not working either

**Comment by PeterTranberg** [comment]
I am having the same Issues here, maybe this is time where the addin should be fixed to support positioning by Shared Coordinates ;-)

**Comment by JOuellette-Autodesk** [comment]
The issue appears to be resolved in 2022.
