### ISSUE TITLE
Revit: objects show in 3d, but not elevation

### ISSUE THREAD

**Issue by theoryshaw** [Autodesk/revit-ifc#429]
Any clues why these anchor bolts show up in 3D in Revit, but not in elevation or section?
files: https://www.dropbox.com/sh/cepsfezmekpbukl/AAA2_vInl1GuC1tqHyah1AgUa?dl=1

![](https://community.osarch.org/uploads/editor/m0/u3hemje2npvy.png "")
![](https://community.osarch.org/uploads/editor/hf/dda2reie9qip.png "")

![](https://community.osarch.org/uploads/editor/3j/x6s2qv14haeh.png "")

**Comment by theoryshaw** [comment]
Tis weird, if you explode it, it shows up...
https://www.dropbox.com/s/tfyf56r8wh75ruv/2022-03-11_16-20-19_Autodesk_Revit_2020.2_-_%5Btest_03.rvt__3D_View_%7B3_Revit.mp4?dl=0

**Comment by JOuellette-Autodesk** [comment]
@theoryshaw How is this related to IFC?

**Comment by theoryshaw** [comment]
This is directly after 'opening' the IFC, linked above, into Revit 2020.

**Comment by JOuellette-Autodesk** [comment]
@theoryshaw What version of Revit 2020 and the IFC open source tool are you using?
This is Open not Link?
Have you tried in Revit 2022.2.1 with the latest open source tool?

**Comment by JOuellette-Autodesk** [comment]
@theoryshaw can you give me info on the versions of Revit and the IFC open source tool you are having the issue?

**Comment by theoryshaw** [comment]
Sure. 
- Revit - 20.2.12.1 20200210_1400(x64)
- Exporter - 20.3.3.0 - Alternate UI 20.3.3.0


I haven't had an opportunity to try 2022 yet.

**Comment by theoryshaw** [comment]
Just tested 2022.  Same error applies. 

[Video](https://www.dropbox.com/s/vpxbzuszu8ji5y5/2022-04-07_17-43-58_Autodesk_Revit_2022_-_%5Btest_03.rvt_-_3D_View_%7B3D%7D_Revit.mp4?dl=0)

[Files](https://www.dropbox.com/sh/os4ldgki2u9a9cg/AADXUGQK4INoL6f3IutVyGc1a?dl=1)

**Comment by theoryshaw** [comment]
Export IFC (v.22.4.2.0)

**Comment by JOuellette-Autodesk** [comment]
https://jira.autodesk.com/browse/REVIT-190532

**Comment by AngelVelezSosa** [comment]
I have reproduced the issue in Revit 2022 and see that it is fixed in Revit 2023.  It is Open IFC, so there's no open source to update.
