### ISSUE TITLE
DEV branch: error build solution

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#43]
Unfortunately, compiling the dll's gets stuck on:

Project: Revit.IFC.common
File: MathUtil.cs

- Type 'MathUtil' already defines a member called 'IsAlmostEqual' with the same parameter types
- The call is ambiguous between the following methods or properties: 'MathUtil.IsAlmostEqual(double, double, double)' and 'MathUtil.IsAlmostEqual(double, double, double)'

Regards,
Dirk

**Comment by jmirtsch** [comment]
I've just removed the duplicate if you pull the latest code for Dev branch.

**Comment by dvrvb** [comment]
Thx! With the current fix I've got it working.
