### ISSUE TITLE
Not possible to export IfcSystem properties using UserDefinedPsets

### ISSUE THREAD

**Issue by tcosse** [Autodesk/revit-ifc#431]
I have attempted to export Properties onto an IfcSystem using UserDefinedPsets. 
The test was unsuccessfull.
Test made in french on the Name of the System and Abbreviation properties.
The test was made on version 20.3.2.0 for Revit 2020.

**Comment by JOuellette-Autodesk** [comment]
@tcosse Have you tried this with Revit 2022.1.2 and the IFC open source tools 22.4.1.0?
