### ISSUE TITLE
Slanted walls are exported wrong in IFC

### ISSUE THREAD

**Issue by COWImgbj** [Autodesk/revit-ifc#433]
Hello,
Slanted walls are exporting wrongly to IFC 2x3 CV 2.0 using Revit 2022.1.2 and IFC exporter 22.4.2.0. This has also been the case in Revit 2021. I have checked the IFC in both Solibri and Navisworks. The results are the same. It has moved 62 mm horizontally. I have 
changed the location line and wall joins, but the results are the same. However, short walls that are slanted seems to be exported correctly. 

Revit
![image](https://user-images.githubusercontent.com/58807838/160273263-6ff38a20-f911-40a5-a64a-285ea245ac98.png)
![image](https://user-images.githubusercontent.com/58807838/160273281-03830de4-9b87-4ddd-a263-c589f79d3197.png)
Short wall (that is correct):
![image](https://user-images.githubusercontent.com/58807838/160273324-94c61e09-cf6b-47c2-9e1b-05c20f3ebda0.png)

Solibri
![image](https://user-images.githubusercontent.com/58807838/160273285-388c769b-3b9c-4c77-8d69-ce0f8b213bad.png)
Short wall (that is correct):
![image](https://user-images.githubusercontent.com/58807838/160273334-9b447084-4bd2-4a9b-a549-eae9fc36ea36.png)

**Comment by parrela** [comment]
Hi @COWImgbj, I do see this effect but it looks like the slanted wall is exported thinner than the original. Can you check in your model? This is what mine looks like, with magenta lines being the edges of the re-linked IFC wall.
![image](https://user-images.githubusercontent.com/38540886/160408091-b8323b4e-cbc4-4ac0-a4ea-0e4a1876c3be.png)

**Comment by parrela** [comment]
REVIT-189785

**Comment by COWImgbj** [comment]
Yes, you are right. It seems the diagonal thickness (actual thickness) in Revit is the horizontal thickness in IFC. It seems to happen for thinner elements and elements with lesser angles as well, but not as noticable.

Revit
![image](https://user-images.githubusercontent.com/58807838/160422885-71de965d-a940-403d-b528-2b1f2fcaf5b1.png)

Solibri
![image](https://user-images.githubusercontent.com/58807838/160422991-3125378b-f358-4794-b94d-bf23fb1d0b6e.png)

**Comment by MagneGanz** [comment]
Same for IFC 4 export from Revit 2022.1.21.13 - Exporter 22.4.0.0.
![image](https://user-images.githubusercontent.com/42205542/161061645-c5835a3f-bec1-4417-bb57-30b57ea9fc2e.png)

**Comment by molodca** [comment]
https://jira.autodesk.com/browse/REVIT-202085

**Comment by AngelVelezSosa** [comment]
This is fixed in 22.6.
