### ISSUE TITLE
IFC2x3CV2.0: error with floors exported as IfcWall

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#44]
Today I exported a batch of models, but this time in IFC2x3CV2.0 (with the current version of the IFC4RV-branch)
Unfortunately with 9 of the 11 models an error window popped up, with errors that could be ignored.
In 2 cases no model at all was generated.
I did a quick test now with the version of the DEV-branch, but unfortunately the same errors are popping up.
It seems mainly related to floors which are exported as IfcWall.
In IFC4RV1.2 they are exported fine (as IfcWall).
In IFC2x3CV2.0 not.
See attached sample. 

[2018-10-05 floors2IfcWall.zip](https://github.com/Autodesk/revit-ifc/files/2452390/2018-10-05.floors2IfcWall.zip)

**Comment by AngelVelezSosa** [comment]
What is the use case of a floor being exported as a wall?  I could imagine some unforseen issues there since they both have compound structures but have different orientations.

**Comment by dvrvb** [comment]
For instance in the case of a plumbingwall, where the vertical board is modelled with a wall, and the horizontal topboard is modelled with a floor: both are part of the plumbingwall.

**Comment by andydandy74** [comment]
Agree. We‘re currently modeling that as floors,  too,  classified as IfcCovering, but I‘d much rather see it exported as IfcWall.

**Comment by dvrvb** [comment]
@WawanSolihin : Fixed! Probably with commit https://github.com/Autodesk/revit-ifc/commit/20b5b90969735f431e1b80a045877bb24475d089
No more error with the IFC2x3CV2.0 export and the floor is exporting fine as IfcWall.
Regards,
Dirk
