### ISSUE TITLE
New codification for special character and accent?

### ISSUE THREAD

**Issue by SDA00** [Autodesk/revit-ifc#441]
Hello,

On Revit 2022 (without patching) and its basic installed IFC converter, Revit encodes in the ifc the accents and special characters using the unicode.

Example: SEQ+SOL_SIT+Chauss\X2\00E9\X0 for an accent "é" in French

While installing the latest stable version of the IFC exporter on revit 2022 (Release 22.4.1.0), I noticed that the coding has changed.

It is now in the form : Sol:SEQ+SOL_SIT+Chauss\X\E9 for an accent "é "

I also tried on Revit 2023 and the codification is also of form : Sol:SEQ+SOL_SIT+Chauss\X\E9

Has there been a change in coding in the latest updates of the IFC exporter?

Thanking you in advance,
Sofiene

**Comment by AngelVelezSosa** [comment]
What changed is the toolkit.  The ODA toolkit uses the more compact representation.  The open source itself hasn't changed.

**Comment by SDA00** [comment]
Thank you AngelVelezSosa

From which version of the IFC exporter did this change occur?

**Comment by AngelVelezSosa** [comment]
That's the thing - none, really.  It happened with Revit 2022.1 (and Revit 2023.0).

**Comment by SDA00** [comment]
Does this mean that depending on the version of revit, the management of special characters will be different? Is it planned that from version 2022.1 onwards this codification management will not change or will it return with a uniform codification?

If I understand correctly, the problem comes from the revit engine but not from the ifc exporter?

**Comment by AngelVelezSosa** [comment]
Revit uses a 3rd party IFC toolkit to read and write IFC files.  Before Revit 2022.1, we used the Jotne EDM IFC toolkit.  Since Revit 2022.1, we use the ODA IFC toolkit.  We don't change toolkits lightly - we switched to the EDM toolkit in (calendar year) 2011 from EuroSTEP IFC toolkit before that.

So while we don't expect this to change, it is based on both the ODA toolkit and our continued use of it.  Is this a concern to you?

**Comment by SDA00** [comment]
Thanks, it was to understand if the change was due to a bug or a voluntary action (update..)

REVIT use https://www.opendesign.com/products/ifc-sdk to manage the export and import of IFC in revit.

The ODA IFC SDK roadmap indicates the beta of "Federated IFC models" in June 2022. This means that Revit could, if developed by ODA, manage the creation of a single IFC from several linked models?



De : AngelVelezSosa ***@***.***>
Envoyé : jeudi 21 avril 2022 19:07
À : Autodesk/revit-ifc ***@***.***>
Cc : DAHAK Sofiene ***@***.***>; Author ***@***.***>
Objet : Re: [Autodesk/revit-ifc] New codification for special character and accent? (Issue #441)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<http://aka.ms/LearnAboutSenderIdentification>

Revit uses a 3rd party IFC toolkit to read and write IFC files. Before Revit 2022.1, we used the Jotne EDM IFC toolkit. Since Revit 2022.1, we use the ODA IFC toolkit. We don't change toolkits lightly - we switched to the EDM toolkit in (calendar year) 2011 from EuroSTEP IFC toolkit before that.

So while we don't expect this to change, it is based on both the ODA toolkit and our continued use of it. Is this a concern to you?

-

**Comment by AngelVelezSosa** [comment]
That's already on our public roadmap: https://trello.com/b/ldRXK9Gw/revit-public-roadmap.  We have a plan to do that without needing extra ODA support.  To be clear, ODA has tools that _also_ work with IFC files in Revit; we only use the read/write aspect of the toolkit at the moment (as you can see by looking at the source code here).
