### ISSUE TITLE
Multiple errors while exporting IFC in 2022

### ISSUE THREAD

**Issue by WillemdBr** [Autodesk/revit-ifc#451]
Hi,

When exporting this Revit file (attached in the next comment) we get this error:
![image](https://user-images.githubusercontent.com/32219489/169227296-98221958-9600-471c-b308-6fa6a4a081fc.png)
The only way is to cancel the export, so no IFC export can be created.

We've searched and tried differend IFC Export settings and finally we've come to the conclusion that the Classification Setting gives this error.  We always fill it in this way:
![image](https://user-images.githubusercontent.com/32219489/169227641-a6035438-5c49-4e44-8cba-405e4fe74a9a.png)
_Mind the standard value for 'Edition date'. This used to be the date of today (not a reason for the export to fail, just a request to change it back if possible)_

When we don't fill in the values for 'Name' and 'Classification field name', the export works without warnings.
Can you reproduce this error and fix it in the next update?

**Comment by WillemdBr** [comment]
I can't seem to attach the .zip file with the revit file, I get the error: 'is not included in the list' ??

**Comment by WillemdBr** [comment]
so here is a WEtransfer: https://we.tl/t-NB6z3owJ29

**Comment by parrela** [comment]
I can reproduce it, will check it out in dev as well and file an item.

**Comment by WillemdBr** [comment]
@parrela / @WawanSolihin  What is the status of this issue? Issue is still present in the nieuwest Revit / IFC exporter versions. With this issue we can't have our classifications in IFC, which is essential for reading and checking IFC models

**Comment by parrela** [comment]
I found that this doesn't happen in the latest versions - coming out shortly. I can't say when.

**Comment by WawanSolihin** [comment]
I think it might be fixed in 22.5.1 and 23.1.1. I will check it later today.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JOuellette-Autodesk** [comment]
REVIT-192026
Fixed in 2023.1
