### ISSUE TITLE
Splitted elements get inconsistent IfcGuid

### ISSUE THREAD

**Issue by MagneGanz** [Autodesk/revit-ifc#467]
If you export to IFC with the option "Store the IfcGUID in an element parameter after export" and then split the wall,
the two Wall elements will have the same value for the parameter IfcGuid. When you export to Ifc the second time, the smallest (or newest?) wall element will in the IFC file get a new IfcGuid, BUT this new IfcGuid will not be written back to Revit. What happens next, is that this wall element will get a new and DIFFERENT IfcGUID every time you export.

So in the case of a splitted element, the exporter handles the situation correct up to the point where it in fact does not write the new IfcGUID back to Revit.

Here is a model where I did just that. 
1. Exported to IFC. IfcGUID is written back
2. Splitted the wall and copied a column. New wall element (new IfcGuid in the Ifc-file, but not updated in Revit). New Column (New IfcGUID in IFC file and updated in Revit, OK). 
3. Exported again, new wall element a different IfcGuid

This happens because the Exporter discovers that there are two identical values for the parameter IfcGUID in Revit, then the newest element gets a new IfcGUID.

It is important that this is fixed! And the fix should be easy. Always write IfcGUID back to the element.

![image](https://user-images.githubusercontent.com/42205542/173590231-4a662518-7e71-443b-a356-3bced94f8980.png)

![image](https://user-images.githubusercontent.com/42205542/173590501-c185c732-b66c-441e-9fee-fcac5ed6f416.png)
[IFC-test IfcGuids.zip](https://github.com/Autodesk/revit-ifc/files/8900329/IFC-test.IfcGuids.zip)

**Comment by AngelVelezSosa** [comment]
v22.5 is still in progress on the GUID work, but we will in any case make sure that split elements work as expected.

**Comment by parrela** [comment]
This can be closed, fixed
[REVIT-193975]
(Revit 2022) Split elements get new GUID each time exported
