### ISSUE TITLE
Parts of walls are missing when exported using 22.5

### ISSUE THREAD

**Issue by COWImgbj** [Autodesk/revit-ifc#477]
This seems to be a bug in 22.5. Some walls have parts missing when exported. From what I can see, it seems to only happen when walls are cut and attached to other elements.

Example 1

Revit
![image](https://user-images.githubusercontent.com/58807838/176707919-8c5db2c2-9b5c-4b0a-b874-576105dda844.png)

IFC
![image](https://user-images.githubusercontent.com/58807838/176706941-2f0452bf-0035-4e98-a6d6-ab7c913f55d8.png)

Example 2

Revit
![image](https://user-images.githubusercontent.com/58807838/176707956-33eccaa7-4b4c-4391-8b0d-a0c12b0f28dc.png)

IFC
![image](https://user-images.githubusercontent.com/58807838/176707619-758e1410-ef4e-4d2f-86ed-aac546618209.png)

**Comment by StCwi** [comment]
also have the same problem with 22.5.1.0

**Comment by AngelVelezSosa** [comment]
We are actively working on an issue relating to this and are trying to make sure we don't fix two problems and regress on a third, so would appreciate a sample file with your particular flavor of issue to make sure our fix actually addresses your issue.  We are also working on putting more regression tests in place for edge cases of wall cuts, so that would help us also.

**Comment by Jelatho** [comment]
I seem to have a model from one of our clients that has the same issue. Is there a workaround for this issue?

**Comment by geraka** [comment]
> also have the same problem with 22.5.1.0, but it seems ok if i change from IFC2x3 coordination view to IFC4

I had a similar issue with walls and floors with edited profiles. Openings were missing when exported with UFC2x3. With IFC4 it is OK.

**Comment by COWImgbj** [comment]
@AngelVelezSosa It seems like this has been fixed in 22.6?

**Comment by parrela** [comment]
[REVIT-194207]
Parts of walls missing on export from 22.5
