### ISSUE TITLE
Different IFC export behavior for slab/floor from Revit 2018 and Revit 2019

### ISSUE THREAD

**Issue by COWItvo** [Autodesk/revit-ifc#48]
Revit 2018 exported f.ex. floor/slab that was "divided" in the "edit boundary" as separate IFC elements. 
Revit 2019 export them as one IFC element. 

Is this intended or a bug?

I think most user would like to keep it the way it was in Revit 2018 or a possibility to override it. 
Please see attachments. 

Dividing them in separate revit instances, means more editing time for the user in case of changes. 
This is similar to the issue that`s reported with use of parts. The objective is to make modeling procedures most efficient as possible. 

![image](https://user-images.githubusercontent.com/44081396/46854043-08565e80-ce00-11e8-8bcb-c02cd3217e69.png)

![image](https://user-images.githubusercontent.com/44081396/46854145-3f2c7480-ce00-11e8-9714-0bea98ed33ae.png)

![image](https://user-images.githubusercontent.com/44081396/46854157-4489bf00-ce00-11e8-9544-d93d08b8adf5.png)

**Comment by dvrvb** [comment]
I can confirm that behaviour as I metioned it in june https://sourceforge.net/p/ifcexporter/discussion/general/thread/ba81d793/#0e9b
I can imagine why the old behaviour is preferred, but on the other hand the new behaviour is closer to "what you've modelled, is what you'll get in IFC".
I would prefer it as an export option "separate floor boundaries": in that case you'll have the choice.
Regards,
Dirk

**Comment by JOuellette-Autodesk** [comment]
Multilayer slab export is based on MVD specifications. Revit has been certified for IFC2x3 CV2.0 and IFC4 RV1.2. Differences in versions are based on updates/changes due to certification testing and results.
