### ISSUE TITLE
Custom Pset not exported

### ISSUE THREAD

**Issue by pedersenjpp** [Autodesk/revit-ifc#484]
Custom Pset not exporting.

![image](https://user-images.githubusercontent.com/66945389/178715626-357551a6-3d5e-49fe-9d63-d24a3aced531.png)

DiKon_Classification is not created, All other custom Psets are created just fine.
Simply cannot find whats different from these entries.

**Comment by AngelVelezSosa** [comment]
Can you try removing the comment from the middle of the definition to see if that helps?  Actually, is there a type there where you missed a "PropertySet:"?  I see Level and TypeName are defined twice.

**Comment by pedersenjpp** [comment]
Started a file from the bottom with no comments and had the same issue.

Found out that Visual Studio Code as a default has indent detection on, and replaces tab with 4 spaces, Thus breaking the changes I made to the file.

Thanks for your help anyways.
