### ISSUE TITLE
Non-applicable quantities still export despite ifcExportAs

### ISSUE THREAD

**Issue by Moult** [Autodesk/revit-ifc#497]
I've overridden a wall to be an IfcFurniture, but it still exports with Qto_WallBaseQuantities

**Comment by AngelVelezSosa** [comment]
Thanks - we will root out the places where the quantities aren't paying attention to how things were actually exported.

**Comment by parrela** [comment]
This doesn't happen for me - I get only the expected stuff. Could you send me a trivial model with your settings? I will check it out.

**Comment by Moult** [comment]
Sample file in #493

**Comment by parrela** [comment]
This is fixed previously - using your file I see the difference between your IFC file and my new one.

**Comment by parrela** [comment]
[Project1_dev.zip](https://github.com/Autodesk/revit-ifc/files/9530063/Project1_dev.zip)

**Comment by Moult** [comment]
@parrela can you confirm which version this is fixed on? I have consultants working on Revit 2021 with the latest Github release for 2021 facing this issue.

**Comment by parrela** [comment]
@Moult I find it is fixed in 2023 but not 2022.

**Comment by Moult** [comment]
OK :) Unfortunately I do not have 2023 to test but let's close this assuming it's fixed!
