### ISSUE TITLE
Moving Wiki

### ISSUE THREAD

**Issue by tsolsen** [Autodesk/revit-ifc#50]
Is there any plans to move the wiki over from source forge or start from scratch?
I can't help much with code, but here I and other might be able to lend a hand with documentation.

The same goes for the various files for download - pset files, shared parameters and so on. They might need a separate repo?

**Comment by AngelVelezSosa** [comment]
We should look into the Wiki.  As far as the other files, we could add them to a Misc folder I guess.

**Comment by tsolsen** [comment]
> Possible to do markdown vs. a wiki?

Please elaborate. Should be no problem to use markdown, when writing the wiki?

**Comment by tsolsen** [comment]
> We should look into the Wiki. As far as the other files, we could add them to a Misc folder I guess.

Reach out if I can help.

**Comment by theoryshaw** [comment]
Just suggest using markdown, because it's platform agnostic. 

and can be version tracked with git.

**Comment by tsolsen** [comment]
I get that, Ryan. But are you are asking for markdown markup or markdown files?

Wiki's are actually a repo in themselves, [and thus have tracking built in](https://help.github.com/articles/viewing-a-wiki-s-history-of-changes/). When a wiki is cloned and edited locally, I think this can actually be done on .md files.

To me a wiki as a structure is superior to individual files for this type of documentation purposes - but again I'd invite you to elaborate on workflow, if you think individual files are better suited. They might be!

**Comment by theoryshaw** [comment]
Hi Troels, yes markdown files.

version tracking with git is a little more agnostic, in that you could relocate to another platform (githlab for example) in the future, and still save your version history.

**Comment by JOuellette-Autodesk** [comment]
For clarity, we'll leave the SourceForge wiki, as is. If anyone feels something is worth copying over, submit a new issue and specify exactly what old Wiki entries need to be copied and updated.
