### ISSUE TITLE
No material layers exported to IFC 2x3 (Rvt22 22.5.2.0)

### ISSUE THREAD

**Issue by louistrue** [Autodesk/revit-ifc#506]
We are not able to export individual material layers of multilayer walls/floors to IFC 2x3: 

![image001 (1).png](https://user-images.githubusercontent.com/78563314/188257024-2275544a-22f2-4783-8a31-a9714434e268.png)

It works as expected for IFC4:

![image002 (1).png](https://user-images.githubusercontent.com/78563314/188257043-3c507056-e1e3-45e1-bae2-94b6651b7780.png)

Is this a bug or has it never been implemented?

**Comment by AngelVelezSosa** [comment]
Sorry for the delay on this.  Can you provide more detail perhaps with a trivial sample file?  I'm not sure exactly what result you are looking for.

**Comment by louistrue** [comment]
IFC 4 with individual layers:
![image](https://user-images.githubusercontent.com/78563314/189208292-5dc6fd66-4a6f-49a8-973e-86fe04d78c46.png)

2x3 without layers:
![image](https://user-images.githubusercontent.com/78563314/189208451-3f8b49fe-fad9-4c0a-8253-5479ab52e326.png)

![image](https://user-images.githubusercontent.com/78563314/189208477-4d3a267f-3fb5-499b-8c5c-32326b337d04.png)


[IFC.zip](https://github.com/Autodesk/revit-ifc/files/9530048/IFC.zip)

**Comment by Teun1** [comment]
Perhaps the folowing link will give you some information that you are looking for.
https://github.com/Autodesk/revit-ifc/issues/120#issuecomment-707727484
The main difference at the moment, is that the IFC4 is supported by more and certified software. 
(in reaction to what I said in that 2 year old post) 
https://technical.buildingsmart.org/services/certification/ifc-certification-participants/

**Comment by louistrue** [comment]
Thanks @Teun1 , but I'm not talking about parts. These are multilayer objects with standard export settings for IFC 2x3 and 4. 

Layers get exported only with IFC 4

I think it used to work for 2x3 as well some time ago but I'm not sure...

**Comment by Teun1** [comment]
As far as my knowledge / memory goes it has been this way.
As you can see multilayer did at least not show up in 2019 (when exporting with IFC2x3)
Using parts was only a workaround to get somewere (and resulted in a different question ;-) ).

**Comment by WawanSolihin** [comment]
This is an expected behavior. In IFC2x3, the wall layers are represented in the IfcMaterialLayer, which may be shown in the property of the Wall in some viewers, whereas the geometry is the overall wall.
Only in IFC4 RV 1.2 MVD, the wall layers (slab too) will be split into its component (using geometry items in the Architecture exchange, or as IfcBuildingElementPart in the Structural exchange).

**Comment by louistrue** [comment]
Thanks for clarifying @WawanSolihin 👍 
One more reason to ditch 3x3, i guess...
Whats the reason structure gets buildingelementparts? Precast concrete?

**Comment by WawanSolihin** [comment]
The main reason if I am not wrong is that the structural applications handles the layers as individual elements, therefore they are exported as individual IfcBuildingElementPart and aggregated into IfcWall
