### ISSUE TITLE
Type IfcGUID of IFC Element Type changes

### ISSUE THREAD

**Issue by manelmarib** [Autodesk/revit-ifc#512]
Exporting from Revit 22.1.30.34, and IFC Exporter v 22.4.2.0

While inspecting the IFC, we found that the first IFC Element Type of each IFC Element maintains the Type IfcGUID stored in the built-in parameter. For example, lets take the **2MA3PEWKzCK8No7IHIMBLz** and look for it in the IFC:

![image](https://user-images.githubusercontent.com/112946224/189691554-3c270425-8969-4559-91ce-9391a526f8d8.png)

If you put attention to this line, we can also observe the ID from Revit: **4272340**

So if we keep looking for the same Type IfcGUID, we cannot find more lines with it. On the other side, if we look for the ID we can find all the IFC Element Type associated to this Type:
![image](https://user-images.githubusercontent.com/112946224/189692480-f8f4a50a-265b-46df-a1ac-35d93cab932d.png)

**Shouldn't it be the same GUID for each type, as ID do?**

**Comment by AngelVelezSosa** [comment]
The code did the right thing in not duplicating the type GUID.  The code did not do the right thing in duplicating the slab type, if it is indeed identical.  In the latest versions, we have addressed both those issues: (1) we have consistent GUIDs for all guids in the file and (2) we do a better job of not duplicating types.  If you see the same issue in the latest version, please let me know.

**Comment by manelmarib** [comment]
Will try with the latest IFC Exporter version, and we will let you know.
Thanks for your reply @AngelVelezSosa

**Comment by manelmarib** [comment]
RVT 22.1.30.34 - Exporter 22.5.2.0 @AngelVelezSosa 
We just did an export and still having duplicated types, with same ID but different GUID.
![image](https://user-images.githubusercontent.com/112946224/189868155-6d084aeb-7e8c-4ce1-bcb3-089a9a6977a9.png)
![image](https://user-images.githubusercontent.com/112946224/189868297-3ae08f02-018f-4500-bdd9-e49ea85bf469.png)

**Comment by manelmarib** [comment]
any update on this? @AngelVelezSosa

**Comment by manelmarib** [comment]
any news on this? @AngelVelezSosa

**Comment by YukiScharf** [comment]
Hi @AngelVelezSosa 
I came across the same issue and made sure R2023.1 worked fine.  For previous version of Revit, what can we do?

**Comment by AngelVelezSosa** [comment]
Hi @YukiScharf , to understand, are you saying that with the latest version of the open source you were able to get a case where a GUID changed between exports?  Or are you saying that you ran across the issue in a previous version of Revit?

**Comment by YukiScharf** [comment]
Yes, I could export the same GUID for properties in R2023.1 but I need the same behavior for R2021-2022 as well. 
Is there a way to update the exportor for previous versions?
