### ISSUE TITLE
Levels are not exported to IfcBuildingStorey in Revit 2023

### ISSUE THREAD

**Issue by AndreasFleischmann2111** [Autodesk/revit-ifc#518]
I created a new blank RVT and added 10 Levels. All Levels are marked as BuidlingLevel.
For one Level I added a Floor object

When I export the IFC 4, only the Level with Floor is exported. The others are not exported.

How can I export all 10 Levels, even I have no geometry attached to it?

PS: I forgot to mention that the IFCExportOption is set to "ByType". If I select "Yes", all floors are exported to IfcBuildingStorey. Unfortunately I have no permission to make this change to the RVT from my addin.

**Comment by AngelVelezSosa** [comment]
We don't export empty levels to any IFC schema.  Are you testing, or is there a use case for exporting empty levels?

**Comment by AndreasFleischmann2111** [comment]
Thank you for the quick answer.

In early LOD 100 phases of buidling studies, architects are designing just levels and volumes for each floor level to calculate room volumes etc.
Ifc export is required to drive our elevator engines to build elevator LOD 100 models. Architects need the elevator room spaces for these calculations.

Honestly i am not sure whether architects have always assigned at least one element to the floor levels. Moreover, the ifc that we need for the elevator automatism only need the ifcbuildingstorey elements. Plan is to filter out anything else except the floor levels.

I feel that your specification to omit empty levels does not make sense at all cases. If the revit user defines a level, marks it as buidling level, it should be exported. This is the mentioned specification.

What do you think?

Sent by Outlook<https://aka.ms/qtex0l> für iOS, respect typos.
________________________________
Von: AngelVelezSosa ***@***.***>
Gesendet: Thursday, October 6, 2022 6:29:35 PM
An: Autodesk/revit-ifc ***@***.***>
Cc: Andreas Fleischmann ***@***.***>; Author ***@***.***>
Betreff: Re: [Autodesk/revit-ifc] Levels are not exported to IfcBuildingStorey in Revit 2023 (Issue #518)


We don't export empty levels to any IFC schema. Are you testing, or is there a use case for exporting empty levels?

**Comment by AngelVelezSosa** [comment]
I don't think it would be a big deal to export levels marked as building storeys even if they are empty.  I'd be curious to know what others think.

**Comment by Teun1** [comment]
We sometimes make an IFC and/or Revit file with only Levels, Grids and an 0-point object. Just for coordination purposes.

**Comment by jmirtsch** [comment]
I would vote for all building stories to be included in the IFC, culling the stories without elements/spaces doesn't really make sense to me.

**Comment by andydandy74** [comment]
We regularly have the same use case as @Teun1 - current workaround is to place a random object on each level. Would be nice if this export limitation for levels could be lifted.

**Comment by AndreasFleischmann2111** [comment]
> We sometimes make an IFC and/or Revit file with only Levels, Grids and an 0-point object. Just for coordination purposes.

@Teun1 : More or less, your use caes is the same, that I tried to explain (in my long explanation). For coordination purposes we need to know all building levels.

**Comment by AndreasFleischmann2111** [comment]
What would be the process to make this change happen?
Who is reponsible for the acceptance?

The change itself is easy, see my image below. 

![image](https://user-images.githubusercontent.com/58511570/194505312-613b0ed6-a9c8-4bb3-ab0d-4209e046a42c.png)

Thank you for taking care, Andreas

**Comment by AngelVelezSosa** [comment]
Hi @AndreasFleischmann2111 , I have been convinced and will make the appropriate changes accordingly.  It's safer for my team to do it internally to have all of the proper testing done on the change (which is more or less what is suggested above).

**Comment by JOuellette-Autodesk** [comment]
Fixed in IFC Extension 23.2.3.0
