### ISSUE TITLE
IfcGUID for Rooms changes every time if "Store the IFC GUID in an element parameter after export" is checked

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#521]
In Revit 2022: IfcGUID for Rooms changes every time the same file is exported if "Store the IFC GUID in an element parameter after export" is checked in Advanced Export settings. We tried to upgrade to the newest exporter here: https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v22.5.2.0

![image](https://user-images.githubusercontent.com/5968613/194864229-b739641f-5bee-4370-ad3e-3a883e300c5f.png)

Same file exported two times with the same settings:
First file:
![image](https://user-images.githubusercontent.com/5968613/194864401-ba4fbfc7-50cf-4714-a537-8ec51b055e1a.png)
Second file:
![image](https://user-images.githubusercontent.com/5968613/194864448-976ff4bf-1b37-4d7f-9075-0f8daaf6b0d4.png)

**Comment by JOuellette-Autodesk** [comment]
@eibre Can you send me the file or post it here?

**Comment by AngelVelezSosa** [comment]
Did you try with 22.6?  But yes, we think we've solved this problem in general, so would like to see the file to verify.

**Comment by homerlpbsight** [comment]
I'm using Revit 2023 with V23.2.5.0 and the issue occurs with other elements aswell; 
<img width="506" alt="2023-04-07 09_19_52-BIM2 - Verbinding met extern bureaublad" src="https://user-images.githubusercontent.com/119950976/230562157-64c2b68e-b310-4de4-9c97-9e8053b573c2.png">

**Comment by xpt5** [comment]
I can confirm that both 22.6.0 and 22.6.2 keep the GUID.
