### ISSUE TITLE
Exporting other Parameters than just the default parameter

### ISSUE THREAD

**Issue by AndreasFleischmann2111** [Autodesk/revit-ifc#528]
I am having the family below. When I export the IFC, I am not able to export the VDI parameter shown in the right side sample ( export from Archicad).

Question:
How can I archieve that?
![image](https://user-images.githubusercontent.com/58511570/195655151-fe68ed02-7a6f-4f62-98f3-c58719ae0c63.png)

Question 2:
How can I define the "Name" property?

![image](https://user-images.githubusercontent.com/58511570/195655445-6ab7a5c8-d3c4-493b-8926-e16fbfd520a0.png)

Thank you for your help.

**Comment by AndreasFleischmann2111** [comment]
Q1 is solved. Explanation is here:
https://bimcorner.com/exporting-ifc-from-revit-part-3-user-defined-properties/

Can you still help on Q2?

**Comment by louistrue** [comment]
@AndreasFleischmann2111 
Add a Revit Parameter called IfcName: https://youtu.be/1DVluDqkjPA

**Comment by AndreasFleischmann2111** [comment]
Q2 is also solved. Thank you @louistrue 

![image](https://user-images.githubusercontent.com/58511570/195665527-36dfdb94-8bca-4329-88c9-c0ecb418b9c5.png)
