### ISSUE TITLE
Revit 2022 IFC 2x3 dont give the proper geometry compared to Revit, IFC4 (works)

### ISSUE THREAD

**Issue by croesFV** [Autodesk/revit-ifc#539]
We have a Mass that we join with a Wall to create a wall opening. As long as the different Masses component are different in heightit works, but as soon as the top of the Masses are equal. Then it removes to much of the wall. Is this a known case?

![IFC](https://user-images.githubusercontent.com/46350131/199243477-4adf80ee-9098-40cc-9ec7-fccc818854d3.png)
![Revit](https://user-images.githubusercontent.com/46350131/199243480-dfc03c41-8654-4fc3-ad61-025e800a4a0c.png)

**Comment by croesFV** [comment]
We done a test in Revit 2023 with exporter version v.23.1.1.0 there is works perfect.

**Comment by AngelVelezSosa** [comment]
I'll mark it as closed, then.

**Comment by croesFV** [comment]
Its not closed, we still have many projects in Revit 2022 (BIM-protocol) long term projects.
It was more a suggestion, that it works in Revit 2023, but not in Revit 2022, maybe you could look into the code and spot a difference in exporting.
