### ISSUE TITLE
IFC4RV: runaway footprints of stairway

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#54]
Probably it is better to post it as separate issue (referring to my last comment in the closed issue https://github.com/Autodesk/revit-ifc/issues/40 ):
Despite the fix of runaway objects, the footprints of the attached stairway are still dislocated.

[2018-10-24 runaway footprint.zip](https://github.com/Autodesk/revit-ifc/files/2509422/2018-10-24.runaway.footprint.zip)

Regards,
Dirk

**Comment by hlg** [comment]
It seems like the only the landing part is offset. It is in a separate footprint representation and contains approximately absolute coordinates which then add to the relative position of the stair product.

**Comment by WawanSolihin** [comment]
A fix has been committed in the IFCRV4-Certification branch at this time. It will be merged into the master eventually probably for the next release

**Comment by dvrvb** [comment]
Superb!
I also tested it on the original complete model (architectural model), and everything is staying in place.
Thx,
Regards,
Dirk
PS: the previous commit concerning Entity/TypeClasses I'll test as soon I've revamped my testfile.
