### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by HL-code** [Autodesk/revit-ifc#548]
(Could be this already exists)

I keep coming back to this question.
As a developer it would be great to have one API method that generates a given IFC property for a selection of elements.
As we get deeper into "cross-standard" detection of classifications it is of interrest to know what IFC properties will be exported.
For example :
A Door with a FireRating might have a specific classification in a national standard.
I could export an IFC file of that door to see if it gets a value on PsetDoorCommon.FireRating.
If i had a "generate propertyset" function  i could check the IFC properties of the door without exporting a file.

So a method sort of like this..... CreatePropertySet(Element element, string nameOfPropertyset)

Does such a method exists somewhere in the API ?

**Comment by AngelVelezSosa** [comment]
There's no direct Revit API function call for that.  That said, the exporter code does that.  So you can look at the export code and copy what it does.

**Comment by HL-code** [comment]
Thanks for reply Angel.

I think this is something we would hesitate to do for the same reason we handed some code to you a few years back.
Every time the opensource code change we would be one step behind having to merge your changes into our code.
(Which is whenever a bugfix is done or new property sets / IFC versions like 4.3 are introduced)

We could do the change and hand it back to you as we have done.
But i will never get an approval to do that right now.

So i think we will just wait and hope that the API calls for geometry and properties become more distinct over time.
It seems like a logical refactoring.
Once you get into UI's for property sets later you could debug just those and not geometry.

Cheers!

**Comment by AngelVelezSosa** [comment]
OK.  I mean, that's an interesting API and we will keep it in mind. But given that the property sets are all created in C# code, it would still have to be a public API in the C# code not internal to Revit - unless I guess it just popped out to the open source.
