### ISSUE TITLE
Nested family export behavior

### ISSUE THREAD

**Issue by aroestia** [Autodesk/revit-ifc#557]
I have an issue with shared/not-shared nested family when exporting to IFC.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/119540852/205513298-54fc8300-c4e0-4de8-a153-edcfb1ac46ec.png">

see the example below.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/119540852/205513257-22913d17-b1bb-4e4d-b075-e5cd0b48f760.png">

in this file, I created 3 different families. 
1. shared - a family with 2 nested shared family
2. partly shared - a family with 1 nested shared family and one not shared
3. non-shared - 2 non-shared nested family

when a family has been created with a shared families element, the nested families export as an individual element, and I can't find the relation to the main family.

![image](https://user-images.githubusercontent.com/119540852/205513316-f64cd9a0-c9c0-4942-91be-5c72981d00a2.png)

since I strive to not make any changes in the origin RVT file, I wonder if there is anything I can define on the export setting or anything I can do with the output IFC file in order to find the relation between those elements and merge them together. 

[nested.zip](https://github.com/Autodesk/revit-ifc/files/10149385/nested.zip)

Attach Rvt 2022 file.

**Comment by AngelVelezSosa** [comment]
Sadly, this is an issue (not a bug really) since the beginning of IFC export in Revit.  It has never been entirely clear if there is a right solution or if this needs UI for possible solutions.

**Comment by JOuellette-Autodesk** [comment]
@aroestia I'm not sure what you mean by "proper". 

In the schemas for IFC2x3 and IFC4 (and the upcoming IFC4.3), IfcDoor only captures/refers to the geometry and data of the Door Leaf and Door Frame. For some reason known only to buildingSMART, Door Hardware is not part of the Door "definition", nor is there a schema specification for linking the Door Hardware to the Door. I will file an Issue with the buildingSMART GitHub repository.

**Comment by JOuellette-Autodesk** [comment]
@aroestia , the other option you have is to create a custom property set and properties (custom shared parameters) that specifies the door hardware.
