### ISSUE TITLE
my IFC walls are just generic models in Revit after import.

### ISSUE THREAD

**Issue by Aidenjh1** [Autodesk/revit-ifc#571]
Is there a way to get Revit to recognize walls when importing an IFC format model? Right now they are all just treated as generic models.

**Comment by JOuellette-Autodesk** [comment]
@Aidenjh1 Can you tell us what version of Revit and the IFC toolbox you are using?

Also, are you using Link or Open?

Is it possible to provide us with the IFC file?

**Comment by JOuellette-Autodesk** [comment]
@Aidenjh1 any further input? If not, this issue will be closed with a "working as designed" note

**Comment by AngelVelezSosa** [comment]
IFCWALL should always come in as something categorized as a wall.  But it could be a native Revit wall or an in-place family, and the in-place family could contain extrusions and voids or an ImportInstance, depending on the IFC file.

**Comment by Aidenjh1** [comment]
I just did a quick test - I made a simple wall in Revit LT 2023, exported it as an IFC file, in several different versions including  2x3 GSA Concept Design BIM 2010, 2x3 Basic FM Handover View, 2x2 Coordination View, 2x3 COBie 2.4 Design Deliverable View, and IFC4 Reference View [Architecture]. I imported each one into Sketchup 2021. The IFC4 Reference View [Architecture] failed to import into Sketchup Pro 2021. The other versions imported just fine, but they came in as "Type undefined." There is no information that Sketchup Pro 2021 can recognize other than raw geometry.

**Comment by AngelVelezSosa** [comment]
This is almost certainly not a Revit issue.  Here are some things to check:
1. Open the IFC file in a text viewer.  Look for "IFCWALL".  Is it there?  Then Revit it exporting walls as walls.  Do you see "IFCBUILDINGELEMENTPROXY" instead?  Then check your export mapping table and see if walls are set to that, or something else.
2. Download another viewer, like the FZK viewer (https://www.iai.kit.edu/english/1648.php).  Open the IFC there.  Is it categorized as a wall?  If you look at the wall, can you see properties?  If you can't, check your export settings - have you set it to not export any properties?
If you have tried the above, and you still see generic objects everywhere, we can reopen and investigate.
