### ISSUE TITLE
Pset_ConcreteElementGeneral properties not exported

### ISSUE THREAD

**Issue by MichalBkn** [Autodesk/revit-ifc#572]
Pset_ConcreteElementGeneral and its properties are not exported for IfcWall. Properties (ConcreteCover) have been added using latest IFC shared parameters file. For export was used revit 2021, both IFC4 RV and IFC4 DTV, exporter v. 21.4.3.0.

**Comment by JOuellette-Autodesk** [comment]
Do you have a file we can apply tests to?

**Comment by MichalBkn** [comment]
Both source file and ifc file at this link:

[https://www.dropbox.com/sh/9mi6jqu89eiddds/AABqfYNy5tk9cfRoLbcnrth3a?dl=0](url)

**Comment by JOuellette-Autodesk** [comment]
@MichalBkn Thank you.

**Comment by JOuellette-Autodesk** [comment]
https://jira.autodesk.com/browse/REVIT-201467

**Comment by JOuellette-Autodesk** [comment]
This was determined to be working as designed, as the Pset_ConcreteElementGeneral was considered out of scope. Will file a new PR/enhancement request.
