### ISSUE TITLE
IFC4RV: MEP export time & runaway pipefitting isolation

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#58]
R2019
exporter: R19.1 & R19-current-DEV-branch-version

issues: 
1. IFC4RV export is 10 times slower than IFC2x3CV2.0 export 
2. IFC2x3CV2.0 & IFC4RV: there are some 'runaway' pipefitting isolation objects 

Since the model and exports are too big for uploading at GitHub:
Sample model is downloadable at German Revit User Group https://www.rug-dach.de/download/demodatensaetze.html
Direct link: https://www.rug-dach.de/phocadownload/2018_final/Samples.zip 

Within the Samples.zip, it is the model: BIM Projekt Golden Nugget - Gebaeudetechnik (1).rvt
Todo:
- upgrade to R2019
- ignore the missing linked model
- create 3D view
- export to (standard setup options)
	IFC 2x3 Coordination View 2.0
	IFC 4 Reference View

1. **export time**

_R19.1 & R19-current-DEV-branch-version_
IFC2x3CV2.0: exported in less than 1,5 minute
IFC4RV: 11 minutes

2. **runaway pipefitting isolation issue**

_R19.1_
IFC2x3CV2.0: a part of the isolation of a pipefitting is not correctly positioned (is rotated)
IFC4RV: same part is now running more away

_R19-current-DEV-branch-version_
IFC2x3CV2.0: a part of the isolation of a pipefitting is not correctly positioned (is rotated)
IFC4RV: same as IFC2x3: a part of the isolation of a pipefitting is not correctly positioned (is rotated)

Just one pipefitting isolation is marked on the screenshot, but there are several in the model with the same issue.
(In R2018 with exporter 18.4 there are even 10 pipefittings that are not exported at all, and are missing in the export)

<img width="862" alt="image" src="https://user-images.githubusercontent.com/41319048/47433977-d3ec8600-d7a1-11e8-8039-120ad0d882d1.png">

Regards,
Dirk

Note: in another MEP model I was not able to export the mechanical system in IFC4RV.
I don't know if this is a related issue with the export time.
Although with IFC2x3 it only took 9 minutes to generate the IFC-model, with IFC4RV there was overnight still no result (something exponential going on?)
The electrical and the plumbing part was not causing any problem.

**Comment by dvrvb** [comment]
Hi Wawan,
Thx for all the effort. I'll will test it on the other MEP model that I mentioned, but that I couldn't send. Feedback will follow.
Regards,
Dirk
PS: I'm still busy with the Entity/TypeClass/PredefinedType test

**Comment by dvrvb** [comment]
Hi Wawan,

I exported the other MEP-model (the model where I couldn't get it exported in IFC4RV within a reasonable time), now with the option "Keep tessellated geometry as triangulation" ticked on.

**IFC4RV** (with "Keep tessellated ..."):

- with current commit it takes 25 minutes, but some ducts are now displaced (runaway 'Flex Duct Round', as IfcDuctSegment): its just some of the flex round ducts, not all of them.

- until previous commit it takes 2 hours and 40 minutes (also with the same runaway flexible round ducts)

-> So, indeed there is for sure improvement in export time.


I also exported it in IFC2x3CV2.0 in order to see if there is also the issue of the runaway ducts.
**IFC2x3CV2.0** (with "Keep tessellated ..."): 

- with current commit it takes 8 minutes, and everything is in place

- until previous commit it takes 8 minutes, and everything is in place

Did I understand well that for IFC2x3CV2.0 the option "Keep tessellated ..." is obsolete? (It doesn't make any difference if it is selected or not, because this option is not applicable for IFC2x3CV2.0 ?)

So, the current commit did improve the export time.
The issue of the runaway of the flexible round ducts seems NOT to be related to the current commit (as regression or something like that).

I tried to isolate the issue, and it seems to be related to ... the option "Keep tessellated geometry as triangulation":
- without the option selected: everything is in place: OK!
- with the option selected: the flex round duct is dislocated: issue.

I attached a sample of the issue (rvt + 2 IFC's: one with and one without the option KTGAT selected)
[2018-11-18 IFC4RV runaway flex round ducts.zip](https://github.com/Autodesk/revit-ifc/files/2592393/2018-11-18.IFC4RV.runaway.flex.round.ducts.zip)

Regards,
Dirk

<img width="866" alt="image" src="https://user-images.githubusercontent.com/41319048/48666991-9c38db80-eacc-11e8-9165-8504355b5d3a.png">

**Comment by WawanSolihin** [comment]
Thanks Dirk,
I will take a look at the runaway issue.

Regards,
Wawan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dvrvb** [comment]
I also noticed the state of the option KTGAT (Keep Tessellated ...) is not saved (which is a pitty if one doesn't notice it, since it makes a world of difference in exporttime): this issue is already posted by andydandy74 https://github.com/Autodesk/revit-ifc/issues/6

**Comment by WawanSolihin** [comment]
I will take a look at this also.
I have other optimization in mind for stiching the triangles, but it may take some time to put it in place.

Regards,
Wawan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dvrvb** [comment]
OK!
So, the 3 main options in the exporterUI which have effect on the geometry, are:
1. **Level of detail for some element geometry**: default = Low:
I have to recheck it, but if I put it on 'high' then there were runaway voids in roofs.
For which elements in particular is this option intended?
2. **Use active view when creating geometry**
As far as I noticed it is mainly intended to get the cable trays exported with the real 'ladder' detail (as viewed with Detail Level = Fine)
Is it good practice to have this option always selected? 
3. **Keep Tessellate Geometry as Triangulation**

**Comment by WawanSolihin** [comment]
Hi Dirk,

Sorry I think I missed this question:
“Did I understand well that for IFC2x3CV2.0 the option "Keep tessellated ..." is obsolete? (It doesn't make any difference if it is selected or not, because this option is not applicable for IFC2x3CV2.0 ?)”
The option for tessellated geometry is only applicable to IFC4RV since the tessellated geometry is only introduced in IFC4.

Regards,
Wawan

**Comment by dvrvb** [comment]
I close this issue, since the pipefitting wasn't an issue after all, and the IFC4RV export time improved by using the option "Keep tessellated geometry as triangulation".
The issue about saving the option is already mentioned in another issue: https://github.com/Autodesk/revit-ifc/issues/6

**Comment by dvrvb** [comment]
Oops, I have to reopen it. The other issue (in the middle of this thread) with the runaway flex round duct still exists.
[2018-11-18 IFC4RV runaway flex round ducts.zip](https://github.com/Autodesk/revit-ifc/files/2948861/2018-11-18.IFC4RV.runaway.flex.round.ducts.zip)

IFC4RV1.2
- without the option "Keep tessellated geometry as triangulation": OK
- with the option "Keep tessellated geometry as triangulation": the flex duct is on the run

<img width="933" alt="image" src="https://user-images.githubusercontent.com/41319048/54077666-fa780d00-42bb-11e9-89d9-2e689790b963.png">

**Comment by dvrvb** [comment]
@WawanSolihin : I can happily confirm that the flex duct remains in place with or without the option KTGAT :-)  Thanks,
Regards,
Dirk
