### ISSUE TITLE
The IFC export process encountered an error

### ISSUE THREAD

**Issue by StCwi** [Autodesk/revit-ifc#583]
Hi
Revit : 2022.1
revit-ifc : 2022.6.0.0

I get an error and the IFC export fails whit the errormessage in the attached screenshot

![IFC export error](https://user-images.githubusercontent.com/111058760/215706309-dee4f18f-f752-45c2-91f0-b3830aac5172.png)

**Comment by AngelVelezSosa** [comment]
Is this generic or for one file?

**Comment by StCwi** [comment]
It does that even when i start a new Revit file, so its generic.
I have to downgrade to IFC.for.Revit.2022.5.1.0 for it to work.

**Comment by Hauk-Lykke** [comment]
I also get this error. I am trying to export a view which only contains floors, with several custom property sets. I am using shared coordinates.

Revit 2022.1
IFC exporter 22.6.0.0

![bilde](https://user-images.githubusercontent.com/25793697/216574973-f3490265-c702-46d2-bf21-24af8b822816.png)

**Comment by JOuellette-Autodesk** [comment]
may be linked to [#](https://github.com/Autodesk/revit-ifc/issues/585)
A Jira PR has been filed.

**Comment by o-babii** [comment]
There is a System.MissingMethod exception there, which is a clear sign of a compatibility issue with some specific Revit version. 
Could you please, specify which version of Revit 2022.1.x is being used? It will be really helpful.
Thanks.

**Comment by Hauk-Lykke** [comment]
![bilde](https://user-images.githubusercontent.com/25793697/219338348-1df55bd4-79af-46af-99c1-d971ce4ec4cc.png)

**Comment by JOuellette-Autodesk** [comment]
@StCwi, we are unable to reproduce the original error on our end. It doesn't appear to be a general Revit or IFC for Revit Addon issue, but something specific to your installation. Please contact Customer Support for further support.
