### ISSUE TITLE
Cannot see my doors and windows in IFC file script

### ISSUE THREAD

**Issue by talha-siddiqui-7** [Autodesk/revit-ifc#593]
Hi i am currently working with IFC file trying to extract information about windows and doors using python. I am unable to use IFCWINDOW as there is no IFCWINDOW in the IFC file.
This is strange as in revit, under the families, i can clearly see windows as well as doors along with their specifications. 
One thing is i cannot see the doors and windows in the 3d model and plan view but they are still there in the families.
Can someone please give a solution for this. I am uploading the file here
I am using Revit 2023. I do not know which version of revit was used to create the IFC file
[IFC BIM File.zip](https://github.com/Autodesk/revit-ifc/files/10717616/IFC.BIM.File.zip)

**Comment by AngelVelezSosa** [comment]
What do you mean by "they are still there in the families"?  If the doors and windows aren't in the 3d model or plan view, doesn't that just mean that they aren't placed?  We don't export unplaced families.

**Comment by talha-siddiqui-7** [comment]
> 

I mean in project browser, when i click on families, both windows and doors are present. But visually i cannot see them in the 3d model. Have you had a look at the model i shared?

**Comment by AngelVelezSosa** [comment]
You shared an IFC file that has no windows in it but I don't know what your Revit project looks like.  But the project browser shows you loaded families in the project which include families that aren't place in the project at all.  Do the following: new project.  Create a wall.  Place a window in it.  Export.  Does the IFC file have an IFCWINDOW in it?  Probably.  If not, we check your export mapping settings.

**Comment by talha-siddiqui-7** [comment]
Hey. I did what you suggested. Made a wall and put a window in it, exported to IFC. I can find IFCWINDOW in this new file. So i guess there is an issue in the IFC file i have for the project? Because i do not have the revit file nor do i know which version of revit the file was made. I just have the IFC
