### ISSUE TITLE
duplicated SlabTypes

### ISSUE THREAD

**Issue by SHKnudsen** [Autodesk/revit-ifc#596]
I have created a small test file containing 5 levels, each level has 5 revit Floors using the same types on each level.

![image](https://user-images.githubusercontent.com/13732445/219705151-af19b5b3-4cba-4856-938e-a5a5874b2f16.png)
![image](https://user-images.githubusercontent.com/13732445/219705272-59fe0a48-6847-4cee-8309-64e20ffe7c35.png)
![image](https://user-images.githubusercontent.com/13732445/219705382-8fc5c0dd-4294-4351-b306-1e341748b47d.png)

I expected one `IfcSlabType` to be created for each Revit Floor type in the sample file that would mean a total of 4 `IfcSlabType`s, but instead i get a new type for each floor instance which means 25 `IfcSlab`s and 25 `IfcSlabType`s. Is there a setting i have missed somewhere, or is this expected?

**Comment by AngelVelezSosa** [comment]
What version of Revit is this?  Can you share that simple sample file?

**Comment by SHKnudsen** [comment]
Revit 22.0.2.392

How do i best share the file with you?

**Comment by AngelVelezSosa** [comment]
You can send to angel.velez@autodesk.com

**Comment by SHKnudsen** [comment]
Just noticed that there was an update to the Revit IFC exporter (v22.6.0.0), after this update everything works as expected
