### ISSUE TITLE
Revit uses non-standard context identifier of "Facetation" instead of body.

### ISSUE THREAD

**Issue by Moult** [Autodesk/revit-ifc#598]
I've come across this quite a few times where "Facetation" is used.

I haven't seen it, but the source suggests the non-standard "Mesh" is also used.

This breaks context filters which users can use to show the "Body" vs other geometry context identifiers. Unless we specifically have a workaround for this, these objects actually become invisible since we filter by Bodies. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/import_ifc.py#L288-L289

**Comment by AngelVelezSosa** [comment]
Looking at the code, these strings are only used if we are exporting SurfaceModels.
"Mesh" is only used when exporting to the IFC 2x3 GSA 2010 COBie specification.
"Facetation" is used if we are exporting to prior to IFC4 otherwise.
Otherwise "Body" is used.  

I'm trying to see where the documentation is for this.  If I can't find it I'll change it.

**Comment by AngelVelezSosa** [comment]
OK, looks like for BuildingElements it should be "Body", but for IfcSite it should be "Facetation".  I'll do that check.

**Comment by AngelVelezSosa** [comment]
Hmm... the code seems to be set up that way.  It should only use "Facetation" for IfcSite.  Let me know if you find examples otherwise.

**Comment by Moult** [comment]
I just grepped the zip for IFC2X3 and IFC4 and cannot find a mention of "facetation" to be used in this manner. Is there an instruction in the spec that I've missed?

**Comment by AngelVelezSosa** [comment]
https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/

Facetation Representation

The facetation representation of IfcSite is defined using a surface model, based on the IfcFaceBasedSurfaceModel or on the IfcShellBasedSurfaceModel. Normally the surface model is the result after triangulation of the site survey points.

The representation identifier and type of this representation of IfcSite is:

IfcShapeRepresentation.RepresentationIdentifier = 'Facetation'
IfcShapeRepresentation.RepresentationType = 'SurfaceModel'

**Comment by Moult** [comment]
Ah thanks I grepped the wrong directory :)

So in that case, shouldn't the site also have a body geometry in addition to the facetation geometry?

**Comment by AngelVelezSosa** [comment]
Revit sites were traditionally only surface models.  I believe our roadmap is for solid, not surfaces, but I don't know what the current status of that is.  In IFC4, we don't put geometry on the site at all and  so this is an increasingly moot point.  I guess I don't know if the interpretation is supposed to be "body + others" or "choose the best choice".

**Comment by Moult** [comment]
Sounds fair. Thanks for the explanation!
