### ISSUE TITLE
UseOnlyTriangulation export setting can be exported to JSON but is not saved in project

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#6]
The export setting ```UseOnlyTriangulation``` a.k.a. "Keep Tesselated Geometry as Triangulation" ("Advanced" tab) can be exported to JSON but not saved in project.

Tested in 18.4

Steps to reproduce:
- In the export settings dialog, check the abovementioned checkbox
- Save the export setup to disk
- Leave dialog with OK
- Click on "Modify setup"
- Notice that the checkbox is now **un**checked again
- Load the previously saved setup from disk
- Notice that the checkbox is now checked again
- Leave dialog with OK
- Click on "Modify setup"
- Notice that the checkbox is now **un**checked again

**Comment by AngelVelezSosa** [comment]
That option isn't even supposed to be there anymore; it was just for IFC4ADD1 compatibility, but that's not associated with any MVD.  Will check why it is there at all.

**Comment by WawanSolihin** [comment]
"Keep Tesselated Geometry as Triangulation" ("Advanced" tab) is introduced for IFC4RV for the following reasons:
1. The default: export will try to optimize any triangulated geometry into polygonal faces if there are co-plannar. If this is not required, the option may be ticked for faster export
2. In some cases, IFC4RV certification auto-check has problem with the Euler check unless it is in the original triangulated form

Need to take a look about the persistence of the option. It should be just minor bug.

**Comment by WawanSolihin** [comment]
This issue on persisting "Keep Tesselated Geometry as Triangulation" ("Advanced" tab) option has been fixed in the latest release: 21.2.0.0, 20.3.1.0, and 19.5.0.0 (coming soon)
