### ISSUE TITLE
Help needed for calculating energy consumption of the building

### ISSUE THREAD

**Issue by talha-siddiqui-7** [Autodesk/revit-ifc#600]
Hi guys, i need a bit of help in calculating the energy consumption of a building. I have revit 2023 and for some reason whenever i try to run energy analytical model, it crashes
So all i need is someone who can run the energy analytical model simulation for me and tell me what is the energy consumption of the building.
Some energy settings to change before the simulation:
1) Change the mode to 'Use building elements'
2) In advanced options, change the building type to single family house
3) Building operating schedule to 24/7

Screen shots from the insight page will be appreciated

[Updated IFC file.zip](https://github.com/Autodesk/revit-ifc/files/10802582/Updated.IFC.file.zip)

**Comment by AngelVelezSosa** [comment]
How is this related to IFC?

**Comment by JOuellette-Autodesk** [comment]
I had trouble viewing this. I suspect it is because it is a "DesignTransferView" export 
ViewDefinition [DesignTransferView_V1.0] (per IFC Header)

23.0.11.19 - Exporter 23.1.1.0 - Alternate UI 23.1.1.0 (per IFC header)

**Comment by JOuellette-Autodesk** [comment]
@talha-siddiqui-7 With what application are you trying to run the energy simulation?

**Comment by JOuellette-Autodesk** [comment]
This is not an IFC problem report. It is better to take this up on the other support forums.
