### ISSUE TITLE
 Prevent Revit from resetting a room to the base point, upon IFC import?

### ISSUE THREAD

**Issue by theoryshaw** [Autodesk/revit-ifc#61]
Is there a way to prevent Revit from resetting a room to the base point, upon IFC import?

Files: https://github.com/OpeningDesign/FreeMVD_WorkFlow/tree/5eb690fa18ef1c9674df34a6e53dde0a2eefea49/Specifications%20test%20files/Rooms/from%20Revit

![rooms_01](https://user-images.githubusercontent.com/507113/47586390-af211b80-d925-11e8-8805-c5797981c28c.png)
![rooms_03](https://user-images.githubusercontent.com/507113/47586398-b3e5cf80-d925-11e8-853b-92ef7d937e08.png)

**Comment by PeterTranberg** [comment]
Hi Ryan

As I recall, you need to have a Room Tag loaded into the IFC Import template. Setup the path to the template in IFC Import Settings.

Peter

**Comment by theoryshaw** [comment]
Yep, that was it!  Thanks.
