### ISSUE TITLE
Implementing SitePlacement - method set_SitePlacement not found

### ISSUE THREAD

**Issue by rayray4105** [Autodesk/revit-ifc#611]
Hi,

I am trying to implement the option 'Coordinate Base' in our export tool but I am running into a problem. After adding 'SitePlacement' to the exporter config I get the following error on execution. Am I missing a reference?

'Method not found: 'Void BIM.IFC.Export.UI.IFCExportConfiguration.set_SitePlacement(Revit.IFC.Common.Enums.SiteTransformBasis)'.'

regards,
Raymond

**Comment by rayray4105** [comment]
For Revit 2022 I dont get this error. It only seems to apply to Revit 2021.

**Comment by AngelVelezSosa** [comment]
We aren't actively making changes to Revit 2021, so I will close this.

**Comment by rayray4105** [comment]
well I also have this problem in Revit 2022 unfortunately.

**Comment by rayray4105** [comment]
hi, what is the status of this issue? We are now using Revit 2024 and this issue still persists.
