### ISSUE TITLE
Revit Mapping of IfcDesription

### ISSUE THREAD

**Issue by AlexSchleicher** [Autodesk/revit-ifc#612]
Hello together,

is there a way to map the IfcDesription attribute with a Revit parameter? Since IfcDescription is not mapped to a pset, I don't know how to do it in the parameter mapping table. Or is there a standard Revit parameter that is automatically mapped with IfcDescription? I use Revit in German language.

Many greetings, Alex Schleicher

**Comment by AngelVelezSosa** [comment]
You can add a shared parameter IfcDescription that you can use to populate it.  The shared parameters file here, or the Parameters Service, has the parameter specified.
