### ISSUE TITLE
Revit 2023(.1) no longer recognizes IfcExportAs and IfcExportType

### ISSUE THREAD

**Issue by martinhspence** [Autodesk/revit-ifc#614]
Hi all,

Issue originally posted here: https://sourceforge.net/p/ifcexporter/discussion/general/thread/198edda1ec/

We've recently started projects in Revit 2023.1, and during a QA session yesterday using IFC's in Solibri, I found out that none of the objects registers the values we assign in the traditional "IfcExportAs"- and "IfcExportType"-parameters.

I know that Autodesk probably wanted to ease the use of costumization/overriding of the IFC Type and Predefined Type properties, but by introducing the built in "Export Type to IFC As"- and "Type IFC Predefined Type"-parameters, the exporter now ignores values stored in the "old" parameters.

We have several clients that have quite strict IFC-specifications, which is why we run the setting og these parameters with semi-automated workflows. With the introduction of Autodesks new export parameters, we have to manually go through our models, and set the parameters for pretty much all object types.

I've attached three screenshots of an Ifc export of a dishwasher from the RAC_sample project, to show what I'm on about.

IfcTest_1: Vanilla export with no parameters set:
-Exports as IfcElementProxyType and NOTDEFINED

IfcTest_2: Export where "IfcExportAs" = IfcElectricApplianceType, and "IfcExportType" = DISHWASHER
-Same result as above

IfcTest_3: Export where I through the UI set the new built in parameters with same values as above.
-Only when setting the above values through the UI I get the expected result.

Perhaps we could get it as an option for the exporter to use IfcExportAs and IfcExportType as an alternative to the defualt built in parameters?
![IfcTest_3](https://user-images.githubusercontent.com/15342446/226283873-6e15e8e2-8220-4498-8e11-01d57ad681b5.png)
![IfcTest_2](https://user-images.githubusercontent.com/15342446/226283875-43246865-d3eb-426d-a3d8-74bf024809aa.png)
![IfcTest_1](https://user-images.githubusercontent.com/15342446/226283876-26e30838-b6e0-41b0-8d42-0f231cc6e383.png)

**Comment by AngelVelezSosa** [comment]
Thanks for bringing this issue to Github.

As I mentioned in the original thread, the intention here was for performance reasons - if we added a new parameter but still checked the old one, now we are slowing down export for legacy support.  We did do an upgrade for pre-Revit 2023 files so that their values populated the new parameters - did that not work for you?

We could have an Advanced option that continued to check the old parameters.

Pro: would support old workflows.
Cons: extra branching code that would need to be supported for a long time, performance hit but only really for those who checked it, yet one more option to choose.

Thoughts?

**Comment by martinhspence** [comment]
Hi Angel,

Thanks again for your response.

I was not aware of the automated population of parameters. The project I did the QA session on, was actually upgraded from R22 to R23 just before new years, but it seems the population of parameters didn't come along (if this is what you mean?)

I can't imagine we are the only ones who do semi- or maybe fully automated setting of these parameters. The new IFC parameters doesn't exist in the family environment, which means, that even if you wanted to preset the values in your company family database, you'd have to go through them manually on each project. (Please correct me if I'm wrong here). 

So having an option to check the old parameters, would be an excellent solution, in my opinion :-).

Best regards, Martin

**Comment by andydandy74** [comment]
Haven't tried, but should work (the same way it does for the assembly code parameter).

One nice aspect that I miss about the old shared parameters, though: We used to be able to set them to read-only for loadable families by controlling them with a formula to prevent folks from tampering with the predefined values in our library families. Doesn't work with the parameter type of the new OOTB parameters. But that's a Revit issue, not an exporter issue, unfortunately.

**Comment by martinhspence** [comment]
> Is it not possible to set the new export as parameter without using the GUI? We should to be able to automate this in combination with other classification tasks.

I just tested this, and you are absolutely right. Even though the parameters have the GUI, we can still set them as generel text type parameters. I was not aware of this, as we never use the Assembly Code parameter. 

Sorry for stirring something small out of proportion.

But @andydandy74's point about making the paramters read-only on in-house loadable families is a good argument as well.

**Comment by AngelVelezSosa** [comment]
Yes, they are still text parameters, so you can choose to put in anything you want, we just provide the GUI to make things easier.  And yes, for the read-only issue, that sounds like a Revit idea issue.
