### ISSUE TITLE
 Transferring parameters from csv to ifc.

### ISSUE THREAD

**Issue by BelyaevaDaria** [Autodesk/revit-ifc#619]
Good afternoon, colleagues. I'm trying to solve a problem with ifc. Maybe someone has encountered something similar, can suggest useful information. Thank you in advance for participating in the question.
The task is to transfer the values of the parameters present in the ifc file to the ifc file from csv and add the missing parameters from csv to ifc and transfer their values. Parameter values are transferred by the value of the key (revit id).

**Comment by BelyaevaDaria** [comment]
Thank you so much!

**Comment by louistrue** [comment]
Happy to help. If your issue is solved (at least kind of), you could close it...
