### ISSUE TITLE
Export linked Revit 2024 models (copied instances) as one federated IFC file

### ISSUE THREAD

**Issue by let4mi** [Autodesk/revit-ifc#626]
### Problem Description

If a user makes one central file and then links another Revit file into it, and then copies this linked file several times, where each instance of the linked file is manually positioned in the central file - once the federated IFC file is exported - all copied instances of the linked file will be located in the same place (overlapped). 
This issue was reported during the beta phase, however, it seems that the issue is still not resolved before public release.

as you may see in the images below(Revit):
![image](https://user-images.githubusercontent.com/69113079/232169286-e25f6f4d-e91a-4d04-9cd9-a9dcda182c79.png)

and exported IFC file opened in Solibri:
![image](https://user-images.githubusercontent.com/69113079/232169524-d7c6e427-8af8-427a-a2ff-86d4ddf865ba.png)

Is there any feedback on this? Any deadline for resolving the issue? 
It's crucial for everyday use on typical projects where using copied instances of one or multiple linked files is a common situation.

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x.x

### Windows Version

11 21H2

**Comment by AngelVelezSosa** [comment]
We are preparing the first open source update for Revit 2024 which I believe resolves the issue.  But we will re-verify.

**Comment by let4mi** [comment]
Now it works as expected. Good job.
