### ISSUE TITLE
Different file size on IFC from 2019 

### ISSUE THREAD

**Issue by COWItvo** [Autodesk/revit-ifc#63]
Hi

I have tried to compare 3 exported IFC (structural models) from Revit 2019 and Revit 2018. All IFC files from Revit 2019 is 30%-60% larger than Revit 2018. I have used the same IFC export setup and same active export view.  I can see, with a model comparison check, that it`s a deviation in the triangulation for steel object. Have I missed something in the export setup or is this normal? It could cause a issues in big projects where it's crucial that the size of the IFC files is kept low.

![image](https://user-images.githubusercontent.com/44081396/47646882-9b6bf400-db75-11e8-9c50-746ac54e76aa.png)

![image](https://user-images.githubusercontent.com/44081396/47646973-f3a2f600-db75-11e8-8e39-d2cb939621c7.png)

![image](https://user-images.githubusercontent.com/44081396/47646994-fef62180-db75-11e8-8aeb-649cdfc4a04d.png)

**Comment by JOuellette-Autodesk** [comment]
Not a bug. Works as designed.
