### ISSUE TITLE
PR: Plates in steel connections are exported as part of the steel connection in 22.4.2 and 24.1.0, but not in 23.2.5

### ISSUE THREAD

**Issue by COWImgbj** [Autodesk/revit-ifc#637]
### Problem Description

Plates in steel connections are exported as part of the steel connection in 22.4.2 and 24.1.0, but not in 23.2.5. I reckon this is a bug in 23.2.5?
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/b0993eeb-ff5c-4272-b717-f66b5efba439)
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/50891490-1477-4e38-b159-2ff622b6392f)
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/e9224f57-21c2-4813-a0e4-09ba53ce5e32)

### Revit Version

2023.1.x

### IFC for Revit Addon Version

23.2.5

### Windows Version

10 22H2

**Comment by o-babii** [comment]
Hello @COWImgbj ,

I have checked this issue, but I was not able to reproduce it on my side.
Could you please provide more information about your case? 
I would really appreciate an example file for which the problem is reproduced, details about export settings, or a journal file.

**Comment by COWImgbj** [comment]
I am exporting using IFC2x3 CV 2.0 with "Include Steel Elements", "Export only elements visible in view" and "Use active view when creating geometry" turned on. Level of detail set to "Low". With a user defined property set. No Revit or other IFC property sets. Everything else is turned off.

The plates are exported, but in 2022.4.2 and 2024.1 they are exported double. Plates and bolts inside the Structural Connection in Revit as IfcPlate and IfcMechanicalFastener and a grouped IfcBuildingElementProxy (Stuctural connection element). In 2023.2.5 the plates are not part of the IfcBuildingElementProxy and the bolts are not exported as IfcMechanicalFastener. Not necessarily a bug, but different behavior going back and forth between the versions. The grouped structural connection element are presented differently as you can see from the images of the element with the same IfcGUID.

What is a bug, is that double elements in 2022.4.2 and 2024.1 have a slight different placement (0,95 mm off) as you can see from the pictures.
IFC exporter 22.4.2
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/697202cb-ebc8-4dc7-9db8-b05ffd148b0f)

IFC exporter 23.2.5
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/6f92292b-f8e4-4fdd-9ff0-54d7ea523856)

IFC exporter 24.1
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/d5ffe061-af3a-4882-8b50-7ff14b995002)

**Comment by COWImgbj** [comment]
This seems to be fixed in 23.3.1.
