### ISSUE TITLE
INQ: 

### ISSUE THREAD

**Issue by jzcelectronics** [Autodesk/revit-ifc#638]
### Inquiry description

Hello,

Is it possible to add an IfcLightFixtureType into an existing Revit model. At present, opening an IFC file with an IfcLightFixtureType as a new project works as expected; the light fixture appears under 'Families > Lighting Fixtures' in the Project Browser. However, importing the IfcLightFixtureType into an already existing project does not seem possible. 
Linking an IFC file to an existing project, the IfcLightFixtureType is no longer recognized as a Lighting Fixture. 

Could someone please clarify whether this is a limitation within Revit's current IFC handling, or if there is a procedure I might be missing to accomplish this? Any workarounds or suggestions would also be appreciated.

Many thanks,

Jonny

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
Are you saying that if you have a trivial IFC file with a light fixture in it, you can link it into a project that has no light fixtures in it OK, but not one that does?

**Comment by jzcelectronics** [comment]
Thank you for your response. To clarify, the issue doesn't lie with the presence or absence of existing light fixtures in the project. Instead, the issue lies in the method of importing IFC files into an existing project, which, as it appears, can only be done through 'linking'. When importing the IFC file as a new project via File > Open > IFC, the light fixture is correctly identified and categorized under 'Families'. However, when I attempt to link the same IFC file into an existing project—irrespective of whether there are other families present—the light fixture is not recognized as such.

**Comment by AngelVelezSosa** [comment]
OK, that's by design.  Open IFC creates native elements as it can, at the expense of performance, some fidelity, and a link to the original data, but then you can modify it.  Link IFC creates properly categorized data with higher fidelity and performance, but it isn't editable (it isn't families or native elements).  So it depends on your workflow - are you coordinating or are you taking over the data?

**Comment by jzcelectronics** [comment]
Our specific use case involves generating custom IFC light fixture files, both with and without the IfcLightSource photometry. Our goal is to incorporate these files into projects across different platforms, including Revit. However, it appears that this might not be feasible at present. We were under the impression that importing an IFC file would behave similarly to importing a Revit family file. 
Thank you again for your assistance.

**Comment by AngelVelezSosa** [comment]
I'd say it isn't feasible out of the box.  With the Revit API, you could use the data in the IFC file to create or augment Revit families.

**Comment by jzcelectronics** [comment]
Funny - I was just reading the API documents. I really appreciate your all help, thank you!
