### ISSUE TITLE
PR: Sketch-based openings in sloped slabs not exported

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#643]
### Problem Description

This is a regression for IFC2x3 CV2 exports that was introduced between 23.2.5 and 23.3.0. Sketch-based openings in sloped slab elements (floor slabs and foundaton slabs) are not exported anymore. I have **not** tested for iFC4.

Revit:
![grafik](https://github.com/Autodesk/revit-ifc/assets/3014437/6b5bb41c-7c53-4e64-97a4-fb64235e0bb2)

23.2.5 export (IFC2x3 CV2):
![grafik](https://github.com/Autodesk/revit-ifc/assets/3014437/ae894b96-3728-4292-a32d-96ea1f18a2fd)

23.3.0 export (IFC2x3 CV2):
![grafik](https://github.com/Autodesk/revit-ifc/assets/3014437/33f5d120-ee36-4170-ba83-7e10a57b7ebb)

This was tested with the 23.3.0 exporter. Please note: This exporter version is not yet available for selection in the issue template (this PR fixes that: https://github.com/Autodesk/revit-ifc/pull/642).

Model to reproduce: https://github.com/andydandy74/MyIssues/blob/master/RevitIFC643/126_IFC_SketchBasedSlabOpenings.rvt

### Revit Version

2023.1.x

### IFC for Revit Addon Version

23.3.0

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
We will look at this ASAP.

**Comment by andydandy74** [comment]
Looks like the opening is created, but in top projection (probably on the plane the sketch lines are located on):

![grafik](https://github.com/Autodesk/revit-ifc/assets/3014437/3d55ea05-90ae-47c8-b120-ea15755e6c40)

**Comment by AngelVelezSosa** [comment]
We are checking to see if this was a problem with the back-submission or is also a problem in 2024 (I am guessing the latter, since otherwise I think we would already know, but still need to check).  In either case we will patch.

**Comment by andydandy74** [comment]
This looks fixed in 23.3.1: https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v23.3.1.0
