### ISSUE TITLE
PR: Type parameters missing

### ISSUE THREAD

**Issue by EPKoele** [Autodesk/revit-ifc#646]
### Problem Description

Type parameters are missing in user defined property sets when using exporter 2023.3.0 (version not listed in menu "IFC for Revit Addon Version"). Only checked for MEP elements. In previous exporter versions we didn't have these issues.

This issue is similar to issue #582 but using another (newer) exporter version.

[Project2_Type parameters.zip](https://github.com/Autodesk/revit-ifc/files/11731188/Project2_Type.parameters.zip)

### Revit Version

2023.1.x

### IFC for Revit Addon Version

Other / None

### Windows Version

10 22H2

**Comment by COWImgbj** [comment]
It seems that from 23.3.0 type and instance properties needs to be defined separately.  Detailed explanation is given in "C:\ProgramData\Autodesk\ApplicationPlugins\IFC 2023.bundle\Contents\2023\DefaultUserDefinedParameterSets.txt" 

# Since 23.3.0, type properties are not exported in case they are not specified in the user-defined property sets file.
#	To export type properties for the IFCElement, for example, 
#	a user should include "IFCElementType" in the proper .txt file.

**Comment by MagneGanz** [comment]
This does not work on Doors. Not able to export Type parameters. Works fine one other Categories.
![image](https://github.com/Autodesk/revit-ifc/assets/42205542/486641a6-6636-407f-a118-660e1a0c3dfd)
![image](https://github.com/Autodesk/revit-ifc/assets/42205542/ab0a7788-b5f4-44af-90d6-15d87161e92d)
![image](https://github.com/Autodesk/revit-ifc/assets/42205542/0e7e9620-75b4-465c-9ec7-e320c0edf881)

**Comment by COWImgbj** [comment]
Seems to be the same for Rebar Couplers. They are missing all typeparameters (exported with the same setup as Magne). They are also missing IFC Type, Predefined Type and Type name. 
![image](https://github.com/Autodesk/revit-ifc/assets/58807838/5a396ffa-003a-4ea5-9557-111fc846792e)

**Comment by MikeRCAD** [comment]
Hi,

I don't have issues with Doors with exporter 22.6.2.0 (Revit 2022), but have this issue with exporter 23.3.1.0 (23.3.5.0 only had issues with type properties of Stairs/Railings/Roofs)
Adding ElementType and/or I/T with PropertySets don't solve this.
 
In Revit 2022 I noticed the issue with Stairs, Railing and Roofs.

If I specify the door as "IfcBuildingElementProxyType", the type properties are Exported.
Just tried adding "IfcDoorStyle" along with IfcElementType in the Propertyset, so I guess we need to add all Element/Type definitions now?

Seems like something is changed and IfcElement no longer takes inherented elements?? At least for some, as Walls still do export type properties without specifying "IfcWall".

Hope this make sense for somebody and we can have IfcElement statement behave as before.

**Comment by AngelVelezSosa** [comment]
We looked into this.  You don't need to add all of the Element/Type definitions now, but IfcDoorStyle (and presumably, IfcWindowStyle) are not part of IfcElementType in the buildingSMART definition.  So this is expected, but of course could use better UI in Revit and perhaps a rethink in IFC5.
