### ISSUE TITLE
PR: IfcExportUIOverride version 22.6.2.0 not found

### ISSUE THREAD

**Issue by sayurlarismanis** [Autodesk/revit-ifc#647]
### Problem Description

Hi, 
so I have a report from my dynamo saying that there is a problem when loading the library from a certain dynamo package

![image](https://github.com/Autodesk/revit-ifc/assets/136445758/4d3e4a05-4652-4e75-97fc-fac22e8e4fe7)

It's in german, but the description under it says that the system could not find IFCExportUIOverride Version 22.6.2.0

![image](https://github.com/Autodesk/revit-ifc/assets/136445758/cb0042d8-58ea-4f2f-81f3-94d77fc0605c)

I already updated my Revit to 2022.1.4 according to the version appropriate for the package and also the corresponding IFC version which is the 22.6.2.0

My IFCExporterUI is saved under C:\Program Files\Autodesk\Revit 2022\AddIns\IFCExporterUI, is this correct?

### Revit Version

2022.1.x

### IFC for Revit Addon Version

22.6.2

### Windows Version

10 22H2

**Comment by denizmaral** [comment]
That's a problem of Orchid package. That assembly has been renamed. The package creator should add new reference to his project.
