### ISSUE TITLE
PR: IFC mapping UI is not working in 2023

### ISSUE THREAD

**Issue by Teun1** [Autodesk/revit-ifc#648]
### Problem Description

Using IFC Exporter 23.3.0 (latest version missing in the dropdown list)

The Export to IFC As, Export Type to IFC As UI does not show up at all.
Same for IFC Predefined Type and Type IFC Predefined Type.
Because I cannot change the string manually, normal IFC mapping is not possible.
I can however change values with the use of Dynamo.

I tried disable all Addins. But that does not help.
I tried a clean new template. I tried the Autodesk content. But that does also not help.

It does work in Revit 2024.0 with IFC exporter 24.0.20.20 (It looks like we did not upgrade to 24.1.0)

### Revit Version

2023.1.x

### IFC for Revit Addon Version

Other / None

### Windows Version

10 21H2

**Comment by Kakihara83** [comment]
Notice the same issue! It's a major issue, please could someone fixed this?
 In addition to the non-export ifc mapping of element and the no-show dropdown list, we also notice that some type parameter element with user defined pset don't export anymore like the width of wall, base column etc..
All things normal with the ifc exporter downgraded.

**Comment by dvrvb** [comment]
Same issue here as Teun described.

**Comment by Teun1** [comment]
Any updates on this one?
Can it be reproduced?

**Comment by Moult** [comment]
I've been receiving this error report from consultants as well. They are using Release 23.3.0 for Revit 2023.

**Comment by Teun1** [comment]
With the latest version 23.3.1 everything works again. Thanks
