### ISSUE TITLE
PR: Pset_CoveringFlooring not supported for IFC4 RVArch

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#653]
### Problem Description

Apparently it's not possible to export data for the ```Pset_CoveringFlooring``` property set in IFC4 RVArch for floors exported as ```IfcCovering.FLOORING```. It is implemented for the IFC2x3 CV2 export, though. Tried this with the old and new shared parameters.

Minimal model to reproduce: https://github.com/andydandy74/MyIssues/blob/master/RevitIFC653/078_IFC_Pset_CoveringFlooring.rvt

### Revit Version

2023.1.x

### IFC for Revit Addon Version

23.3.0

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
This seems to be purposeful.  Pset_CoveringFlooring is on the allowed list for IFC2x3 CV2.0, but not IFC4 RV, which implies that it isn't included in the supported IFC4 RV property sets.  @WawanSolihin , do you know if this is something you did on purpose or was an oversight?

**Comment by andydandy74** [comment]
Sorry, should have checked if it's included in the MVD (which it isn't: https://standards.buildingsmart.org/MVD/RELEASE/IFC4/ADD2_TC1/RV1_2/HTML/annex/annex-b/alphabeticalorder_psets.htm).

**Comment by WawanSolihin** [comment]
Yes, you are right. Pset_CoveringFlooring is not included in the IFC4 RV MVD and therefore it is not in the list of valid Pset for the IFC4 RV export
