### ISSUE TITLE
Property name problem

### ISSUE THREAD

**Issue by adoomy** [Autodesk/revit-ifc#656]
### Problem Description

In the IFC4x3 version, the property name "NumberOfRisers" in Pset_StairFlightCommon is incorrectly exported as "NumberOfRiser". Please modify it to "NumberOfRisers" as requested.

### Revit Version

2023.1.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
is https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3_0_0/lexical/Pset_StairFlightCommon.htm wrong?  That says NumberOfRiser.

**Comment by adoomy** [comment]
Sorry. I was confused about the property IfcStairFlight.NumberOfRisers. You are correct in your statement. Thank you.
