### ISSUE TITLE
PR: Large number of objects in linked IFC not created as DirectShape

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#658]
### Problem Description

I have a linked MEP model that is missing a whole lot of entities.

Here's how the model looks when linked in Revit 2021:

![MicrosoftTeams-image](https://github.com/Autodesk/revit-ifc/assets/3014437/8c7d653d-58ff-40de-a6ae-13caf8ff3114)

And here the same model linked in Revit 2023:

![MicrosoftTeams-image (1)](https://github.com/Autodesk/revit-ifc/assets/3014437/e86e36c2-1cf1-4a8d-bd35-a5a14f267690)

The log file shows many lines like this one:

```
#4308: ERROR: At least one member of pGeomArr does not satisfy DirectShapeType validation criteria. Parameter name: pGeomArr
```

### Revit Version

2023.1.x

### IFC for Revit Addon Version

23.3.0

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
That looks like a standard "far from the origin" issue.  Is it?

**Comment by andydandy74** [comment]
Only about 70m - that shouldn't be too far, should it? ;-)

![grafik](https://github.com/Autodesk/revit-ifc/assets/3014437/34f7231a-0bd0-457b-a64c-18234ac00c4e)

The model looks okay in Solibri and BIMcollab Zoom btw.

**Comment by AngelVelezSosa** [comment]
70m?  Too far!  It just looked a bit jaggy in the image but that could have been the photo itself.  Hard to know what the issue is without the file, although I do remember dealing with that particular error message at some point.

**Comment by andydandy74** [comment]
@AngelVelezSosa - Sent you a download link.

**Comment by parrela** [comment]
OK, I do see these missing ducts in 2023, but not in 2024. I'll file an issue to investigate. meanwhile @andydandy74 can you try it with the IFC open source uninstalled?

**Comment by andydandy74** [comment]
@parrela - Unfortunately the same issue with Revit 2023.1.2 after uninstalling the IFC open source addin:

![grafik](https://github.com/Autodesk/revit-ifc/assets/3014437/5b9e5992-6b66-4976-b201-33293e1125fb)

**Comment by parrela** [comment]
REVIT-209589

**Comment by AngelVelezSosa** [comment]
OK, the issue here is that there is some invalid 2D geometry - in particular, there are some representations that are IFCVECTORs, but those are infinitely long.  We will change the code to ignore these.  But I'd say the file is invalid.

**Comment by andydandy74** [comment]
Yes, I thought it might be. I had tried to run the model through the KIT validator but it crashed... 😁 
Thanks for making those changes even though the issue likely is caused by an outside party. Much appreciated.

**Comment by AngelVelezSosa** [comment]
Note that Revit 2024.1 does seem to deal with this OK - we have made some radical changes (part 1...) to how we import IFC geometry and I would very much appreciate issues you see in Revit 2024.1 linking in IFC files (specifically).  Performance is still a definite WIP and there are some areas where we are still using "legacy" support for some surfaces for now, but in general fidelity should be significant better from now on.

**Comment by andydandy74** [comment]
Haven't encountered this with other models again and in 2024.2 this model links just fine
