### ISSUE TITLE
which is the best Ifc class for exporting Area from Revit to Ifc ?

### ISSUE THREAD

**Issue by ArunSanthosh98** [Autodesk/revit-ifc#671]
### Enhancement Description
If I have to export Areas like 'Buildup Area', 'Gross Area' from Revit. and show them in 3D geometry under each IfcBuildingStorey in an IFC. what steps I should follow.

* I have tried ExportAs to IfcSpace and it do get export with IfcSpace Psets.
* Is there any other best practice (better Ifc Class) for exporting areas to Ifc 
 

![image](https://github.com/Autodesk/revit-ifc/assets/110660510/dc909655-151b-488c-80e5-366e484146bd)

![image](https://github.com/Autodesk/revit-ifc/assets/110660510/3234b6cf-6757-4b7b-a89c-75e9ccb03c1c)

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by lejla-adsk** [comment]
Hi Arun, as already mentioned, IfcSpace is the recommended and default way to export areas. You can always add additional data using custom Psets. 
In general, you can map Areas to other categories, but I don't really see an additional value in doing so. The full overview of possible mappings can be found here: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Supported-IFC-Class-mapping-when-exporting-Revit-models-to-IFC.html?collection=181476 

But eventually someone else has a better idea?

**Comment by ArunSanthosh98** [comment]
> Hi Arun, as already mentioned, IfcSpace is the recommended and default way to export areas. You can always add additional data using custom Psets. In general, you can map Areas to other categories, but I don't really see an additional value in doing so. The full overview of possible mappings can be found here: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Supported-IFC-Class-mapping-when-exporting-Revit-models-to-IFC.html?collection=181476
> 
> But eventually someone else has a better idea?

Thank you

**Comment by AngelVelezSosa** [comment]
Agreed with comments above.  IfcSpace is best for areas.  By default we ship as not exported so that you don't get duplicated area and room information.  But there's no problem with turning it on.
