### ISSUE TITLE
IFC4Add2TC1 Entity/TypeClasses

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#68]
IFC4Add2TC1 Entity/TypeClasses

Since a few newly added classes in IFC4 are already deprecated in IFC4Add2TC1,
there are now a few export translations that are not yet consistent in my opinion.

R2019
Using IFCExportAs

While for instance IFCExportAs = IfcMemberStandardCase is nicely translated in the IFC-export to IfcMember and its IfcMemberType,
there is some inconsistency with:

- IFCExportAs = IfcPlateStandardCase (which is deprecated in IFC4Add2TC1) > is now only translated to IfcPlate: IfcPlateType is missing

- IFCExportAs = IfcSlabeElementedCase (which is deprecated in IFC4Add2TC1) > still translated to IfcSlabElementedCase: should be IfcSlab + IfcSlabType

- IFCExportAs = IfcWallElementedCase (which is deprecated in IFC4Add2TC1) > still translated to IfcWallElementedCase: should be IfcWall with PredefinedType ELEMENTEDWALL  + IfcWallType

- IFCExportAs = IfcOpeningStandardCase (which is deprecated in IFC4Add2TC1) > still translated to IfcOpeningStandardCase: should be IfcOpeningElement

There is also an issue with:
IFCExportAs = IfcFooting > now only exporting as IfcFooting: the IfcFootingType is missing
IFCExportAs = IfcPile > now only IfcPile: IfcPileType is missing
IFCExportAs = IfcProxy (which is deprecated in IFC4Add2TC1) > still translated to IfcProxy: should be IfcBuildingElementProxy (Why did they deprecate IfcProxy? Retorical question)

I'm also wondering why the following exportable classes are missing their TypeClass in the IFC-export:
IfcDistributionControlElement is missing its IfcDistributionControlElementType
Also an issue for:
IfcDistributionFlowElement
IfcEnergyConversionDevice
IfcFlowController
IfcFlowFitting
IfcFlowMovingDevice
IfcFlowSegment
IfcFlowStorageDevice
IfcFlowTerminal
IfcFlowTreatmentDevice

Note: with missing TypeClass, I don't mean the use of the TypeClass as value for IFCExportAs, I really mean how it is written in the IFC-file, where the EntityClass for the occurence is related to its TypeClass, and that TypeClass is sometimes missing.

Regards,
Dirk

**Comment by WawanSolihin** [comment]
Thanks Dirk,

There are places in the codes that do "special" export, such as Footing, Pile. These are the ones that mostly explain the issues you highlighted above. I will be fixing those.
However for the IfcDistributionElement thing is a little more difficult. In IFC2x3 the instance of those MEP element may be IfcFlowController (for example) and the associated type is more specific like IfcValveType. In cases that the type is not assigned (e.g. IfcExportAs = IfcFlowTerminal), we could create an instance of IfcFlowTerminal without the type. But in IFC4 IfcFlowTerminal has been made deprecated (and will be made abstract in future, while currently is still a valid entity) and the concrete classes are now paired with the type, e.g. IfcValve and IfcValveType. Therefore, especially for MEP objects, it is better and safer to use the typeclass for IfcExportAs, e.g. IfcExportAs=IfcValveType. This will be valid in both IFC2x3 and IFC4.
And because of the valid and yet deprecated status of the sub-entities of IfcDistributionElement. The entity such as IfcFlowTerminal will still be created but not the IfcFlowTerminalType that is now abstract. I will be looking into some improvements in this area.

Regards,
Wawan

**Comment by dvrvb** [comment]
Hi Wawan,

Any idea what the future 'proxy' will be instead of IfcDistributionElement (for distribution elements)?
Because of your remark, I just now notice the red change text at the buildingSMART site, that indeed it is deprecated for instantiation and will be made abstract.

Your remark about the TypeClass being more specific than the EntityClass in IFC2x3, is indeed one of the nice improvements of IFC4 where those are 'levelled'.
Fortunately there is also a lot of forgiveness & translation in the exporter, like it's correctly translating IfcGasTerminal, while it is not even existing in IFC2x3 as EntityClass. Only IfcGasTerminalType exists as TypeClass (with IfcFlowTerminal as EntityClass): these kind of translations of the exporter are in my opinion good and acceptable, and are really contributing in making IFC a bit more easy to apply in practice.
(I only have doubts about the acceptance of IfcFloor and IfcAssembly ... personally I would like to see them removed)

IFC4Add2TC1: So, while IfcDistributionElement and IfcDistributionElementType are deprecated for instantiation and will be made abstract, and as you mentioned, this is also valid for the EntityClass IfcFlowTerminal, but I'm now wondering why then IfcFlowTerminalType isn't deprecated as well ... but that's probably a question for buildingSMART.
Anyway, now it's clear for me that the supertypes that I mentioned are deprecated for instantiation.

I will retest some last issues with the PredefinedTypes: https://sourceforge.net/p/ifcexporter/discussion/general/thread/b6a9156b/#f126
and then I think the issues for the Entiy/TypeClasses and PredefinedTypes for IFC4RV are solved. At least based on the use of IfcExportAs on Generic Models.  There are a few other issues, like the PredefinedTypes in the mapping table that are not working anymore: https://github.com/Autodesk/revit-ifc/issues/25

Regards,
Dirk

**Comment by WawanSolihin** [comment]
Thank you Dirk for the comprehensive test cases. It is certainly very useful to ensure the export is consistent and complete. Generally the type and predefinedtype should be correct as they are checked against the schema. However, the schema version used is IFC4Add2, not the TC1 yet. I do not have the TC1 version yet. I will ask the buildingSMART guys to make it available. Also there are some codes written specifically for some types of object that may not use the same path as the others.
I will take a look at the report and use the test case to verify any fix.

Thanks,
Wawan

**Comment by dvrvb** [comment]
There seems to be an issue with the IFC2x3CV2.0 export of the PredefinedTypes, and something got broken during the process since version 19.1.
For a lot of Classes the PredefinedTypes are not anymore exported. So I also went back to the original version 19.1.

The attached zips are containing the IFC-export with version 19.1 as well as with the current GitHub version of the IFC4RV-cert branch.
I added a simple Solibri ITO to list the PredefinedTypes next to the SOLL-PredefinedType-parameter. To be sure, I verified some of them also with Notepad (but not all of them, so there can/will be also Solibri issues in some cases).

To be sure that it has nothing to do with the Entity-input-values for IFCExportAs, I now also made the TYPE-variant.
Since the previous testmodel already contained 'EntityClass-alike' values, as well as 'Type-alike' values in 2 separated parameters, I now linked the 'Type-alike' values to the IFCExportAs parameter (although this is an Instance Parameter in the Family of the Generic Model, but that doesn't matter for the export-translation).

The 2 variants of the testmodel are:
- IFC IfcClass_PredefinedType_ENTITY_R2019.rvt
[IFC IfcClass_PredefinedType ENTITY.zip](https://github.com/Autodesk/revit-ifc/files/2594636/IFC.IfcClass_PredefinedType.ENTITY.zip)
- IFC IfcClass_PredefinedType_TYPE_R2019.rvt
[IFC IfcClass_PredefinedType TYPE.zip](https://github.com/Autodesk/revit-ifc/files/2594640/IFC.IfcClass_PredefinedType.TYPE.zip)

In comparison with the previous testmodel, I only corrected 1 value: there was a "0" as value for the IFC2x3 SOLL PredefinedType of an IfcDistributionElement(Type), which I removed. I did not completely verified my own "SOLL-values" since I was planning to do so in comparison with the outcome of the export.

Best regards,
Dirk

**Comment by dvrvb** [comment]
At first, I noticed that I made some mistakes in my test model, at least concerning IFC2x3CV2.0 
- typo: the T was missing in RADIAN'T'HEATER (IfcElectricAppliance)
- PROGRAMMABLE did not exist in IFC2x3 (so it has to be NOTDEFINED) (IfcController)


For **IFC2x3CV2.0** the current status seems to be:

remaining issues with PredefinedTypes for:
-IfcWall (all are now NOTDEFINED)
-IfcSlab (only the one without a value for the PredefinedType is now by default translated to FLOOR, instead of NOTDEFINED)
-IfcSpace (both USERDEFINED and NOTDEFINED are missing)
-IfcRoof (USERDEFINED is translated to NOTDEFINED)
-IfcElectricDistributionPoint (all PredefinedTypes are missing)

-IfcReinforcingBar (the TypeEnum in IFC2x3 was IfcReinforcingBarRoleEnum for the attribute ReinforcementRole of IfcSectionReinformcementProperties, and changed in IFC4 to IfcReinforcingBarEnum as TypeEnum for the PredefinedType of IfcReinforcingBar: so formally it didn't exist in IFC2x3: so it is OK that they all are translated to nothing. 

IfcClass issues:
-IfcElectricHeater is now translated to IfcBuildingElementProxy 
-IfcGasTerminal is now translated to IfcBuildingElementProxy (of course only IfcGasTerminalType is only existing, but also explicitly exported as IfcGasTerminalType, it is translated to IfcBuildingElementProxy)
-IfcProxy is now translated to IfcBuildingElementProxy with PredefinedType USERDEFINED while IfcProxy is only deprecated in IFC4


Issues with IfcStair/IfcRoof(other than USERDEFINED)/IfcRamp as seen in Solibri are only Solibri-related (not a Revit-exporter-issue)

Regards,
Dirk

**Comment by dvrvb** [comment]
Hi Wawan,

Taking into account Solibri/BIMVision issues, but also other mistakes in my testfile, I think I can pinpoint the issues to just only a few minor cases. Perfection is close, very very close :-)


**IFC4RV1.1/2**
(leaving out possible IFCAdd2 IFCAdd2TC1 related stuff)

PredefinedTypes:
- IfcSlab (without PredefinedType) is translated to FLOOR: I would expect NOTDEFINED
- IfcWindow (without PredefinedType) and IfcWindow.NOTDEFINED: now both are translated to the PredefinedType WINDOW instead of NOTDEFINED
- IfcDoor (without PredefinedType) and IfcDoor.NOTDEFINED: now both are translated to the PredefinedType DOOR instead of NOTDEFINED

- IfcSurfaceFeature: all are now translated to NOTDEFINED
- IfcGrid: all are now translated to NOTDEFINED

Classes:
- IfcProjectionElement/IfcExternalSpatialElement/IfcAnnotation: strictly spoken they should be translated to IfcBuildingElementProxy since they are out of the scope of IFC4RV1.1
Probably it is safer to leave it this way until IFC4RV1.2 is really published.



**IFC2x3CV2.0**

PredefinedTypes:
- IfcSlab (without PredefinedType) is translated to FLOOR: I would expect NOTDEFINED
- IfcElectricDistributionPoint: the PredefinedTypes are missing

Classes:
- IfcSpaceHeaterType is translated to IfcElectricHeaterType, while it should be IfcSpaceHeaterType
- IfcElectricHeaterType/IfcGasTerminalType is translated to IfcBuildingElementProxy 

- IfcProxy is translated to IfcBuildingElementProxy (while IfcProxy exists in IFC2x3) and the PredefinedTypes are missing: but probably it is OK to leave it this way.

Best regards,
Dirk

**Comment by WawanSolihin** [comment]
Hi Dirk, 

A few of them are assigned default predefinedtype according to the current default assignment behavior:
- IfcSlab with default FLOOR
- IfcWindow with default WINDOW
- IfcDoor with default DOOR
I am hesitating to change it at the moment because this will change the current behavior and those predefinedtypes look valid too.

I wil check the others.

Thanks for the feedback,
Wawan

**Comment by dvrvb** [comment]
concerning fix https://github.com/Autodesk/revit-ifc/commit/c9aca0e01e39ddd25cb1ef8a75c91db05016f316


**IFC4RV1.1/2**
**Ultimate fix :-)**

Great: I think for IFC4RV the mission is completed!
Whatever RV1.2 will bring us, the input and output of the exporter is now clear, complete and consistent (based on the use of IfcExportAs on Generic Models).

PredefinedTypes:
- IfcSlab (without PredefinedType) is translated to FLOOR: I would expect NOTDEFINED
→ due to default behavior: FLOOR is OK
- IfcWindow (without PredefinedType) and IfcWindow.NOTDEFINED: now both are translated to the PredefinedType WINDOW instead of NOTDEFINED
→ due to default behavior: WINDOW is OK
- IfcDoor (without PredefinedType) and IfcDoor.NOTDEFINED: now both are translated to the PredefinedType DOOR instead of NOTDEFINED
→ due to default behavior: DOOR is OK
- IfcSurfaceFeature: all are now translated to NOTDEFINED
→ fixed: OK
- IfcGrid: all are now translated to NOTDEFINED
→ fixed: OK (only BIM Vision has issue in showing these PredefinedTypes)

Classes:
- IfcProjectionElement/IfcExternalSpatialElement/IfcAnnotation: strictly spoken they should be translated to IfcBuildingElementProxy since they are out of the scope of IFC4RV1.1
Probably it is safer to leave it this way until IFC4RV1.2 is really published.
→ OK: At the moment the output is rather RV1.1 'plus', and that seems to be OK (in my opinion).



**IFC2x3CV2.0**
**Penultimate fix ?**
→ seems only still an issue with IfcElectricHeaterType, probably also IfcGasTerminalType

PredefinedTypes:
- IfcSlab (without PredefinedType) is translated to FLOOR: I would expect NOTDEFINED
→ due to default behavior: FLOOR is OK
- IfcElectricDistributionPoint: the PredefinedTypes are missing
→ fixed: OK (actually it was not a PredefinedType, but the DistributionPointFunction)

Classes:
- IfcSpaceHeaterType is translated to IfcElectricHeaterType, while it should be IfcSpaceHeaterType
→ fixed: OK
- IfcElectricHeaterType/IfcGasTerminalType is translated to IfcBuildingElementProxy
**→ issue: IfcElectricHeaterType is still translated to IfcBuildingElementProxy
→ ? IfcGasTerminalType is indeed present in the IFC-model, but none of the viewers (FZK Viewer/BIM Vision/Solibri/XBim Xplorer) seems to recognize it as GasTerminal. They all are showing it as BuildingElementProxy.**

- IfcProxy is translated to IfcBuildingElementProxy (while IfcProxy exists in IFC2x3) and the PredefinedTypes are missing: but probably it is OK to leave it this way.
→ OK: now translated to IfcProxy (without PredefinedTypes)

Best regards,
Dirk

**Comment by dvrvb** [comment]
IFC-sample with the result in IFC2x3CV2.0 for the 2 TypeClasses IfcElectricHeaterType and IfcGasTerminalType, which are now IfcBuildingElementProxy. 
[IFC2x3_GasTerminal_ElectricHeater_TypeClass.zip](https://github.com/Autodesk/revit-ifc/files/2683398/IFC2x3_GasTerminal_ElectricHeater_TypeClass.zip)

Best regards,
Dirk

**Comment by dvrvb** [comment]
Thx Wawan!
Mission completed!
With https://github.com/Autodesk/revit-ifc/commit/8187887fb0f18ff2f3fde9ed3a3c3ac864684208 this issue is finally finding closure :-)
… and it exposed (again) a flaw in my testfile … due to a typo on the buildingSMART website ...
<img width="688" alt="image" src="https://user-images.githubusercontent.com/41319048/50768628-610f8900-1281-11e9-8480-feb896e6ce43.png">

**Comment by WawanSolihin** [comment]
Phew, finally.
Thanks Dirk for your support too.
I noticed the issue of that GASTERMINAL, but I forgot to tell you. Sorry about that.

Best regards,
Wawan
