### ISSUE TITLE
Revit 2023 - which IFC Supports 

### ISSUE THREAD

**Issue by Mairh93** [Autodesk/revit-ifc#681]
### Enhancement Description

Hello all, 

I would like to know which version of IFC Revit supports in the classifications (see image below). Is it the IFC  4.0.2.1 ? Any idea about IFC 4.3? 

Thank you in advance!

![REVIT 2023 IFC](https://github.com/Autodesk/revit-ifc/assets/27021809/7edf426f-0f72-4b51-8c21-5f05c074d063)

### Revit Version

2023.0.x

### IFC for Revit Addon Version

Other / None

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
IFC4 is 4.0.2.1.  IFC4.3 isn't on there yet and isn't on the immediate roadmap but we do intend to have full IFC4.3 once demand picks up and IFC4.3 is finalized.

**Comment by Mairh93** [comment]
@AngelVelezSosa , Thank you a lot for the answer!
