### ISSUE TITLE
INQ: is revit capable of exporting ifc with textures? using IfcSurfaceTexture supertype?

### ISSUE THREAD

**Issue by Baruchware** [Autodesk/revit-ifc#685]
### Inquiry description

Hello I am looking to some ifc files using IfcSurfaceTexture supertype (IfcImageTexture, IfcBlobTexture, IfcPixelTexture) in order to run some tests, is revit capable of exporting files like this?

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
We don't export texture information in Revit, and I don't believe there's an MVD that supports textures.
