### ISSUE TITLE
INQ: Why revit 2023 ifc can export whole longitude and latitude in IFCPOSTALADDRESS but revit 2022 can not

### ISSUE THREAD

**Issue by u0416033** [Autodesk/revit-ifc#686]
### Inquiry description

I encounter problems when I use the revit 2022 export  ifc that the format of latitude and longitude degrees minutes and seconds[(24,9,1,228008),(120,37,45,13435)] can not turn to the correct latitude and longitude (120.629170399,24.150341114). I think it isn't precise enough . 
I see the revit 2023 ifc can export the latitude and longitude that user enter in the location
Can revit 2022 can do the same thing?

revit 2022 export :
#126= IFCPOSTALADDRESS($,$,$,$,('\X2\53F04E2D5E0253575C6F53406C385BCC6BB5\X0\95\X2\3001\X0\96\X2\5730865F\X0\'),$,'','','','\X2\4F7F752880055B9A7FA9\X0\');
revit 2023 export :
#101=IFCPOSTALADDRESS($,$,$,$,('Enter address here'),$,'','24.1503772735596','','120.628967285156');

### Revit Version

2022.1.x

### IFC for Revit Addon Version

22.6.2

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
Latitude and longitude go into IFCSITE, not IFCPOSTALADDRESS.  IFCPOSTALADDRESS is the literal address you'd put on an envelope.
