### ISSUE TITLE
PR: Category Doors - Export Type Properties with UserDefined Pset

### ISSUE THREAD

**Issue by MagneGanz** [Autodesk/revit-ifc#694]
### Problem Description

I have Revit 2023.1 with IFC Exporter 23.3.1.
In our project we export with UserDefined Psets. By adding IfcElement and IfcElementType to the Pset definition we can usually export both Instance and Type Parameters to IFC. 

But, I cannot make it work for Category Doors exported to IfcDoor (IfcDoorType). Type Properties just wont export. Can you show me an example were you succeed with exporting Type Parameters for Doors to User Defined Pset? Please?

I cannot figure out how it's don the proper way, and I believe it's due to a bug. Unless someone proves me wrong.

### Revit Version

2023.1.x

### IFC for Revit Addon Version

23.2.5

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
Do you have a sample file to look at (Revit and PSet)?  I believe doors do work, but they may need special treatment because of the IFC class hierarchy.

**Comment by MagneGanz** [comment]
It might actually be an issue on my computer. Someone told me that the Door Type issue should be fixed on version 23.3.1. And you need to uninstall 23.3.0 first. At my computer the two version existed in parallell. That might be an issue.

**Comment by AngelVelezSosa** [comment]
That shouldn't be able to happen but sometimes it does.

**Comment by MagneGanz** [comment]
Manged to fix the installation. But I am still not able to get Type Parameters for the doors. See attached files.

[Files.zip](https://github.com/Autodesk/revit-ifc/files/12831072/Files.zip)

**Comment by o-babii** [comment]
Hello @MagneGanz ,

The actual reason for such behavior lies in the IFC2x3 scheme itself.
The IfcDoorType entity was added only in IFC4 (https://standards.buildingsmart.org/MVD/RELEASE/IFC4/ADD2_TC1/RV1_2/HTML/schema/ifcsharedbldgelements/lexical/ifcdoortype.htm).
That is why in your case type properties exported correctly to IFC4, but not to IFC2x3

The proper IFC entity for door type is IFCDoorStyle (deprecated in IFC4) (https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifcarchitecturedomain/lexical/ifcdoorstyle.htm).

To export door type properties to IFC2x3 you need to add IFCDoorStyle to your Pset file.

Here are the sample and export results:

_PropertySet:	FOB_Dør_Info	I	IfcDoor,IfcDoorType_
![image](https://github.com/Autodesk/revit-ifc/assets/25076346/2b24e208-4e14-496d-8712-b73acfa9aebd)

_PropertySet:	FOB_Dør_Info	I	IfcDoor,IfcDoorType,IfcDoorStyle_
![image](https://github.com/Autodesk/revit-ifc/assets/25076346/8c3923b2-ed25-41b3-925d-3bc62a21ab16)

Attaching fixed Psets file:
[fixed_FOB_IFC_UserDefinedParameterSets_ARK_NO.txt](https://github.com/Autodesk/revit-ifc/files/12929905/fixed_FOB_IFC_UserDefinedParameterSets_ARK_NO.txt)

You can also use higher-level entities but note that IFCDoorStyle is not a subclass of IFCElementType.
![image](https://github.com/Autodesk/revit-ifc/assets/25076346/c0fa8a27-5ed4-4ccf-9a6a-facf11a52501)

Please let us know if this workaround works in your case, or if you have any questions on this.
Thanks

**Comment by MagneGanz** [comment]
Thank you so much @o-babii , I would never figured this out on my own.
