### ISSUE TITLE
IfcTaskTime

### ISSUE THREAD

**Issue by Mairh93** [Autodesk/revit-ifc#697]
### Inquiry description

Dear all, 

I want to add the 4D information in IFC file. I saw that there is the Class: IfcTaskTime (IfcDateTime, IfcDuration etc). How I could add them in Revit 2023?

Thank you in advance!

### Revit Version

2023.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
You would have to modify the export code - we don't support these entities currently, as they are not prt of a known MVD.
