### ISSUE TITLE
Character encoding issues with import class mappings in German locale

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#7]
These are actually several interconnected issues occurring when using the UI for the import class mappings  (Open > IFC Options) in the German Revit UI.

1. German Umlaute are not displayed correctly when using a UTF8-encoded import class mapping file.
![grafik](https://user-images.githubusercontent.com/3014437/42466269-b03cc202-83ae-11e8-9cd5-7cb2064df89e.png)
(Should say "Luftdurchlässe"...)

2. When editing the import class mappings in the UI and subsequently saving them, the file is ANSI-encoded.
Previous state:
![grafik](https://user-images.githubusercontent.com/3014437/42466361-fe6aa3e0-83ae-11e8-80b8-1c9dab57f696.png)
After saving:
![grafik](https://user-images.githubusercontent.com/3014437/42466502-67de658c-83af-11e8-9d65-031ce75338bb.png)

3. Using an ANSI-encoded import class mapping file with "corrected" Umlaute will result in import errors for the affected categories when linking / importing an IFC file.
![grafik](https://user-images.githubusercontent.com/3014437/42466633-bbb61ef2-83af-11e8-85ea-5d5958e9b381.png)

Tested in 18.4

Workaround:
* Do not use the UI. 
* Keep the import class mapping file UTF8-encoded.
* Maintain/edit the file outside of Revit.

Expected behaviour:
* UI should display Umlaute correctly
* Encoding used when saving from UI should not produce the abovementioned errors when linking/opening IFC files.

**Comment by cwaluga** [comment]
Came here to report the same thing. This should be pretty easy to fix. I guess you just have to add an encoding in the constructor here: [https://github.com/Autodesk/revit-ifc/blob/cd2551b77554a97d92f0605a72f28fee3a980039/Source/Revit.IFC.Import/Utility/IFCCategoryUtil.cs#L479](url)

**Comment by JOuellette-Autodesk** [comment]
Fixed with prior version
