### ISSUE TITLE
PR:  Ifc Export As can not be opened

### ISSUE THREAD

**Issue by denizmaral** [Autodesk/revit-ifc#700]
### Problem Description

I see that it's been reported that the problem had been solved with 23.3.1 version for Revit 2023 but I still have that problem. 

PS: I just updated WallSweepExporter.cs on my computer. Once it was stuck, I had to end the process. After that I could not open that window anymore.

### Revit Version

2023.1.x

### IFC for Revit Addon Version

23.2.5

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
Can you be more specific about the issue you are encountering?

**Comment by denizmaral** [comment]
When I click on three points in element properties palette in Revit, it does not open that window to select an IfcClass. It happens nothing.

**Comment by denizmaral** [comment]
> HI @denizmaral, This is known issue for 23.3.0 but, looks like it is reproducible for you with 23.3.1, could you please add journal file to check. Also, you said that you updated the WallSweepExporter.cs, so do you use some custom version?

Thank you very much for answering. I checked it again and I see that I am using 23.2.5. I will try to upgrade it.
