### ISSUE TITLE
PR: IfcWindowType/IfcDoorType missing exported properties

### ISSUE THREAD

**Issue by sema-soft-dev** [Autodesk/revit-ifc#719]
### Problem Description

I have a model with 4 walls, 1 ceiling, 1 door, and 1 window. I am trying to export an IFC with one additional property ("Type Comments" or "Typenkommentare", since my Revit is in German). All type comments have a value and are not empty.

<img width="1600" alt="Issue_Revit" src="https://github.com/Autodesk/revit-ifc/assets/154235472/2836b1d4-e4a5-4834-8e6d-a28ae2d97b4d">

<img width="903" alt="Issue_MappingFile" src="https://github.com/Autodesk/revit-ifc/assets/154235472/bc0295d4-b593-4655-9f52-3f5d178ac9a6">

For the walls and the ceiling, it is correctly exported as a the new property specified in the mapping file. But for the door and window, the property set is missing.

<img width="1440" alt="Issue_IfcWall" src="https://github.com/Autodesk/revit-ifc/assets/154235472/5e5d75ae-a8ac-4ba8-8a81-c8d8d8a378aa">

<img width="1390" alt="Issue_IfcDoor" src="https://github.com/Autodesk/revit-ifc/assets/154235472/2b17422d-35ea-4157-9504-5ff8b46761f6">

I tried using "I" instead of "T" in the mapping file and also tried specifying different types (only IfcBuildingElement and IfcElement, only the specific types and so on). Neither worked.

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by o-babii** [comment]
Hello @sema-soft-dev ,

Could you tell me which version of IFC you use for exporting? Different entities are used for door types and window types in IFC2x3 and IFC4.

Please try this, and let me know if is it working for you.
For IFC2x3 the IFCDoorStyle and IFCWindowStyle 
For IFC4 the IFCDoorType and IFCWindowType

Also, I see a typo in your pset file: "IfcDoorTyoe", but it is not a reason for the issue

**Comment by sema-soft-dev** [comment]
Hi @o-babii ,

I am using IFC2x3.

I  tried your recommendations and I got it to work. Thanks a lot!
For future reference, I ended up using it like this:

```
PropertySet:	Our_Set	T	IfcWallType, IfcCoveringType, IfcWindowStyle, IfcDoorStyle
	ID	Text	Typenkommentare
```
