### ISSUE TITLE
Pset_BeamCommon

### ISSUE THREAD

**Issue by HenkMolhoek** [Autodesk/revit-ifc#72]
Angel,

When we export a new IFC File from Revit 2019 we are missing in Pset_BeamCommon Property Load Bearing. In the earlyer versions from the Revit IFC Export all of the IfcBeam and Ifc Members automatically when given the Property Load Bearing and the value was always True.
Can you fix this?

![revit_2014](https://user-images.githubusercontent.com/45469583/49252010-367d1580-f423-11e8-9abd-0e3460c70078.png)
![revit_2019](https://user-images.githubusercontent.com/45469583/49252011-367d1580-f423-11e8-8879-1552bf724b52.png)

**Comment by WawanSolihin** [comment]
Not sure when this exactly changed, but the current code seems to assign LoadBearing for IfcColumn only. We have added support now for the Structural elements (under built-in category OST_Structure..) to automatically get LoadBearing=true. This will apply to IfcColumn, IfcBeam and IfcMember. If you would like to test it, it is included in a beta release: https://github.com/Autodesk/revit-ifc/releases/tag/IFC4RV-beta-v0.6.1
