### ISSUE TITLE
Ifc exporter 23.3.1 does not export Type parameters

### ISSUE THREAD

**Issue by mjkayali** [Autodesk/revit-ifc#723]
### Ifc exporter 23.3.1 does not export Type parameters

Hi, 
Im using the ifc exporter (**23.3.1**) to export one generic model and its type parameter and instance parameter using a user defined property set.
Unfortunately the ifc exporter does export the generic model including only the instance parameter.
I have attached the Revit model and the user defined property set i have used to make the export.
Hope to hear soon about the solution of this issue.
[test2_ifc.zip](https://github.com/Autodesk/revit-ifc/files/13828046/test2_ifc.zip)
[Project1.zip](https://github.com/Autodesk/revit-ifc/files/13828047/Project1.zip)
[test_UDPS_tp.txt](https://github.com/Autodesk/revit-ifc/files/13828048/test_UDPS_tp.txt)

### Revit Version

2023.0.x

### IFC for Revit Addon Version

Other / None

### Windows Version

11 22H2

**Comment by AlexSchleicher** [comment]
In addition to the IfcElement, try writing IfcElementType in the top line.

Like here:
IfcElement, IfcElementType

If type properties are to be exported, Type must be appended to the class name in the TXT file.
IfcWall, IfcWallType etc.

The differentiation between instance and type properties in the TXT file was changed with some update but in my opinion not properly communicated. Where can this information be found officially?

Hope this helps.

**Comment by mjkayali** [comment]
@AlexSchleicher Wonderful, it did solve the issue!
Thankyou!
