### ISSUE TITLE
PR: ZoneName for IfcSpatialZone does not work

### ISSUE THREAD

**Issue by MennoMekes** [Autodesk/revit-ifc#727]
### Problem Description

When exporting Areas to IfcSpatialZone (Revit 2024.2.0.63 + exporter v.24.2.0.49 on 2 different computers) the export aborts the moment I add a value to ZoneName. (Also tried the latest ZoneName parameter from the provided Shared parameter file 'IFC Shared Parameters-RevitIFCBuiltIn_ALL.txt' in the ProgramData\....\Contents\2024\ folder.

Error message is not helpful:
![image](https://github.com/Autodesk/revit-ifc/assets/66679121/c499eb07-c39c-4290-9c9c-f0a5ef2aaf06)

Without Naming the Zone this IfcSpatialZone is in, it works.
This is a very neccesary functionality since the Gross Area of a dwelling is part of several Zones.
IfcSpatialZones can be related to IfcZone:

![image](https://github.com/Autodesk/revit-ifc/assets/66679121/3c81c208-f41e-46ca-bae3-dff01e76cf94)

When double checking if something is allowed I usually open BlenderBIM and it is possible there so it should work from Revit as well:

![image](https://github.com/Autodesk/revit-ifc/assets/66679121/d6261434-b92f-4719-a400-a99352628e64)

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by parrela** [comment]
Hello, this works fine for me in 2024.2. would you be able to attach a simplified version of that file to this thread? Maybe there is something special with that file. Thanks.
Andy

**Comment by dvrvb** [comment]
Hi Andy,
I also get this error with 2024.2
See attached sample with a room, an area and a floor. All as "IfcSpatialZone", with the parameter "ZoneName".
Regards,
Dirk
[IfcSpatialZone_R2024_ZoneName.zip](https://github.com/Autodesk/revit-ifc/files/13865554/IfcSpatialZone_R2024_ZoneName.zip)

**Comment by parrela** [comment]
Whoa, OK I see it in your attached file. I think I was looking at the predefined type. I will file an item to look into it. Thanks.

**Comment by parrela** [comment]
Revit-217482

**Comment by pstrokap** [comment]
Any news on progress to fix this issue? I have the same error message and there is no workaround available as far as I know.

**Comment by parrela** [comment]
It is fixed in development version and we will try to get it into some future update.

**Comment by pstrokap** [comment]
We have tested this today in RVT2025 hoping it was fixed by now. Is there a date known when this will be included an update?

**Comment by parrela** [comment]
I can't give a date, but I don't see why it wouldn't be in the next release of open source.

**Comment by MennoMekes** [comment]
Thanks a lot!
Areas can now be exported to Ifc4x3 fro mRevit 2024 with the new epxorter v24.2.20.0.

![image](https://github.com/user-attachments/assets/4e0d6629-1292-42b8-82c3-c078e4126461)
