### ISSUE TITLE
PR: Custom Pset export issue IFC 24.2.0.49

### ISSUE THREAD

**Issue by xpt5** [Autodesk/revit-ifc#728]
### Problem Description

I came across a problem while exporting Wall information to IFC using the  24.2.0.49 version. The created Custom Pset has only partial information while comparing it with IFC exporter 22.6.2.0, more specifically with walls (IfcWallStandardCase). 

**24.2.0.49** (Revit 2024.1.1)* vs **22.6.2.0** (Revit 2022.1.4) using BIMcollabZoom. Output in Solibri is the same:

![BIMcollab_Zoom_DCDPpvLesq](https://github.com/Autodesk/revit-ifc/assets/30028308/af228d51-c35d-4e78-a0ad-efd146a8503f)

IFC info 24.2.0.49:
![notepad++_4wgTouCVeK](https://github.com/Autodesk/revit-ifc/assets/30028308/c34f1fd8-915d-4101-8221-8f16d63ddf31)

IFC info 22.6.2.0:
![notepad++_qi3KYwxVxF](https://github.com/Autodesk/revit-ifc/assets/30028308/a71db7b7-1514-4eaa-821e-17cfe1c6928e)

I used the same .json for the ifc export configuration but as you can see there is much less information when searching for the property NL-SfB which should be in the Pset_ElementTeamV-IFC custom Pset. Although I didn't make an extensive research, revit floors, roofs, stairs, plumbing fixtures and furniture seem not to be affected by this. 

Is there something that I am missing?
Thank you in advance

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

10 22H2

**Comment by t-vasyi** [comment]
Hi @xpt5,
This is unexpected.

I can take a look why some user-defined properties are not exported in 2024.
Can you share a simple model and user-defined property sets text file?

**Comment by xpt5** [comment]
Hi @t-vasyi, 

Sure, here you have a sample with a simple wall (Revit 20224) and the propertysets file. 
[folder.zip](https://github.com/Autodesk/revit-ifc/files/13889330/folder.zip)

**Comment by t-vasyi** [comment]
> _Since 24.1.0, to export type properties for the IFCElement, for example, 
a user should include "IFCElementType" in the proper .txt file.
In order for the type properties to be exported, the type entity should be specified IFCElementType as follows:
"PropertySet: testPset T IfcElement, IfcElementType"_

Try replacing
`PropertySet:	Pset_ElementTeamV-IFC	I	IfcElement`
with
`PropertySet:	Pset_ElementTeamV-IFC	I	IfcElement, IfcElementType`

![image](https://github.com/Autodesk/revit-ifc/assets/115650049/6c568b00-d6f5-40f1-9875-70bd58cfe2d6)

**Comment by t-vasyi** [comment]
It is from the Release notes here:
https://github.com/Autodesk/revit-ifc/releases
