### ISSUE TITLE
INQ: IFC exporter for Revit 2025 (.net 8)

### ISSUE THREAD

**Issue by erfajo** [Autodesk/revit-ifc#770]
### Inquiry description

Is there a plan for the IFC exporter for Revit 2025 or is this repository only meant for supporting the older versions using the .net framework, and you will create a new repository for .net core and beyond?

I am asking since I have created some nodes for Dynamo that are using the IFC exporter, and it is quite challenging that you aren't ready with a version supporting the current Revit version when it is being officially released, especially this time when the change from .net 4.8 to .net 8 is a huge step.

Sadly I can't choose Revit 2025.x and IFC addon 25.x.x in the below dropdowns… however it says something about following the pace!?

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
We are definitely planning to add Revit 2025 to the open source - it is not just for old branches.  Can't give you an ETA, but we are actively working on it.

**Comment by erfajo** [comment]
May I suggest some more attention to the Revit releases/roadmap?

It would help a lot if someone could upgrade the latest version to the new Revit versions without any connections to your roadmap for new functions, so we all can move on when new Revit versions are released, especially the yearly major release?

…and this time is it really troublesome that nothing is ready for the step from .net framework to .net core.

**Comment by AngelVelezSosa** [comment]
This is more a case of the coordination being trickier than usual for that very reason.  In general, I agree that it would be good to have the open source ready to go sooner.
