### ISSUE TITLE
UserDefined Pset (IfcSite, IfcBuilding) regression?

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#78]
R2019

With the exporter v.19.1 I'm able to export a UserDefined Pset for IfcSite and IfcBuilding (in IFC4 & IFC2x3).

With the current solution of the branch IFC4RV, I'm only able to export a UDPset for IfcBuilding, not anymore for IfcSite (in IFC4 & IFC2x3).

With the current solution of the branch DEV, it seems that for both, IfcSite and IfcBuilding, it isn't working anymore (in IFC4 & IFC2x3).

Best regards,
Dirk

**Comment by dvrvb** [comment]
unfortunately the regression in the DEV branch is not limited to IfcSite and IfcBuilding: it's applicable for all other classes too. In the IFC4RV branch it seems to be OK for all other classes (except IfcSite).

<img width="446" alt="image" src="https://user-images.githubusercontent.com/41319048/50310574-b4709180-04a2-11e9-9b5c-beeb32b65d31.png">

**Comment by jmirtsch** [comment]
Hi Dirk,

Looks like some reasonably significant changes by a few of use relating to properties so all feedback is appreciated.  I've just tested this project https://drive.google.com/file/d/1EleciJJM3tnuv45WSSuE2aF1oEPWLZ41/view?usp=sharing  with this pset definition 
https://github.com/jmirtsch/RevitIfcExportCommonPset/blob/master/IfcCommonParameterSets.txt
and it worked for me.  If it also works for you, can you please share a reproducible case so I can test it?  You can send it privately if you prefer.

Cheers,

Jon

**Comment by dvrvb** [comment]
Hi Jon,

I notice that you shared a mappingfile for the common parameters, but it is the user defined propertyset that isn't working anymore.
I attached a rvt sample and the UDPset mapping file, and 2 IFC-exports in IFC4RV.
[2018-12-21 UDPset.zip](https://github.com/Autodesk/revit-ifc/files/2701761/2018-12-21.UDPset.zip)

- IFC with suffix: 'branchDEV' is the export where the UDPset 'RVB' is missing (for instance for IfcSite)
- IFC with suffic: 'exporter19.1' is the export where the UDPset 'RVB' is still created:
see screenshot: 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/41319048/50328140-494eab80-04f2-11e9-9269-e8ddf4fa2fb2.png">




BTW: I did try your sample, but I was not able to export it in IFC4RV: it is throwing an error screen
<img width="350" alt="image" src="https://user-images.githubusercontent.com/41319048/50328155-5a97b800-04f2-11e9-8b1b-cf3c82c68760.png">


I did check my Category-Class mapping file, but I don't see anything strange there.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/41319048/50328179-7bf8a400-04f2-11e9-9874-ec891dacce62.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/41319048/50328188-80bd5800-04f2-11e9-91f7-2437cbbc9ee3.png">

For IFC2x3CV2.0 it is not giving an error. 
But in both cases there is no UDPset created.

Best regards,
Dirk

**Comment by jmirtsch** [comment]
Hi Dirk,

If you pull the latest commits, I believe I have resolved these two issues.  Thanks for reporting.  Let us know if you see anything further amiss.

Cheers,

Jon

**Comment by dvrvb** [comment]
Hi Jon,

Unfortunately, the creation of the UDPset of IfcSite is not working yet. 
Just a remark: in 19.1 it was possible to create an UDPset for IfcSite, as long as IfcSite has geometry (a topography). Without geometry it was also not possible to create a UDPset. It would be nice if it would be possible in both cases (with or without geometry), but if this is not really possible, it's OK that at least it would be again possible to have an UDPset for an IfcSite with geometry.

But, your commits did fix:
- the creation of UDPsets on all the other Classes: :-)
- the error is gone in the export of structural framing: :-)

Although I'm lately solely focussed on the IFC4RV export, I now indeed noticed some other geometric issue in the IFC2x3CV2.0 export. It concerns the cutting of an opening through more than 1 wall. But at first I'll have to take a closer look to find out if it's happening in more models, and if can isolate the issue. If so, I'll will post it in a separate issue.

Best regards,
Dirk

**Comment by jmirtsch** [comment]
I see why about the site (and project) properties,  I've just committed a code change that enables this.

I note that in your user defined property set, you're adding the globalID as a property for entities such as site.  I see at the moment it's not necessarily using the built in parameter for the site guid and I've pushed a commit that should now ensure it is.

Let me know if you observe further issues.

**Comment by dvrvb** [comment]
For IFC2x3CV2.0: it is indeed fixed for IfcSite (and indeed its now also possible to have an UDPset for IfcProject: very nice that you made this also possible!).

But for IFC4RV ... I did try a few models, but I'm not getting any output anymore ... (it's not even giving an error message).

About the GlobalID: for IfcSite I added to the UDPset the parameter IfcSite GUID (of the Project Information), since this is the built in parameter for the GlobalID for the abstract IfcSite. (next to the parameters IfcProject GUID, IfcBuilding GUID) ... but it seems that the mapping of this parameter is now blocked :-(

**Comment by jmirtsch** [comment]
Sorry, I hadn't checked project property exporting in IFC4.  I notice that there is a typecheck in IfcReldefines that should only occur in Ifc2x3 and earlier.  I've modified this in the latest commit.

I'm not sure I understand the comment about the globalId.  I see the parameter is readonly from the user interface.

Let me know if this doesn't work better.

**Comment by dvrvb** [comment]
Hi Jon,

IFC4 output seems to be fixed again :-)

Concerning the mapping of IfcSite GUID: is this picture making it more clear?
Originally (with exporter 19.1) it was possible to map the parameter IfcSite GUID, but now it seems not possible anymore.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/41319048/50344417-2d1b3080-052b-11e9-8932-d0b3dc9be6d4.png">




These are the only 3 GUIDs that are editable, as long as one follows the steps as I described at:
https://sourceforge.net/p/ifcexporter/discussion/general/thread/634a2a16/#bc3a

**Comment by jmirtsch** [comment]
Seems there are still some bugs to clean up. I seem to get different behaviour than you though so sharing your files again or a screen share to debug together might be needed.

I note there is a duplication of common property sets so I need to see why the user defined doesn't get included when this is triggered the first (existing) call.

![181222 globalid property](https://user-images.githubusercontent.com/791757/50364322-ad8d7000-05c3-11e9-9faa-81af350eea3b.png)


The open source plugin sets the building, site and project guids.  So it's possible I could provide a little utility to set the builtin parameter

 (probably in ggRevitIFC unless I talk to Angel and we provide a utility IFC plugin for this).

**Comment by dvrvb** [comment]
Concerning the GUIDs of IfcProject, IfcBuilding, IfcSite.
These are the only 3 entities where it is possible to give it your own GUID, before the exporter is creating one. If you do so, the exporter is not even overwriting it. 
This is nice behavior for these 3 entities, because in that way it is easily possible to have identical GUIDs for federated models (without the need of using the same template to start with).

**Comment by dvrvb** [comment]
(just for future reference, specific about the issue of IfcGUID)
with the update to **R2019.2**, each IfcGUID (also of IfcProject/IfcSite/IfcBuilding) is now 'read/write'.
It also solves the issue of an IfcGUID of a copied object. After IFC export the new GUID is now visible.

**Comment by AngelVelezSosa** [comment]
Right, this is independent of the version of IFC.  Hopefully that gets rid of all of the IFC GUID issues of the past.

**Comment by dvrvb** [comment]
and if something strange would happen, it is now at least possible to correct it (temporary) in the source model!

**Comment by dvrvb** [comment]
Some housecleaning: somewhere down the road the issue is fixed, so the issue can be closed.
