### ISSUE TITLE
Installation Path (destination folder)

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#79]
Nice that is now easily possible to build the installable exe with the current solution at the DEV branch.
Is it possible to change the installation path, which is currently set on C:\ProgramData\Autodesk\ApplicationPlugins\IFC 2019.bundle\Contents\2019\ ,
to set it back to the default C:\Program Files (x86)\Revit IFC 2019 ?

Best regards,
Dirk

![2018-12-18_11-48-14](https://user-images.githubusercontent.com/41319048/50149599-ed9add00-02bb-11e9-8eaf-ed5104712939.png)

**Comment by jmirtsch** [comment]
C:\ProgramData\Autodesk\ApplicationPlugins\IFC 2019.bundle\Contents\2019\ is the default path used by the appstore installer, and makes it clearer when other applications are using the plugin about which might be in use.

Is there a problem with this location as a new default?

**Comment by dvrvb** [comment]
Not really a problem. Thx for the explanation.
I wasn't aware of this new default. It seems I always used the Sourceforge version, never the Appstore one.
Regards,
Dirk
