### ISSUE TITLE
INQ: 12D model import into Revit using IFC file

### ISSUE THREAD

**Issue by AndreB916** [Autodesk/revit-ifc#802]
### Inquiry description

Hi, not sure I am at the right place to post this issue.

I am trying to import a 12D model into Revit using IFC format, but after importing the 12D model into Revit, it becomes a whole entity and cannot select individual element to get data from the model.

The category of the entity is site. The 12D model includes just tins and strings. We assume that we should map the tins and strings with Revit family category, but we don't know which category to map with.

Does anyone have any ideas about this issue? Thanks a lot.

### Revit Version

2023.0.x

### IFC for Revit Addon Version

23.1.0

### Windows Version

11 22H2

**Comment by AngelVelezSosa** [comment]
Hello, I'm not sure I understand the contents of the IFC file.  How many IFC rooted entities are there in there?  We generally create 1 Revit element per rooted entity.  We don't "split" the IFC entity up.  Also, is this open or link?

**Comment by AndreB916** [comment]
> Hello, I'm not sure I understand the contents of the IFC file. How many IFC rooted entities are there in there? We generally create 1 Revit element per rooted entity. We don't "split" the IFC entity up. Also, is this open or link?

Hello Angel, thank you for your reply. Sorry, I am new to IFC, so I don't know what is IFC rooted entity and how to know the number of it. Would you mind telling me how to get the number of it?

Also, we are using link IFC to import the IFC.

We want to get the level information of 12D model in Revit by doing a spot elevation, but since the model is a whole entity, we are not able to do that.

**Comment by AngelVelezSosa** [comment]
If you look at it in a viewer, say the KIT viewer, and look at the tree structure on the left that shows the project, site, building, etc., how many objects how up on that list?

**Comment by AndreB916** [comment]
![Capture](https://github.com/user-attachments/assets/9bd5d20f-19ff-40f8-b1f8-863e49d391f4)

Do you mean this tree structure? I am viewing the IFC in Autodesk viewer.

**Comment by AngelVelezSosa** [comment]
Right.  So there is one object called "Tin RS100" and it contains 10 geometries inside it.  What you want from the original software is for them to export 10 "Tin" objects each with 1 geometry and the element data.  This seems like an issue with your exporting application.

**Comment by AndreB916** [comment]
Thank you so much. 

So you mean if the IFC contains more than one objects, say it contains 5 objects, then it will create 5 elements after importing into Revit, then we will be able to select each element in Revit, am I right?

**Comment by AngelVelezSosa** [comment]
Correct.  We create on Revit element per every object in the IFC file, not every geometry (since the objects, not the geometry, has the parameter information).
