### ISSUE TITLE
PR: Export contains parameters not defined in export mapping table

### ISSUE THREAD

**Issue by kohout-lukas** [Autodesk/revit-ifc#811]
### Problem Description

Using Revit **Export user defined property set** option results in invalid IFC. Attached TXT file contains two property sets, both containing one parameter. Parameter Area is exported even though it is not definod. 
My understanding is that it exports Revit internal parameter HOST_AREA_COMPUTED. Exporter somehow subtracts preifxes in parameter definition and exports it anyway.

See attached files:
1. In RVT there is no user visible parameter named Area, only through RevitLookup.
2. In TXT file there is no mapping for parameter Area, only CZ_M2_Area
3. In IFC file there are both property sets and both parameters.
![bug](https://github.com/user-attachments/assets/39e2ba53-7b23-4489-962d-6da1c7be06df)
[IFC_EXPORT_bug.zip](https://github.com/user-attachments/files/17190985/IFC_EXPORT_bug.zip)

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by denizmaral** [comment]
You mapped `CZ_M2_Area` to `Area` in property set `CZ_M2`. It is about your setting, isn't it?

**Comment by kohout-lukas** [comment]
Yes, I mapped it like ou say. But the element in screenshot does not have `CZ_M2_Area`, only `Area`, which is not being mapped and still gets exported.

**Comment by denizmaral** [comment]
Your goal is then something like that: 

`PropertySet:	CZ_M2	I	IfcElement
CZ_M2_Area	Area
PropertySet:	CZ_M3	I	IfcElement
CZ_M3_Volume	Volume`

**Comment by kohout-lukas** [comment]
Well, no. TXT file in the post is correct, that is how I want it. 
In the images below, there are snapshots of element in `IFC `and `RVT`. In `RVT `there is no parameter `CZ_M2_Area`a and yet, it gets exported as seen in `IFC `snapshot.
![IFC](https://github.com/user-attachments/assets/706a71bf-b614-4936-ac25-5a1787176fe3)
![RVT](https://github.com/user-attachments/assets/86a68af1-17e8-4aa8-9239-461e3442f770)

**Comment by AngelVelezSosa** [comment]
Can you re-summarize the problem (just for area?)  You want a property set for all IfcElement called CZ_M2, and it should have a property called Area that is an area calculation that comes from a Revit parameter called CZ_M2_Area?  And it doesn't work, but if you change IfcElement to IfcColumn, it does?

**Comment by denizmaral** [comment]
Now I got it. I could not open the file because I don't have Revit 2025 on my computer. You don't see Area parameter in Revit UI but there is an API-Parameter unter parameters that is being mapped to your parameter. Even though you don't assign the user defined parameter to that family, it still creates a property set and take the Area value.

**Comment by kohout-lukas** [comment]
Yes, exactly. Thanks.

**Comment by AngelVelezSosa** [comment]
That seems by design, unless I am missing something.

**Comment by kohout-lukas** [comment]
OK, if it is by desing, can you describe the reasoning behind it? How can parameter you do not define to be exported still be exported?

**Comment by AngelVelezSosa** [comment]
You are looking for a parameter called "Area".  There is a parameter called "Area" (at least in English), it just isn't visible in the parameters dialog.  If you called it anything else, it wouldn't show up.  Unless I am missing the issue.

**Comment by kohout-lukas** [comment]
I know there is and I see it with RevitLookup. I just do not want it to be exported to IFC. And I thought, that by using TXT file I wil be able to. But looks like it does not work. 
Maybe we could use Teams or Google Meet to talk and I could explain it better.

**Comment by AngelVelezSosa** [comment]
What I mean is, can you call your parameter anything other than "Area"?  On our roadmap, we have ways to improve control over what does or doesn't export, but in the meantime, I'm suggesting calling it "_Area" or "MyArea" or anything.

**Comment by kohout-lukas** [comment]
Well, in this case I cannot since it is mandatory requirement from the investor. But for other instances I will count with that. Thank you for the input. BTW., is the roadmap somewhere public?
