### ISSUE TITLE
Hidden Topography

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#82]
R2019
IFC4RV | IFC2x3CV2.0

issue: although the Topography is hidden in the View, and the option "Export only elements visible in view" is used, the Topo is still exported.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/41319048/50477518-08acd180-09cd-11e9-91be-8202928bca4b.png">

It seems to be some kind of regression since this issue is not present in exporter version 19.1.
It isn't a recent regression. Although it occurs with the current Github-DEV-branch-solution, it also occurs with the Github-IFC4RV-branch-solution-of-13thdec2018.
So, somewhere before that point the regression took place.

[2018-12-27 IfcSite Topo export.zip](https://github.com/Autodesk/revit-ifc/files/2712228/2018-12-27.IfcSite.Topo.export.zip)

Best regards,
Dirk

**Comment by dvrvb** [comment]
For R2020, with 20.1.0.1
IFC4RV1.2 & IFC2x3CV2.0

Issue similar as described at https://sourceforge.net/p/ifcexporter/discussion/general/thread/b17e88e860/

The option "export only elements visible in view" is ignored for the Toposurface, but it is debatable that this is an issue, because it is coded that way. So it is more a wish/request that if the option "export only elements visible in view" is ticked, really only the visible geometry will be exported (kind of same issue with the Steel Elements).

<img width="649" alt="image" src="https://user-images.githubusercontent.com/41319048/63650093-204c7d80-c747-11e9-85a5-9dced5bcd99b.png">

**Comment by MagneGanz** [comment]
In Revit 2019 we colud easely use "Export only visible elements in view" to prevent Toposurface from being exported. In 2020 IFC 2x3 this is not working. We do need a way to prevent Toposurface from being exported. I cannot see why "Export only elements visible in view" should not be treated differently for Toposurface.

**Comment by eibre** [comment]
It seems to be impossible to not export the topo without deleting it! Tried "Not Exported" in class mapping table, and IfcExportAs paramneter set to "DontExport".
![image](https://user-images.githubusercontent.com/5968613/72150342-9fb0b580-33a5-11ea-8f53-fc549d4949e1.png)

**Comment by AngelVelezSosa** [comment]
This is a known issue that is being addressed.

**Comment by dvrvb** [comment]
Hm, I don't think that it is very handy to 'close' unsolved issues, even if they are already addressed more than 1 year ago.

**Comment by dvrvb** [comment]
Nice! Issue is solved/fixed with commit https://github.com/Autodesk/revit-ifc/commit/a3d89f7ddad0137d52cec8f48a6f553e63690415
