### ISSUE TITLE
INQ: Export multiple ifc links 

### ISSUE THREAD

**Issue by ShehabFekry** [Autodesk/revit-ifc#823]
### Inquiry description

Is there any way that I can export links and model in one ifc file? that can be done in Revit 2025 by selecting the option "Export in same project" , can it be done in Revit 2023? using Revit or Revit API?

The only valid option is Export links as separate ifc files.

### Revit Version

2023.1.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

11 22H2

**Comment by denizmaral** [comment]
Federated export is in Revit 2024+ possible.

**Comment by AngelVelezSosa** [comment]
There was a lot of work done in Revit itself to accommodate the ability to federate links which showed up in Revit 2024 as stated above.
