### ISSUE TITLE
Slanted Pile geometry regression

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#83]
R2019
Original issue and sample file at https://sourceforge.net/p/ifcexporter/discussion/general/thread/bbf9d775/

Although initially the commit https://github.com/Autodesk/revit-ifc/commit/be8b42851d89538bcd496e8d792f69e0f9b8dcdd solved the issue,
the issue is back.
As far as I can track down, the regression took place between Nov.02 - Nov.15.

Best regards,
Dirk

**Comment by WawanSolihin** [comment]
The fixed code is unchanged. It could be change in the behavior in the base code. Need to take a closer look.

Regards,
Wawan

**Comment by dvrvb** [comment]
Thx for the fix. Issue can be closed.
