### ISSUE TITLE
Out-of-date CAD links in IFC mapping options

### ISSUE THREAD

**Issue by abalazy** [Autodesk/revit-ifc#84]
IFC Options window shows me CAD layers from removed links.
Is there a way to remove them from Revit mapping categories?
![image](https://user-images.githubusercontent.com/43812564/50558125-a7963e00-0ceb-11e9-8a55-3d14f4ffef37.png)

**Comment by AngelVelezSosa** [comment]
Have you made any changes to the table?  If not, you can delete that file and then press the "Standard" button.  That will get reset to the normal.  Otherwise, you can open up the file in Notepad and manually delete those lines.
