### ISSUE TITLE
IFC4RV: IfcSite geometry issue (Topography)

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#87]
R2019.2
IFC4RV IfcSite geometry issue (Topography)

Although I'm not completely sure that this isn't an IFC-Viewer issue, it seems that something is going on with the geometry of a topography in combination with the inprint of building pads.
Tested with BIMVision. FZKViewer isn't showing anything.
[2019-02-03 topo geometry issue.zip](https://github.com/Autodesk/revit-ifc/files/2825655/2019-02-03.topo.geometry.issue.zip)
<img width="754" alt="image" src="https://user-images.githubusercontent.com/41319048/52178763-7d480c80-27d2-11e9-8bca-e4c159abc01b.png">

Regards,
Dirk

**Comment by WawanSolihin** [comment]
Should be fixed by commit 1af17b5

**Comment by dvrvb** [comment]
Indeed fixed: thx!
nice clean geometry:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/41319048/52917435-c8dada00-32eb-11e9-825b-76b72275e79f.png">
