### ISSUE TITLE
Install Beta: How to know that the correct version is used?

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#89]
@WawanSolihin I installed the latest Beta5-v19.2.0 release from here: https://github.com/Autodesk/revit-ifc/releases/tag/Beta5-v19.2.0 but seems like it's not overriding the old one (19.1.2.0)?

![image](https://user-images.githubusercontent.com/5968613/52919668-1adc2980-3305-11e9-94c1-93a36a63c0e0.png)

I tried to uninstall the ifc-exporter from add/remove programs before installing the new one. I got three warnings of unsigned addins when opening Revit so I know they are installed. How can be sure that the beta version is used?

**Comment by WawanSolihin** [comment]
Hi Einar,

Thanks for the feedback. This is not yet a final release and we haven’t changed some of the version numbers so it may still show up as 19.1.2.0 currently. We are focusing on fixing some bugs especially regression bugs in these Beta releases. Once we have done enough tests, we will move the version numbers to 19.2.0.0. As long as you installed the Beta5 version, it should use the latest.

Regards,
Wawan
