### ISSUE TITLE
Wish: Export grids when "export only visible in view" is checked and the active view is a 3D-view.

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#90]
I know many of us want this checkbox:
![image](https://user-images.githubusercontent.com/5968613/52919785-3f84d100-3306-11e9-8b78-6d2fc972f926.png)

**Comment by WawanSolihin** [comment]
You can export IfcGrid currently by just making sure that the IFC Option table is set to the correct value: IfcGrid
![image](https://user-images.githubusercontent.com/31854582/54223848-526c7900-4533-11e9-89ed-1bb8003d8ab6.png)

**Comment by eibre** [comment]
Thank you for helping @wawansolihin, but grids are not visible in 3D views in Revit and thus not exported when "export only visible in view" is checked and the active view is a 3D view.

**Comment by andydandy74** [comment]
I second this wish. Would be really useful.

**Comment by ebussiere** [comment]
Just over a year later, but I third this wish

**Comment by sebortner** [comment]
Another year later, I fourth this wish :) Also, I can't seem to export grids if the model has been georeferenced accordingly. I tried the same 2D settings in my geomapped (height is correct) versus a "fresh" new model. Grid export worked with an empty model but not in a georeferenced one.

**Comment by eibre** [comment]
Now in Revit 2022 grids are visible in 3D, maybe this issue has resolved itself?

**Comment by sebortner** [comment]
I saw that aswell, yes! The change log got me excited. It would have been nice to have at least a working grid export in the older versions with 2D views as well. Seems like a lottery everytime I export ifcgrid from Revit.

**Comment by AngelVelezSosa** [comment]
I just checked and it looks like this doesn't immediately work with Revit 2022.  But - now that grids are visible, it should be a much simpler fix than before.  So I am going to create an item to see if we can get this in the next update.

**Comment by AngelVelezSosa** [comment]
Actually, user error - this does work now!  It didn't work in my simple case because all of the grid lines were parallel, and that's not supported in IFC.  Adding a proper grid exported.  Please verify.
