### ISSUE TITLE
AddSavedConfigurations return null!?

### ISSUE THREAD

**Issue by erfajo** [Autodesk/revit-ifc#93]
I have just released a set of nodes supporting your IFC Exporter.

https://erfajo.blogspot.com/2019/02/ifc-export-and-some-other-new-nodes.html
https://forum.dynamobim.com/t/orchid-package-released-at-github/22671/40

However, there is still one thing there puzzles me. That is why the function `AddSavedConfigurations()` do not work!?
I can get “In session” and “Built in” configurations…

```
var configurations = new IFCExportConfigurationsMap();
configurations.Add(IFCExportConfiguration.GetInSession());
configurations.AddBuiltInConfigurations();
configurations.AddSavedConfigurations();
var elements = configurations.Values.ToList();
```

It seems that other have the same problem as I.
https://sourceforge.net/p/ifcexporter/discussion/general/thread/d08ff0b5ac/

**Comment by dobrzhanskyi** [comment]
I have the same problem.

It works only when I open the IFC exporter, close it, and now the user-created configurations show up

**Comment by erfajo** [comment]
Since nothing has happened and I have given up anything is going to happen I am closing this issue...

**Comment by AngelVelezSosa** [comment]
Even if it hasn't been worked on, it is still an open issue; I'll reopen.

**Comment by denizmaral** [comment]
I had same problem. The reason is that `TheDocument` property is `private set`. When you open UI, UI sets the TheDocument property to current document and then you can retrive SavedConfigs. You can use System.Reflection to set TheDocument to your current document and then it should work.

**Comment by erfajo** [comment]
thanks @denizmaral 

It is an interesting observation that it is the UIDcument instead of Document that is used, this might be the devil behind why this doesn't work when I am creating dynamo nodes for IFC export. Surely I want to be able to switch documents so I can export background opened documents.

However, I could not manage to use your solution but it has given me some ideas that I hope can solve the issue.

@AngelVelezSosa Is it the case that we must provide UIDocument? And why is it so, I am sure others want to be able to export using background opened documents!?

**Comment by denizmaral** [comment]
It is using Document but it's `protected set`. Only Add-in can set it but you can set via System.Reflection like that:
`ifcAssembly.GetType("BIM.IFC.Export.UI.IFCCommandOverrideApplication").GetProperty("TheDocument", BindingFlags.Static | BindingFlags.Public).SetValue((object) null, (object) doc);`
If you want to set document when you switch between documents then you should use UIDocument.ViewChanged or DocumentClosed event to set new value..
